### ISSUE TITLE
Cyrillic attachment name is undefined

### ISSUE THREAD

**Issue by danbka33** [Webklex/php-imap#101]
#45 duplicate

I have same issue. Hope this helps solve the problem. 
Current version in composer:  2.5.0

For this mail I get undefined. Real file name is Остатки 4.02..xls
`--=_0b2d23d5602ca8725a5d021a1cddaeb4\r\n
Content-Transfer-Encoding: 8bit\r\n
Content-Type: text/plain; charset=UTF-8;\r\n
 format=flowed\r\n
\r\n
\r\n
\r\n
-- \r\n
НОВЫЕ МОДЕЛИ ПО ССЫЛКЕ\r\n
\r\n
\r\n
С Уважением к Вам и Вашему бизнесу,\r\n
\r\n
--=_0b2d23d5602ca8725a5d021a1cddaeb4\r\n
Content-Transfer-Encoding: base64\r\n
Content-Type: application/vnd.ms-excel;\r\n
 name="=?UTF-8?Q?=D0=9E=D1=81=D1=82=D0=B0=D1=82=D0=BA=D0=B8_4=2E02=2E=2Ex?=\r\n
 =?UTF-8?Q?ls?="\r\n
Content-Disposition: attachment;\r\n
 filename*=UTF-8''%D0%9E%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%B8%204.02..xls;\r\n
 size=94208\r\n
\r\n`

For this mail I get - Авангард склад 07.02.2021.xls. Everything works well here. 
`--------_29865_-1932362997_6316\r\n
Content-Type: text/plain;\r\n
\tcharset="utf-8"\r\n
Content-Transfer-Encoding: base64\r\n
\r\n
0KHQvNC+0YLRgNC40YLQtSDQstC70L7QttC10L3QuNC1Lg==\r\n
\r\n
--------_29865_-1932362997_6316\r\n
Content-Type: application/octet-stream;\r\n
\tname="=?utf-8?B?0J7RgtGH0LXRgg==?="\r\n
Content-Disposition: attachment;\r\n
\tfilename="=?utf-8?B?0JDQstCw0L3Qs9Cw0YDQtCDRgdC60LvQsNC0IDA3LjAyLjIwMjE=?=\r\n
\t=?utf-8?B?Lnhscw==?="\r\n
Content-Transfer-Encoding: base64\r\n
\r\n`

**Comment by alaevka** [comment]
Same issue

**Comment by spyp** [comment]
I have the same issue and problem is utf-8?B? for attachments
that means if we remove utf-8?B? and decode it we have name and filename for attachments
for attachments i think we should decode with base64 decde utf8

**Comment by nicohell** [comment]
Hi
Same issue (with no Cyrilic)... 
Don't know if there's a link but I made traces and found a leading comma & space in attribute key  : 

`[2021-06-14 18:09:16] local.INFO: , name {"script":"vendor/webklex/php-imap/src/Attribute.php 41"} `

This issue happens (both in Content-Type and in Content-Disposition) when, in rawData, filename is made up of more than one item (line or key=value) : 

```
--------------C7764F0612F9E6913B09787D
Content-Type: application/pdf;
 name="=?UTF-8?Q?PPT_support_CS_SYDED_du_19_05_2021_VF_avec_r=c3=a9sultat_d?=
 =?UTF-8?Q?es_votes=2epdf?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*0*=UTF-8''%50%50%54%20%73%75%70%70%6F%72%74%20%43%53%20%53%59%44;
 filename*1*=%45%44%20%64%75%20%31%39%20%30%35%20%32%30%32%31%20%56%46%20;
 filename*2*=%61%76%65%63%20%72%C3%A9%73%75%6C%74%61%74%20%64%65%73%20%76;
 filename*3*=%6F%74%65%73%2E%70%64%66
```

class Header gets this rawData : 
```
[2021-06-14 19:36:09] local.INFO: Content-Type: application/pdf;
 name="=?UTF-8?Q?PPT_support_CS_SYDED_du_19_05_2021_VF_avec_r=c3=a9sultat_d?=
 =?UTF-8?Q?es_votes=2epdf?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*0*=UTF-8''%50%50%54%20%73%75%70%70%6F%72%74%20%43%53%20%53%59%44;
 filename*1*=%45%44%20%64%75%20%31%39%20%30%35%20%32%30%32%31%20%56%46%20;
 filename*2*=%61%76%65%63%20%72%C3%A9%73%75%6C%74%61%74%20%64%65%73%20%76;
 filename*3*=%6F%74%65%73%2E%70%64%66
 {"script":"vendor/webklex/php-imap/src/Header.php 202"} 
```
then builds class object
```
[2021-06-14 19:36:09] local.INFO: array (
  'content_type' => 
  array (
    0 => 'application/pdf;',
    1 => 'name="=?UTF-8?Q?PPT_support_CS_SYDED_du_19_05_2021_VF_avec_r=c3=a9sultat_d?=',
    2 => '=?UTF-8?Q?es_votes=2epdf?="',
  ),
  'content_transfer_encoding' => 'base64',
  'content_disposition' => 
  array (
    0 => 'attachment;',
    1 => 'filename*0*=UTF-8\'\'%50%50%54%20%73%75%70%70%6F%72%74%20%43%53%20%53%59%44;',
    2 => 'filename*1*=%45%44%20%64%75%20%31%39%20%30%35%20%32%30%32%31%20%56%46%20;',
    3 => 'filename*2*=%61%76%65%63%20%72%C3%A9%73%75%6C%74%61%74%20%64%65%73%20%76;',
    4 => 'filename*3*=%6F%74%65%73%2E%70%64%66',
  ),
) {"script":"vendor/webklex/php-imap/src/Header.php 203"} 
```

Problem in extractHeaderExtensions() from Header's class, imploding on ', ' does not manage multi-items values : 

```
[2021-06-15 15:46:20] local.INFO: , name="=?UTF-8?Q?PPT_support_CS_SYDED_du_19_05_2021_VF_avec_r=c3=a9sultat_d?=, =?UTF-8?Q?es_votes=2epdf?=" {"script":"vendor/webklex/php-imap/src/Header.php 651"} 
[2021-06-15 15:46:20] local.INFO: , filename*0*=UTF-8''%50%50%54%20%73%75%70%70%6F%72%74%20%43%53%20%53%59%44 {"script":"vendor/webklex/php-imap/src/Header.php 651"} 
[2021-06-15 15:46:20] local.INFO: , filename*1*=%45%44%20%64%75%20%31%39%20%30%35%20%32%30%32%31%20%56%46%20 {"script":"vendor/webklex/php-imap/src/Header.php 651"} 
[2021-06-15 15:46:20] local.INFO: , filename*2*=%61%76%65%63%20%72%C3%A9%73%75%6C%74%61%74%20%64%65%73%20%76 {"script":"vendor/webklex/php-imap/src/Header.php 651"} 
[2021-06-15 15:46:20] local.INFO: , filename*3*=%6F%74%65%73%2E%70%64%66 {"script":"vendor/webklex/php-imap/src/Header.php 651"} 
```

**Comment by Webklex** [comment]
Hi @danbka33 @alaevka @spyp @nicohell many thanks for your reports!

I'm going to merge this issue with #102 

Best regards,
