### ISSUE TITLE
Wildcard search?

### ISSUE THREAD

**Issue by EthraZa** [Webklex/php-imap#103]
There is a way to search for just part of email address?

I had try things like:
```php
$search = '1@domain.tld';
$search = '*1@domain.tld';
$search = '%1@domain.tld';

$folder->query()->where([['TO' => $search]]);
```
But can't get it to work.

There is a way to do a **wildcard search or regex search** before full download messages bodies? (It may be Gmail specific.)

**Comment by Webklex** [comment]
Hi @EthraZa ,
this completely depends on your mail provider. In general it is not supported / available.

If they do support it, you can utilize the `CUSTOM` search keyword to implement any additional search criteria.
Take a look at [Custom search criteria](https://www.php-imap.com/api/query) for more detail and examples.

Best regards,

**Comment by EthraZa** [comment]
Thank you. 
I'm using Gmail right now, I tryed lots of variants, but can't get it work.

But since I'm using a paid workspace account for this project, I have setup a Gmail content complience rule to add a special text to subject where I can easily filter on.
