### ISSUE TITLE
move method is moving the wrong message

### ISSUE THREAD

**Issue by EthraZa** [Webklex/php-imap#105]
```php
$messageA->move($new_folder); // Moves msg ID 1
$messageB->move($new_folder); // Try to move msg ID 2 and fails
```

Why:
At least in Gmail, for some reason I was unable to pinpoint yet, PHP-IMAP is using **MID** (message number/ID) instead of **UID** (Unique ID). So, when we move the msg ID 1 the second message becomes the 1, so it fails to move ID 2 because it does not exist anymore.

Question:
Am I missing some setup to get it using UID instead of MID?

**Comment by Webklex** [comment]
Hi @EthraZa ,
thanks for your report.

You can switch to UID by settings `options.sequence` from `\Webklex\PHPIMAP\IMAP::ST_MSGN` to `\Webklex\PHPIMAP\IMAP::ST_UID`.

I highly recommend to do so :)

Best regards,

**Comment by EthraZa** [comment]
How on earth did I miss that? Gonna check it.
But buddy, why make ST_MSGN the default?

**Comment by Webklex** [comment]
Well, that's historic - If I change it now, it might break other peoples code... so I've never changed it...

You don't happen to have any good update strategy? 

Best regards,

**Comment by EthraZa** [comment]
If it can break other people code it's not good to change. 
Maybe make it available on the Getting started doc examples will suffice to make sure people notice the option exists and is what is the default. 
Also it will show how to use this advanced options since the docs does not let it clear if it goes in the same level as the other options or go inside an options array as it is inside the imap.php.

**Comment by Webklex** [comment]
Hi @EthraZa,
with the next release `IMAP::ST_MSGN` won't  be the default anymore. 

Thanks for raising the issue!

Best regards,
