### ISSUE TITLE
delete method not working on Gmail

### ISSUE THREAD

**Issue by EthraZa** [Webklex/php-imap#106]
At least on Gmail, I can't get delete to work. It returns true, but does nothing. 
Manually set 'Deleted' flag on a message does nothing as well.

Am I noobing here?

**Comment by EthraZa** [comment]
Here is a very good explanation on the why the \Deleted flag does nothing on Gmail:
http://yz.mit.edu/wp/gmail-and-imap/

**Comment by Webklex** [comment]
Hi @EthraZa ,
thanks for the followup. I'll add it to the documentation. Any idea on where it could fit?

Ref.:
- https://www.php-imap.com/
- https://github.com/Webklex/php-imap-documentation

Best regards,

**Comment by EthraZa** [comment]
Do you have a reliable way to detect when you are connected to Gmail? 
Use the host is not reliable because people can use a cname DNS entry.

**Comment by Webklex** [comment]
Yeah I was wondering about this as well..
Perhaps `$client->getConnection()->getCapabilities()` has some interesting information?

Best regards,

**Comment by EthraZa** [comment]
Also taking a look at [Gmail IMAP Extensions](https://developers.google.com/gmail/imap/imap-extensions#checking_for_the_presence_of_extensions)

Maybe the delete method can look something like this:
```php
public function delete($expunge = true, $trash_path = "[Gmal]/Trash", $force_move = false) {
        $status = $this->setFlag("Deleted");

        if($force_move || in_array("X-GM-EXT-1", $this->client->getConnection()->getCapabilities())) {
                $this->move($trash_path);
        }

        if($expunge) $this->client->expunge();

        $event = $this->getEvent("message", "deleted");
        $event::dispatch($this);

        return $status;
}
```

What do you think?

**Comment by Webklex** [comment]
Hi @EthraZa ,
many thanks for your suggestion. As of [v3.0.0-alpha](https://github.com/Webklex/php-imap/releases/tag/3.0.0-alpha) you can now use the `Message::delete()` method as suggested by you. 
There is however one difference. If you don't provide a `$trash_path`, the default common folder path from `options.common_folders.trash` gets used instead.

Best regards,
