### ISSUE TITLE
thread

### ISSUE THREAD

**Issue by tkowalski29** [Webklex/php-imap#107]
Hi how work thread in message i have 

```
$folder = $this->client->getFolderByPath($folderName);
        $message = $folder->query()
            ->getMessage($messageId);
        $results = $message->thread();
       
```

but result is `Call to a member function query() on null`

**Comment by Webklex** [comment]
Hi @tkowalski29 ,
it looks like the folder path you defined in `$folderName` does not exists. Are you sure that `$folderName` contains the correct folder path?

If you don't know if the folder path exists, you can check it before you use it:
```php
$folder = $this->client->getFolderByPath($folderName);
if ( $folder != null) {
    $message = $folder->query()->getMessage($messageId);
    $results = $message->thread();
}
```
or..:

```php
$folder = $this->client->getFolderByName($folderName);
if ( $folder != null) {
    $message = $folder->query()->getMessage($messageId);
    $results = $message->thread();
}
```

Best regards,

**Comment by tkowalski29** [comment]
![image](https://user-images.githubusercontent.com/3847457/108242256-ff52c600-714c-11eb-84ba-9d9ae512b71c.png)

Thx @Webklex, but look on the screen. Is stopped inside if no outside. 
folder and message definitely exist

**Comment by tkowalski29** [comment]
in my opinion primary_folder in fetchThreadByInReplyTo is null and query returns exception. But I don't know how to fix it, without more action analysis

**Comment by tkowalski29** [comment]
I found a solution. I set up my 'common_folders' and the error stopped. Maybe it's worth paying attention to in the documentation?

```
'common_folders' => [
                    'root' => 'INBOX',
                    'junk' => 'INBOX.Spam',
                    'drafts' => 'INBOX.Drafts',
                    'sent' => 'INBOX.Sent',
                    'trash' => 'INBOX.Trash',
                ]
```

THX @Webklex
