### ISSUE TITLE
Missing email bodies (v2), with example to reproduce

### ISSUE THREAD

**Issue by peanut24** [Webklex/php-imap#111]
Hi @Webklex 

webklex/laravel-imap version 2.4
webklex/php-imap version 2.5

I'm still trying to get this v2 to prod, was doing some final tests and then ran into a situation where the email bodies were not identified by v2.

After a bit of "what the hell is happening", I realised that it was only for emails sent from Spark (https://sparkmailapp.com), and only on v2, for v1 the body was identified and could be retrieved. 

The email in question displays properly in gmail, as well as when using v1 to retrieve it, it seems to only be on v2. I was able to reproduce this with the below email (Had to change extension from .eml to .txt as GitHub doesn't allow uploading .eml)

[dump3.txt](https://github.com/Webklex/php-imap/files/6034057/dump3.txt)

When running

```php
  $messages = $inbox->query()
            ->whereSubject("a normal email, nothing fancy here")
            ->setFetchBody(true)
            ->since(now()->subDay())
            ->limit(1)
            ->get();
```

I get the following:

* First dump is the subject line
* Second dump is the result of `$message->getHTMLBody()` - which is null
* Third dump is the actual message just getting dumped. You can see there only one key text which is just an empty string

![image](https://user-images.githubusercontent.com/5346088/108962787-ee8cdd80-7681-11eb-8de6-00950f1c7de8.png)

In gmail, the email appears as:

![image](https://user-images.githubusercontent.com/5346088/108962989-31e74c00-7682-11eb-8fc5-e887dc317d13.png)

Could you please see if you can reproduce this with the provided example?

Thanks

**Comment by peanut24** [comment]
@Webklex were you able to reproduce this one?

**Comment by JuanAdamuz** [comment]
Im having the same issue, but not with all accounts.

I can see HTML body in webmail and outlook but not in php-imap library...

@Webklex

**Comment by afrazahmmad** [comment]
I am also facing same (empty body) issue while using sparkmail

**Comment by Webklex** [comment]
Hi @peanut24 @afrazahmmad  ,
please give [v3.0.0-alpha](https://github.com/Webklex/php-imap/releases/tag/3.0.0-alpha) a try. The default boundary regex used to detect the message parts in a multi-part message has been changed and can now also be modified via the config `options.boundary` parameter inside your configuration.

Best regards,
