### ISSUE TITLE
Error when I want to display messages from 1 month ago

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#112]
I am testing the searches, the problem is that when I want to bring messages from 1 month ago I get this error in both GMAIL and OUTLOOK.

![image](https://user-images.githubusercontent.com/33232796/109214040-1a968480-7790-11eb-9f4f-281354763ea5.png)

```
                $cm = new ClientManager([
                    'options' => [
                        'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                        'fetch_order' => 'desc',
                        'sequence' => \Webklex\PHPIMAP\IMAP::ST_UID,
                    ],
                ]);

                $client = $cm->make([
                    'host'          => $email->server,
                    'port'          => $email->port,
                    'protocol'      => $email->server_type,
                    'encryption'    => $email->encryption,
                    'validate_cert' => true,
                    'username'      => $email->email,
                    'password'      => $email->password,
                ]);

echo ($client->connect() ? "\n I connect ".$email->email ." the day " . Carbon::now() ."\n" : die("Error connecting to $email->server"));

 $folder = $client->getFolder($email->folder);

if ($email->lastId == 0 || $email->lastId == null || $email->start_date == '' || $email->start_date == null) {           
    $messages = $folder->query()->since(Carbon::now()->subDays(30)->format('d-m-Y'))->setFetchOrder("asc")->get();

}elseif (!empty($email->start_date) && $email->lastId == null) {       
    $messages = $folder->query()->since($email->start_date)->setFetchOrder("asc")->get();
}
```

**Comment by Webklex** [comment]
Hi @alexv96 ,
thanks for your report.

It looks like the mail provider is closing the connection. 
Please try to limit the amount of messages you are fetching.

Best regards,

**Comment by alexv96** [comment]
There is the problem that I need to capture all the emails from 1 month ago since it is running the console not the web view. 

Someone when I search by date tells me that I should limit the number of messages so that it works well and does not crash.

**Comment by Webklex** [comment]
.. you could also try to "chunk" the result:
```php
/** @var \Webklex\PHPIMAP\Query\WhereQuery $query */
$query->all()->chunked(function($messages, $chunk){
    /** @var \Webklex\PHPIMAP\Support\MessageCollection $messages */
    dump("chunk #$chunk");
    $messages->each(function($message){
        /** @var \Webklex\PHPIMAP\Message $message */
        dump($message->uid);
    });
}, $chunk_size = 10, $start_chunk = 1);
```

Ref.: https://www.php-imap.com/api/query

Best regards,

**Comment by alexv96** [comment]
If it works now, I didn't know how to use this long function, I didn't understand it at all in the documentation.

Another question for UID you could also use a structure like this? because for Outlook I had to make a function external to the library that consisted of:

1. extract the most recent message and get its UID.
2. save in a variable.
3. To make a for where I started with the UID that I had registered in the DB and that was inferior or equal to the most recent UID and to go incrementing in 6.
4. to later execute the query()->getMessageByUid($uidProcess);
