### ISSUE TITLE
Email HTML body does not appear when email has been moved in Outlook

### ISSUE THREAD

**Issue by JuanAdamuz** [Webklex/php-imap#117]
**Describe the bug**
I've tested several ways to have outlook move my emails upon receiving so ESET antivirus can analyze them before i show them in Web.

When I receive an email to INBOX folder, the method "getHTMLBody" gets the correct data.
If I set a rule to move all incoming mails to another folder in outlook, the method "getHTMLBody" in all emails of the new folder is "null".
If I set the same rule on RoundCube website, the method "getHTMLBody" gets the correct data.

So the problem seems to be with Outlook rules and moving emails manually... but... What is the solution? The structure in php seems correct.

![MYOc6I8Z08](https://user-images.githubusercontent.com/9932083/112027083-24b16600-8b37-11eb-91ab-fc342729529c.png)

**Code to Reproduce**
The troubling code section which produces the reported bug.
```php
 $client = Client::account('mail');

$client->connect();

$folder = $client->getFolder("INBOX_REDIRECTED");

$message = $folder->query()->setFetchBody(true)->getMessageByUid(1);

$body = $message->getHTMLBody();
```

**Expected behavior**
The variable "$body" contains valid html data and if I move mail in outlook, variable is null (Only text body is available).

**Desktop / Server (please complete the following information):**
- OS: Windows 10 (testing)
- PHP: [7.4]
- Version [v2.5.0]

**Comment by MouMoutMan** [comment]
Are you using the Outlook software installed in your computer?
If so, there is a synchronization time between the modifications on the heavy client installed on the computer, and the Outlook server.
I had this problem.
To find the message in a moved folder, I had to synchronize my folders: send / receive button.
