### ISSUE TITLE
Inline images in HTML body not displaying

### ISSUE THREAD

**Issue by b4tch** [Webklex/php-imap#118]
Firstly, thanks for the excellent library :)

Please can you explain how to get the base64-encoded inline images within the src attribute of img tags when using getHTMLBody()?

I see they are returned through getAttachments(), so do I need to write some code to inject them into the HTML body?

**Comment by zssarkany** [comment]
It is the standard behavior, that inline images are transferred in the MIME message nearly the same, as attached images. The only difference is the Content-Disposition header value. Inline images also have a Content-Id header, which is then used as reference in the HTML body.

For example:
- Content-Id: xyz
- `<img src="cid:xyz">`

You have two choices:
- replace src value to a script url (`attachment.php?muid=1&aidx=2`) containing message id / uid and attachment index / Content-Id value, therefore you can fetch that attachment in the php script with proper headers (obviously this will result inline images count + 1 request for your server)
- fetch attachment body for inline images as well with the HTML body, and replace img src value to data url [https://tools.ietf.org/html/rfc2397](https://tools.ietf.org/html/rfc2397) (this solution will result single HTTP request, but sum response size will be greater with nearly 33% of binary data and you won't have file names for images)

**Comment by stanolacko** [comment]
As standard problem with IMAP is, that uses index depend on current situation on server and this index number is not unique. So first sollution to use message index and attachment index can be problematic, because it can be changed between load message body and loading attachments. This is very small chance, but still exists.
