### ISSUE TITLE
Breaking changes should not be introduced in minor releases

### ISSUE THREAD

**Issue by itkfm** [Webklex/php-imap#120]
**Describe the bug**
Breaking changes like 86f28b6f3fa28a4c4144c16c1d25f2926415741d should not occur in minor releases.
This breaks code without any notice!

In case one would release a new major version (as required semantic versioning), there wouldn’t be any problem.
Composer won’t install an incompatible version, when you specify a suitable version selector (e.g. `^2.2` -> *any v2 that’s at least v2.2.0*)

**Code to Reproduce**
```json
"webklex/php-imap": "^2.2"
```
```
rm composer.lock
composer install
```
 -> boom!, here you go…

**Expected behavior**
Do not BREAK code in minor updates.

**Desktop / Server (please complete the following information):**
- OS: any
- PHP: any
- Version `^2.2`

**Additional context**
https://semver.org/

**Comment by Webklex** [comment]
Hi @itkfm ,
thanks for your report.

It looks like you've expected semantic versioning. This project however does not follow it. If you want to make sure that you are always using the same version, just go ahead and add the full version string e.g. 2.2.0 inside your composer.json.

Breaking changes are always listed inside the changelog as well as inside every release. If something breaks which I did not expected to break - well that can happen. Overall this is just a side project and no one here is getting paid for it - we all just do it for the fun of it :)

Best regards,

**Comment by itkfm** [comment]
well, composer would have handled this for free with semantic versioning… just sayin’, thank you anyway
