### ISSUE TITLE
Problem parsing of Boundary

### ISSUE THREAD

**Issue by mikolamin** [Webklex/php-imap#121]
I have getting emails with header like this:

_...
Content-type: multipart/mixed; 
	Boundary="0__=4E55...._

And method find() of class Header cannot find preg_match_all() with $pattern "/boundary=\"?([^\"]*)\"?/" because B letter is in upper case.

Could you help me to find the solution? It will be better to set these boundary pattern

**Comment by MouMoutMan** [comment]
Using find function ?
$boundary = $header->find("/Boundary=\"?([^\"]*)[\";\s]/");
https://www.php-imap.com/api/header

I also have a problem with the pattern in the Header class...

**Comment by Webklex** [comment]
Hi @mikolamin ,
thanks for your report! :)

Best regards,
