### ISSUE TITLE
Obvious bug in LegacyProtocol::headers method

### ISSUE THREAD

**Issue by zssarkany** [Webklex/php-imap#125]
**Describe the bug**

Uid function argument (sequence type) of [header](https://github.com/Webklex/php-imap/blob/2.5.0/src/Connection/Protocols/LegacyProtocol.php#L223) method gets overwritten by foreach. This results, that UID-based sequence is used for messageId-based header enumeration as well.

Problematic block:
```php
    public function headers($uids, $rfc = "RFC822", $uid = false){
        $result = [];
        $uids = is_array($uids) ? $uids : [$uids];
        foreach ($uids as $uid) {
            $result[$uid] = \imap_fetchheader($this->stream, $uid, $uid ? IMAP::FT_UID : IMAP::NIL);
        }
        return $result;
    }
```

Possible solution changing variable name from uid to id in foreach:
```php
    public function headers($uids, $rfc = "RFC822", $uid = false){
        $result = [];
        $uids = is_array($uids) ? $uids : [$uids];
        foreach ($uids as $id) {
            $result[$id] = \imap_fetchheader($this->stream, $id, $uid ? IMAP::FT_UID : IMAP::NIL);
        }
        return $result;
    }
```

**Used config**

*irrelevant*

**Code to Reproduce**

*irrelevant*

**Expected behavior**

Foreach should not overwrite $uid function argument.

**Screenshots**

*n/a*

**Desktop / Server (please complete the following information):**

*irrelevant*

**Additional context**

*n/a*

**Comment by zssarkany** [comment]
The same issue exists for [content](https://github.com/Webklex/php-imap/blob/2.5.0/src/Connection/Protocols/LegacyProtocol.php#L209) and [flags](https://github.com/Webklex/php-imap/blob/2.5.0/src/Connection/Protocols/LegacyProtocol.php#L242) methods.

**Comment by Webklex** [comment]
Hi @zssarkany ,
many thanks for your report! :)

Best regards,
