### ISSUE TITLE
Error regex to getBoundary() passing by getAttachment()

### ISSUE THREAD

**Issue by MouMoutMan** [Webklex/php-imap#126]
**Describe the bug**
The getAttachment function cannot find the attachment because the returned boundary is not properly parsed.
Only using the getAttachment () function.
In the mail header, when there is a string after the boundary, the regex also takes that string. This creates a bad boundary, and the attachment is not found.

**Code to Reproduce**
The following code returns:
"----=EDF_mixed"; charset="ISO-8859-1"
and after clearBoundaryString, this code return the bad boundary: 
----=EDF_mixed charset=ISO-8859-1
```
<?php
$part_of_header = 'Content-Type: multipart/mixed; boundary="----=EDF_mixed"; charset="ISO-8859-1"';

// Header.php, function getBoundary() - l.176
$actual_pattern = "/boundary\=(.*)/i"; 

// Header.php, function find() - l.159
 if (preg_match_all($actual_pattern, $part_of_header, $matches)) {
            if (isset($matches[1])) {
                if(count($matches[1]) > 0) {
                    var_dump( $matches[1][0]);
                }
            }
        }
```

The following code returns:
"----=EDF_mixed"
and after clearBoundaryString, this code return the good boundary: 
----=EDF_mixed
```
<?php
$part_of_header = 'Content-Type: multipart/mixed; boundary="----=EDF_mixed"; charset="ISO-8859-1"';

// Header.php, l.176
$actual_pattern = "/boundary=\"?([^\"]*)[\";\s]/i"; 

 if (preg_match_all($actual_pattern, $part_of_header, $matches)) {
            if (isset($matches[1])) {
                if(count($matches[1]) > 0) {
                    var_dump( $matches[1][0]);
                }
            }
        }
```
**Expected behavior**
Change the regex to:
`/boundary=\"?([^\"]*)[\";\s]/i`
like the example in the documentation:
https://www.php-imap.com/api/header

**Desktop / Server (please complete the following information):**
- OS: Ubuntu
- PHP: 7.4.13
- Version: v2.4.0

**Comment by MouMoutMan** [comment]
This issues would solve #121

**Comment by MouMoutMan** [comment]
#27  is managed with this code ;)

**Comment by MouMoutMan** [comment]
After many tries, the problem is not just with the regex, because the current one (/boundary\=(.*)/i) covers a larger amount of mails.
However, I have several problems because of her.
It gets the semicolon and the function clearBoundaryString() therefore transforms the boundary.

**Here is my suggestion:**
Since RFC2046 (on page 22) does not allow the semicolon in the boundary, you might as well remove anything after the semicolon, if there is one:

```
    private function clearBoundaryString($str) {
        $pos = strpos($str, ';');
        if($pos) {
            $str = (strstr($str, ';', true));
        }
        return str_replace(['"', '\r', '\n', "\n", "\r", ";", "\s"], "", $str);
    }
```

**Comment by Webklex** [comment]
Hi @MouMoutMan ,
many thanks for your report and your time spent looking into this issue. I've had so many problems with this little regex, I'm really afraid to touch it...

RFCs are nice and all, but unfortunately almost no mail client follows it 100% - so in the end its all over the place..

I'm not sure how to handle this issue. Any additional comments or ideas are welcome :)

Best regards,

**Comment by Webklex** [comment]
Hi @MouMoutMan  ,
please give [v3.0.0-alpha](https://github.com/Webklex/php-imap/releases/tag/3.0.0-alpha) a try. The default boundary regex used to detect the message parts in a multi-part message has been changed and can now also be modified via the config `options.boundary` parameter inside your configuration.

Best regards,
