### ISSUE TITLE
How to install php-imap without composer and without Laravel?

### ISSUE THREAD

**Issue by bjaverhagen** [Webklex/php-imap#128]
Hi,

How can I install this php-imap class without the use of composer? I tried the following:
1. Download all files.
2. Require all files in to my script

I get errors when the files uses "Illuminate\..". Those classes are not found. Can I use this php-imap class without installing Laravel?

**Comment by Webklex** [comment]
Hi @bjaverhagen ,
if you don't have composer installed or available on the production server, you would have to sync the vendors folder from your dev or local environment. 

You'll need all dependencies to use this library.

Best regards,
