### ISSUE TITLE
fetch_order => 'desc' not working

### ISSUE THREAD

**Issue by yadavsingh** [Webklex/php-imap#129]
$aMessage = $oFolder->query()->since(now()->subDays(3))->get(); // used this

fetch_order => 'desc' //used this on config/imap.php but not working?
is there any way to get mail with desired order?

**Comment by MouMoutMan** [comment]
try:
`$aMessage = $oFolder->query()->since(now()->subDays(3))->setFetchOrder("desc")->get(); // used this
`

**Comment by yadavsingh** [comment]
Thank you for your message but this does not work.

**Comment by MouMoutMan** [comment]
However, it works well for me... Look documentation : [https://www.php-imap.com/api/query](https://www.php-imap.com/api/query) .
Check that `$aMessage = $oFolder->query()->since(now()->subDays(3))->get(); // used this` is returning the list of your messages to you.
Otherwise I don't see ...

**Comment by yadavsingh** [comment]
Thanks for reply.

I've seen and used as per documentation:

**This is my controller:**

use Webklex\IMAP\Facades\Client;
public function index(){
      $oClient = Client::account('default');
      $oClient->connect('default');
      $aFolder = $oClient->getFolders('INBOX.read');
      return view('backend.emails.index',compact('aFolder'));
    }


**This is my Blade:**

@foreach($aFolder as $oFolder)
                              @php $aMessage = $oFolder->query()->since(now()->subDays(1))->setFetchOrder("desc")->get();@endphp
                              @foreach($aMessage as $message)
                                <li class="media">
                                    <div class="media-left pr-50">
                                        <div class="avatar">
                                            <img src="{{ asset('images/face.jpg') }}" alt="" />
                                        </div>
                                        <div class="user-action">
                                            <div class="custom-control custom-checkbox">
                                                <input type="checkbox" class="custom-control-input" id="customCheck2{{$message->getUid()}}" value="{{$message->getUid()}}" />
                                                <label class="custom-control-label" for="customCheck2{{$message->getUid()}}"></label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="media-body">
                                        <div class="mail-details">
                                            <div class="mail-items">
                                                <h5 class="mb-25">{{$message->getFrom()[0]->mail}}</h5>
                                                <span class="text-truncate">{{$message->getSubject()}}</span>
                                            </div>
                                            <div class="mail-meta-item">
                                                <span class="mail-date">{{$message->getDate()}}</span>
                                            </div>
                                        </div>
                                        <div class="mail-message">
                                            <p class="mb-0 text-truncate">
                                                {{$message->getTextBody()}}
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                @endforeach
                                @endforeach

**Mail appear well but not as per order. If anything you found wrong let me know... **

**Comment by MariaLuize** [comment]
I'm facing the same problem, however I want to get emails from a specific sender, in descending order.

My currently structure is: 
`$messages = $query->from('sender@email.com')->setFetchOrder("desc")->get();`
With all the config/imap.php files seted as  `'fetch_order' => 'desc', `

![image](https://user-images.githubusercontent.com/28123958/139497678-fbbadbfc-ac2a-48e6-b322-505b203d3679.png)

**Comment by stefanofinetti** [comment]
I'm facing the exact same issue.
imap.php is set to desc
i get messages with:

$messaggi = $inbox->messages()->all()->setFetchOrder("desc")->setFetchBody(false)->paginate($per_page = 30, $page = $request->page, $page_name = 'page');

mails are sorted correctly by date (day of the month), but the time of the email is still sorted ascending.

So, basically, I have 9 december shown before 8, as it should, but all emails from 9 december are sorted oldest to newest. There is no way, apparently, to show the most recent email at the top of a datatable.

**Comment by FR31NDSDEV** [comment]
Is there any update on this?
I tried : 

$inboxFolder->query()
->setFetchOrder("desc");
->setFetchOrderDesc);
->fetchOrderDesc();

I also tried changing it from imap.php in both folders ( laravel-imap / php-imap ).

However nothing worked, it had no effect and the order is always from old email to new email, meaning the oldest is shown at the top or has the first index.

**Comment by Gunasekar-Skyraan** [comment]
**// Get the messages in the inbox**

$messages = $folder->messages()->all();

**// Paginate the messages in descending order and retrieve 5 items per page**

$messages = $messages->setFetchOrder("desc")->paginate(5);

**// Reverse the order of the paginated results without creating a new instance**

$messages->setCollection(collect(array_reverse($messages->items())));

**to imap.php**

'fetch_order' => 'desc',

**Comment by haiderpro** [comment]
It looks like a bug still exist. I am using version 2.4.1 due to not able to use PHP 8 on my project and sorting DESC was not working not matter what I tried. So finally I adopted a workaround:

 Use `$query->reverse();` // or put ->reverse(); at the end of your request to reverse the order of the fetched messages.

Hope this helps someone :-)
