### ISSUE TITLE
paginate() returns array of "true"

### ISSUE THREAD

**Issue by Max13** [Webklex/php-imap#13]
I don't know if I'm not using it properly, but when I use `paginate()` the items are just arrays of `true`, while with `limit()` I get the messages.

Here is how I use it:
```php
$imap = new Imap(array_merge(
    $attributes,
    [
        'password' => decrypt($this->attributes['password']),
    ],
    [
        'masks' => [
            'attachment' => \Webklex\PHPIMAP\Support\Masks\AttachmentMask::class,
            'message' => \Webklex\PHPIMAP\Support\Masks\MessageMask::class,
        ],
    ],
));
$imap->connect();

$folders = $imap->getFolders(); // Returns a correct list
$pages = $imap->getFolderByPath('folder')->messages()->all()->paginate();
$limited = $imap->getFolderByPath('folder')->messages()->all()->limit(5)->get();
```

So, `$pages` contains 5 items which are all the value `true`. `$limited` on the other hand, contains 5 `Message` instances which are correct.

Am I missing something?

**Comment by hadesflames** [comment]
This fix doesn't work. Returns empty after going past first page because the array is being sliced twice at the offset.

**Comment by Max13** [comment]
@hadesflames Hi thanks for your feedback. If you have a patch, feel free to submit it. I will only be able to look at it in few days

**Comment by hadesflames** [comment]
I haven't looked too much into it but you can probably just get rid of the second paginate call to fix it.
