### ISSUE TITLE
vs code doesnt load images

### ISSUE THREAD

**Issue by fa1th01** [Webklex/php-imap#132]
Hello, guys I really want your help. I am a beginner at HTML/CSS and vs code doesn't load my images it says that an error while loading images. Help me please :(
![Capture](https://user-images.githubusercontent.com/79598433/115440131-745f7c00-a220-11eb-82c9-d411add70f67.PNG)

**Comment by Webklex** [comment]
Hi @fa1th01 ,
I think you are at the wrong place :)

Please check out stackoverflow or their github page for more information:
- https://stackoverflow.com/questions/62585607/how-to-use-image-in-visual-code-its-not-working
- https://github.com/microsoft/vscode/issues/83165

Best regards,
