### ISSUE TITLE
enableDebug() to check connect()

### ISSUE THREAD

**Issue by stanolacko** [Webklex/php-imap#134]
It is not possible to enable Debug mode when connect().

$client->getConnection()->enableDebug(); is possible to set only after proper connection is established.

**Comment by Webklex** [comment]
Hi @stanolacko ,
many thanks for your question.
Currently there is no easy way to enable the debug mode before the connect() call. However if you do want to have it enabled, just open https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/Protocol.php#L32 and change it from `false` to `true`.

Bes regards,
