### ISSUE TITLE
Is it possible to use the overview method with chunked?

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#136]
I have this doubt because the chunked method is the only one that does not vote me the outlook connection, so I wanted to know if you could do something like that, or to search by mail and that the UID is greater than the uid that you register in the database?

**Comment by Webklex** [comment]
Hi @alexv96 ,
many thanks for your question.

Yes you can do this by calling `Query::fetchBody(false)` to prevent the query from fetching the message body. All you are left with are the message headers and flags - just like the overview method :)

Best regards,
