### ISSUE TITLE
PHP Notice:  Undefined variable: $error in Protocol.php on line 197

### ISSUE THREAD

**Issue by dartrax** [Webklex/php-imap#137]
PHP Notice:  Undefined variable in /Connection/Protocols/Protocol.php on line 197
The variable $error in the line `throw new ConnectionFailedException("Failed to connect to host", 0, $error);` was never defined.

The full stack trace, may be it reveals more bugs:
```
PHP Warning:  stream_socket_client(): unable to connect to ssl://xxx:993 (Network is unreachable) in xxx/imap_idle/Connection/Protocols/Protocol.php on line 192
PHP Warning:  stream_set_timeout() expects parameter 1 to be resource, bool given in xxx/imap_idle/Connection/Protocols/Protocol.php on line 194
PHP Notice:  Undefined variable: error in xxx/imap_idle/Connection/Protocols/Protocol.php on line 197
```

**Comment by Webklex** [comment]
Hi @dartrax ,
thanks for your report. Which PHP version are you using?

Best regards,

**Comment by dartrax** [comment]
Hi,
thanks for your reply. I use PHP v 7.4.20
