### ISSUE TITLE
Guaranteed: POP3 connection failed

### ISSUE THREAD

**Issue by xianzhe18** [Webklex/php-imap#139]
https://github.com/Webklex/php-imap/blob/e1296d18a01027b9d99728a2b3dee4e8b5b4d299/src/Connection/Protocols/LegacyProtocol.php#L82

According to [documentation](https://www.php.net/manual/en/function.imap-open.php), **/readonly: request read-only mailbox open (IMAP only; ignored on NNTP, and an error with SMTP and POP3)**. 
It is required to update to make sure POP3 works.

**Comment by Webklex** [comment]
Hi @xianzhe18 ,
many thanks for your report. I'm merging this issue with [#402](https://github.com/Webklex/laravel-imap/issues/402) .

Best regards,

**Comment by Beaudinn** [comment]
This issue still exist also in alpha 
`Unknown: Can't get status of mailbox {pop3.***.nl:995/pop3/novalidate-cert/ssl}INBOX: invalid remote specification (errflg=2)`

When changing the code like @ennnnny provided it works.
