### ISSUE TITLE
Mail content is parsed as file attachment

### ISSUE THREAD

**Issue by erkanarslan** [Webklex/php-imap#142]
**Describe the bug**
Email content from some senders are parsed as file attachment. In this case email body is empty and email has 2 file attachments with no name. One is for text body, another is for html body.

**Expected behavior**
Mail body should be parsed correctly.

**Screenshots**
Here is the data of the mail that causes this issue:
[mail-data.txt](https://github.com/Webklex/php-imap/files/6587885/mail-data.txt)

**Desktop / Server (please complete the following information):**
- OS: Ubuntu 19.04
- PHP: 7.3
- Version. Package version is 2.5.0

**Additional context**
Some emails are parsed correctly.

**Comment by Webklex** [comment]
Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
