### ISSUE TITLE
Not expected result of WhereQuery::whereInReplyTo method

### ISSUE THREAD

**Issue by alexelev** [Webklex/php-imap#144]
**Describe the bug**
I try to find inbox emails which are replies on my sent emails. So I sent email 
![Screenshot_220](https://user-images.githubusercontent.com/3392106/123517040-c81a9580-d6a7-11eb-86e9-b45f78acdd90.jpg)
 and receive a reply on it.
![Screenshot_221](https://user-images.githubusercontent.com/3392106/123517053-d799de80-d6a7-11eb-8182-0eded6d2578c.jpg)
In the replied email I have header attribute `in_reply_to` which shows me id of sent email. It equals the id of my sent email.
![Screenshot_222](https://user-images.githubusercontent.com/3392106/123517072-e8e2eb00-d6a7-11eb-8de6-3003d294f2c3.jpg)
But if I try to get messages with help of `whereInReplyTo` method - I'll have empty collection. 
![Screenshot_223](https://user-images.githubusercontent.com/3392106/123517086-f13b2600-d6a7-11eb-9283-0a2f20717343.jpg)
Am I do something wrong?

**Used config**
I've used a `default` account with my login data.
```conf
IMAP_HOST=imap.ukr.net
IMAP_PORT=993
IMAP_ENCRYPTION=ssl
IMAP_VALIDATE_CERT=true
IMAP_USERNAME={my_username}
IMAP_PASSWORD={my_password}
IMAP_DEFAULT_ACCOUNT=default
IMAP_PROTOCOL=imap
```

**Expected behavior**
I want to have ability to find replied emails to my messages.

**Desktop / Server (please complete the following information):**
- OS: Ubuntu 18.04 LTS
- PHP: 7.2.24
- Version: 2.4.0

**Comment by Webklex** [comment]
Hi @alexelev ,
many thanks for the detailed report.

The method `WhereQuery::whereInReplyTo()` depends on your email server. It can happend that the server doesn't support certain search criteria - but I've never heard of missing `In-Reply-To` support... You could try to enable the debug option `$client->getConnection()->enableDebug()` and see if you get any additional clues.

However maybe `Message::thread()` contains the message you are looking for :)

Best regards,

**Comment by alexelev** [comment]
Thanks for your answer

> but I've never heard of missing In-Reply-To support...

Yep, now you can say that you've read about that, because this is true and confirmed by the technical support staff of mail service which was used. In such situation, respectively, `Message::thread()` also doesn't work :) 
When i contacted them they advised me making request for all mails's headers, parse them on my side to find nessesary for me mails and then making request to get data only for this mails, by, for example, `Message-Id` header. So can I fetch custom set of headers - I think `Message-Id` and `In-Reply-To` would be enough for start - with this library help?

**Comment by Webklex** [comment]
Hi @alexelev ,
sorry for the late response. Yes you'll find all these values within the header of a message :)

I'm closing this issue, as this isn't library issue. If I'm wrong or you have any additional comments feel free to comment below or to create a new issue.

Best regards,
