### ISSUE TITLE
'Where' method replaces the content with uppercase

### ISSUE THREAD

**Issue by felipehertzer** [Webklex/php-imap#148]
I have a problem searching for a message using whereInReplyTo(). Currently php-imap is creating the query in the format "HEADER IN-REPLY-TO <CAHGEXCRJVSQN3EY....>" (All query in Uppercase) but the function return is empty.

After some tests I found that the server is case sensitive and that the validate_criteria function transforms the content of the where function into uppercase.

https://github.com/Webklex/php-imap/blob/5ca52ab98da97ba2e281e71f608805e73815086c/src/Query/WhereQuery.php#L108

After removing the line that adds the uppercase the query returns the expected message.
"HEADER In-Reply-To <CAHGeXCrjvsqn3ey...>"

Is there another method I can use without turning the content into uppercase?

The server tested was Gmail.

Thank you for this amazing project.

**Comment by Webklex** [comment]
Hi @felipehertzer  ,
many thanks for your report. Please give [v3.0.0-alpha](https://github.com/Webklex/php-imap/releases/tag/3.0.0-alpha) a try :)

Best regards,
