### ISSUE TITLE
Can't fetch some attachments

### ISSUE THREAD

**Issue by EthraZa** [Webklex/php-imap#150]
I'm unable to fetch attachment from some senders messages.

It's maybe related to #142 

An eml sample with this problem:
[CantGetAttachment.eml.txt](https://github.com/Webklex/php-imap/files/6970471/CantGetAttachment.eml.txt)

And here is the output of `var_dump($message->getAttachments())`:
[CantGetAttachment.log.txt](https://github.com/Webklex/php-imap/files/6970473/CantGetAttachment.log.txt)

As it can be seen on log at line 938, looks like it's getting the XML attachment and the body together:
```php
       ["structure":protected]=>
        object(Webklex\PHPIMAP\Structure)#255 (5) {
          ["raw"]=>
          string(13973) "----AaZz
Content-Type: text/plain; charset="UTF-8"
Content-Disposition: inline

Segue, em anexo, em caráter meramente comercial, o arquivo da nota fiscal eletrônica 2798556, de 11/08/2021 com chave de acesso 33210834274233009584550000027985561873768020.
Informamos que, independente deste envio, o arquivo da mesma ficará à disposição, para download, na aplicação Canal de Negócios do Portal BR, no endereço www.br.com.br.

----AaZz
Content-Type: application/xml; charset="UTF-8";
	name="NF-e_33210834274233009584550000027985561873768020.xml"
Content-Disposition: attachment;
	filename="NF-e_33210834274233009584550000027985561873768020.xml"
Content-Transfer-Encoding: base64

PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PG5m
ZVByb2MgeG1sbnM9Imh0dHA6Ly93d3cucG9ydGFsZmlzY2FsLmluZi5ici9uZmUiIHZlcnNhbz0i
...
```

Versions:
```yml
$ php -v
PHP 8.0.9 (cli) (built: Jul 31 2021 08:10:26) ( NTS )

$ grep -A1 php-imap composer.lock 
            "name": "webklex/php-imap",
            "version": "2.5.1",
```

There's something I can do to get it working right?
Or, could you please point me to the file or method that could be tweked?
(This code is in production and will explode on me soon!)

Thank you.

**Comment by EthraZa** [comment]
I have made a PR changing getBoundary function regex of 2.5.1 version (Header.php)
from
`"/boundary\=(.*)/i"`
to
`"/boundary=(.*?(?=;)|(.*))/i"`

but just found out that till version 2.4.3, is was (Structure.php)
`"?([^\"]*)[\";\s]/i"`
that seen to work as well.

**Please, someone who understand RegEx better, take a look at this changes.**

This is my poor's man test with parts from 2 e-mails headers:
```
<?php

#$p='/boundary\=(.*)/i'; # 2.5.1
##$p='/boundary=(.*?(?=;)|(.*))/i'; # PR #152 
$p="/boundary=\"?([^\"]*)[\";\s]/"; # 2.4.3

$s1='Organization: GHSix
Content-Type: multipart/mixed;
 boundary="=_34f19e771ef672441eab76cca3808103"

--=_34f19e771ef672441eab76cca3808103';

$s2='Message-ID: <OFC5EC803D.5298C025-ON0325872E.003DCA9D@br-petrobras.com.br>
Content-Type: multipart/mixed; boundary="--AaZz"; filename="untitled.txt"
Content-Disposition: nf-e_33210834274233009584550000027985561873768020.xml';


preg_match_all($p, $s1, $m1);
preg_match_all($p, $s2, $m2);

print_r([$m1, $m2]);
```

**Comment by EthraZa** [comment]
There is something wrong with my PR? I's almost 2 months pending aleready.

**Comment by Webklex** [comment]
Hi @EthraZa ,
I believe this issue is fixed. If I'm wrong please feel free to reopen this issue. Thanks again for your help and support!

Best regards,
