### ISSUE TITLE
How to watch changes in multiple folders for one account 

### ISSUE THREAD

**Issue by mq-lukasz** [Webklex/php-imap#167]
If I would like to observe the changes (new mails / moved mails) in the incoming, outgoing, spam, trash folders:
1) I need to run 4 separate idle processes on each folder?
2) do one process and somehow switch folders every few seconds and see if anything has changed?
3) do it another way like?

How to do it correctly with php-imap lib?

**Comment by Webklex** [comment]
Hi @mq-lukasz ,
this is a good question! I'm honestly not sure...

You could try to experiment with `Folder::subscribe()` -  perhaps this will bring up some interesting results :)

Best regards,
