### ISSUE TITLE
Having an empty email (mail without content) breaks query pagination retrieval

### ISSUE THREAD

**Issue by petarg** [Webklex/php-imap#169]
**Describe the bug**
I want to query an Inbox, but when some of the returned emails has no content the whole page retrieval breaks with a GetMessagesFailedException (with message "no content found"). Setting query->setFetchBody(false) does not seem to do anything in this case

**Expected behavior**
The page results should be returned and no error should be thrown.

**Comment by Webklex** [comment]
Hi @petarg ,
many thanks for your report. 

Best regards,
