### ISSUE TITLE
Webklex\PHPIMAP\Exceptions\GetMessagesFailedException  Invalid message date.

### ISSUE THREAD

**Issue by dannylifino** [Webklex/php-imap#173]
So currently I am having an issue with fetching emails from a mailbox due to an invalid message date of 1 mail. Although this is only 1 mail, this stops the entire mailbox from read out and I can't seem to find a solution for the issue.

The code, which seems like basic throws error:  Webklex\PHPIMAP\Exceptions\GetMessagesFailedException   Invalid message date. I have not changed the config regarding the date formats either.

`
$inboxMessages = $this->inboxFolder->messages()->all()->get();
$spamMessages = $this->spamFolder->messages()->all()->get();
`

Is there a way to get the fetch working with filtering out the invalid one?

**Comment by dannylifino** [comment]
@Webklex Is it also possible to solve this issue without editing the composer package?

**Comment by Webklex** [comment]
Hi @dannylifino ,
yes there is, if you use the current master. As you can see in https://github.com/Webklex/php-imap/commit/8cf23675169a22aa9eb7a6a3c15947b7f8d4cf76 the exception will now contain the troubling date :)

Best regards,

**Comment by Webklex** [comment]
Hi @dannylifino ,
please give [v3.0.0-alpha](https://github.com/Webklex/php-imap/releases/tag/3.0.0-alpha) a try :)

Best regards,

**Comment by mbol8309** [comment]
I'm having the same problem, debugging find out that date with format "2022.07.27-14.35.59" its not parseable. can you fix that @Webklex . thanks in advance
