### ISSUE TITLE
How to set the ID of the imap client for identification information ?

### ISSUE THREAD

**Issue by mtariqsajid** [Webklex/php-imap#174]
How to identify php imap client to gmail that i am currently reading the emails ? 

this RFC explain it  [IMAP4 ID extension](https://datatracker.ietf.org/doc/html/rfc2971  )

**Comment by Webklex** [comment]
Hi @Magiczne ,
many thanks for your suggestion. Please give [v3.0.0-alpha](https://github.com/Webklex/php-imap/releases/tag/3.0.0-alpha) a try :)

You can call the id command like this:
```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->connect();
$client->getConnection()->id(["name", "php-imap", "version", "3.0.0", "vendor", "webklex", "contact", "email@domain.tld"]);
```
..or:
```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->connect();
$client->Id(["name", "php-imap", "version", "3.0.0", "vendor", "webklex", "contact", "email@domain.tld"]);
```

Best regards,

**Comment by mtariqsajid** [comment]
@Webklex thanks I will try and let you know

**Comment by mtariqsajid** [comment]
yes its working 👍

**Comment by Webklex** [comment]
HI @mtariqsajid ,
thanks for testing. I may add that you can also call `id` without any parameters like this: `$id = $client->id()`.

Best regards,
