### ISSUE TITLE
Message from gmail with wrong UID

### ISSUE THREAD

**Issue by igmacedo** [Webklex/php-imap#176]
**Describe the bug**
Messages are loaded but cannot be searched individually, the problem is with the UID, although it is removed from the inbox, when searching the message it is not found and this is not related to the fact that the identifier is dynamic.
Messages with a low UID like 200 return the wrong content and messages with a high UID like 200,000, which is what I'm looking for, are not found, all the ids are wrong and that only happens with Gmail.

**Used config**
The default configuration is used, the only change was the sorting way going from ASC to DESC.

**Code to Reproduce**
Follow the procedure below

- Log into a gmail account and enable the less secure app option for IMAP login:
https://myaccount.google.com/lesssecureapps

- Configure the package with the account credentials as per documentation.

- Get the UID of a message:

```php
$account = \Webklex\IMAP\Facades\Client::account('default')->connect(); // view:  https://github.com/Webklex/laravel-imap/issues/419
$folder = $account->getFolders()->all()[0]; // Select inbox
$message = $folder->messages()->all()->setFetchBody(false)->limit(1)->get();  // Retrieve all messages and return only 1
foreach($message as $ms){
return $ms->getUID();
}
```
- Locate and display the respective message for the user to read:

```php
$uid = '200.000'; // dynamically using or equivalent: $_GET["name"]
$account = \Webklex\IMAP\Facades\Client::account('default')->connect(); // view:  https://github.com/Webklex/laravel-imap/issues/419
$folder = $account->getFolders()->all()[0]; // Select inbox
$message = $folder->query()->where('uid', $uid)->limit(1)->get(); // Find a message with the same UID
//print($message); //Throw an exception because the content is an array or object, use dd()
dd($message);
```

**Expected behavior**
The expected behavior is to provide a valid, localizable UID that can be used on the next screen to make the respective message available for reading.

**Screenshots**
![image](https://user-images.githubusercontent.com/93507106/139718189-e1659cb3-f4be-4599-8cef-1e8ef2f9e48a.png)

**Desktop / Server (please complete the following information):**
- OS: Linux CentOS 7
- PHP: 7.4
- Version 2.4.0

**Additional context**
Gmail documentation for UID message location: https://developers.google.com/gmail/imap/imap-extensions#access_to_the_gmail_unique_message_id_x-gm-msgid

**Comment by Webklex** [comment]
Hi @igmacedo ,
many thanks for posting it here. I'm currently playing around with it, with some success. Do you know if the `X-GM-MSGID` can be used as an UID alternative?

For example like this:
```
C: A003 X-GM-MSGID COPY 1278455344230334865 foo
S: A003 OK COPY completed
```
..instead of:
```
C: A003 COPY 2:4 foo
S: A003 OK COPY completed
```

This is my little test setup:
```php
$client = $cm->make([
    'host'  => 'imap.gmail.com',
    'port'  => 993,
    'encryption'    => 'ssl',
    'validate_cert' => true,
    'username' => 'username',
    'password' => 'password',
    'protocol' => 'imap',
]);
$client->connect();

$con = $client->getConnection();
$con->enableDebug();

var_dump($con->id(["name", "php-imap", "version", "3.0.0", "vendor", "company", "contact", "someone"]));

$folder = $client->getFolder("INBOX");
$client->openFolder($folder->path);
var_dump($con->fetch(["X-GM-MSGID"], 1));
```

Result:
```
>> TAG2 ID ("name" "php-imap" "version" "3.0.0" "vendor" "company" "contact" "someone")
<< ID ("name" "GImap" "vendor" "Google, Inc." "support-url" "https://support.google.com/mail" "version" "gmail_imap_211029.07_p0" "remote-host" "<MY_IP>")
<< OK Success

>> TAG3 LIST "" "*"
<< LIST (\HasNoChildren) "/" "INBOX"
<< LIST (\HasChildren \Noselect) "/" "[Gmail]"
<< LIST (\All \HasNoChildren) "/" "[Gmail]/Alle Nachrichten"
<< LIST (\Drafts \HasNoChildren) "/" "[Gmail]/Entw&APw-rfe"
<< LIST (\HasNoChildren \Sent) "/" "[Gmail]/Gesendet"
<< LIST (\Flagged \HasNoChildren) "/" "[Gmail]/Markiert"
<< LIST (\HasNoChildren \Trash) "/" "[Gmail]/Papierkorb"
<< LIST (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
<< LIST (\HasNoChildren \Important) "/" "[Gmail]/Wichtig"
<< OK Success

>> TAG4 SELECT "INBOX"
<< FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
<< OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
<< OK [UIDVALIDITY 1] UIDs valid.
<< 10 EXISTS
<< 0 RECENT
<< OK [UIDNEXT 11] Predicted next UID.
<< OK [HIGHESTMODSEQ 19015]
<< OK [READ-WRITE] INBOX selected. (Success)

>> TAG5 FETCH 1 (X-GM-MSGID)
<< 1 FETCH (X-GM-MSGID 1644288497719176764)
<< OK Success
```

Here is a custom search:
```php
$folder = $client->getFolder("INBOX");
$message = $folder->query()->where("CUSTOM X-GM-MSGID", "1644288497719176764")->limit(1)->get()->first();
$header = $message->header;
var_dump($message->uid, $header->get("x_google_id"), $header->get("message_id"));
```

Result:
```
>> TAG2 ID ("name" "php-imap" "version" "3.0.0" "vendor" "company" "contact" "someone")
<< ID ("name" "GImap" "vendor" "Google, Inc." "support-url" "https://support.google.com/mail" "version" "gmail_imap_211029.07_p0" "remote-host" "<MY_IP>")
<< OK Success

>> TAG3 LIST "" "*"
<< LIST (\HasNoChildren) "/" "INBOX"
<< LIST (\HasChildren \Noselect) "/" "[Gmail]"
<< LIST (\All \HasNoChildren) "/" "[Gmail]/Alle Nachrichten"
<< LIST (\Drafts \HasNoChildren) "/" "[Gmail]/Entw&APw-rfe"
<< LIST (\HasNoChildren \Sent) "/" "[Gmail]/Gesendet"
<< LIST (\Flagged \HasNoChildren) "/" "[Gmail]/Markiert"
<< LIST (\HasNoChildren \Trash) "/" "[Gmail]/Papierkorb"
<< LIST (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
<< LIST (\HasNoChildren \Important) "/" "[Gmail]/Wichtig"
<< OK Success

>> TAG4 SELECT "INBOX"
<< FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
<< OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
<< OK [UIDVALIDITY 1] UIDs valid.
<< 10 EXISTS
<< 0 RECENT
<< OK [UIDNEXT 11] Predicted next UID.
<< OK [HIGHESTMODSEQ 19015]
<< OK [READ-WRITE] INBOX selected. (Success)

>> TAG5 UID SEARCH X-GM-MSGID 1644288497719176764
<< SEARCH 1
<< OK SEARCH completed (Success)

>> TAG6 UID FETCH 1 (FLAGS)
<< 1 FETCH (UID 1 FLAGS ())
<< OK Success

>> TAG7 UID FETCH 1 (RFC822.HEADER)
<< 1 FETCH (UID 1 RFC822.HEADER {4833}
<< Delivered-To: my_email\r\n
<< Received: by <IP> with SMTP id c7csp5527971ltc; Tue, 10 Sep\r\n
<< ...
<< OK Success
```

As you can see in TAG7 im using the UID obtained from the search. The big question however is still the same - what else can you do with the `X-GM-MSGID`? If you have any ideas or thoughts, please feel free to share them with us :)

Best regards,

**Comment by Webklex** [comment]
Hi @igmacedo ,
I did some more messing around. Please give the current `master` a try;

```php
$client = $cm->make([
    'host'  => 'imap.gmail.com',
    'port'  => 993,
    'encryption'    => 'ssl',
    'validate_cert' => true,
    'username' => 'username',
    'password' => 'password',
    'protocol' => 'imap',
    "extensions" => ["X-GM-MSGID", "X-GM-THRID", "X-GM-LABELS"], // auto. fetch these extensions 
]);

$client->connect();
$con = $client->getConnection();
//$con->enableDebug();

$folder = $client->getFolder("INBOX");

// Handle custom gmail labels
$client->openFolder($folder->path);
$con->store(["foo"], $uid = 1, null, "+", false, IMAP::ST_UID, "X-GM-LABELS"); // add a label
$con->store(["foo"], $uid = 1, null, "-", false, IMAP::ST_UID, "X-GM-LABELS"); // remove a label

// Advanced querying - fetch additional information by providing a list of supported extensions
$message = $folder->query(["X-GM-MSGID", "X-GM-THRID", "X-GM-LABELS"])->all()->limit(1)->get()->first();
$header = $message->getHeader();

$uid = $message->uid;
$x_google_id = $header->get("x_google_id");
$message_id = $header->get("message_id");
// Access fetched extensions
$MSGID = $header->get("X-GM-MSGID");
$THRID = $header->get("X-GM-THRID");
$LABELS = $header->get("X-GM-LABELS");

// Custom queries
$message = $folder->query()->where("CUSTOM X-GM-MSGID", $MSGID)->get()->first();

$thread = $folder->query()->where("CUSTOM X-GM-THRID", $THRID)->get();

$messages = $folder->query()->where("CUSTOM X-GM-LABELS", "foo")->get();
```

Best regards,

**Comment by igmacedo** [comment]
Thanks for the answer.

I created a project from scratch to test your suggestions and discard any chance of conflict with other packages and I arrived with the result:

1) The first method didn't work.

2) The second of the extension works fine, finds the message with msgid, but not with UID...

Do you have any suggestions for identifying these Google servers? Gmail will need special handling and people may be using a Gsuite corporate account; in this case, the server will not be imap.gmail.com, but imap.mydomain.com, all other imap servers work fine with UID, the problem is specific with Google

The new extension will be welcome.

Best regards.

**Comment by Webklex** [comment]
Hi @igmacedo ,
I'm not sure what problem you are describing.
- Which "first method" do you mean?
- Which second extension works but is having problems with uids?
- Whats the value of `options.sequence` [config/imap.php#L145](https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L145)?
- What do you mean by "identifying these Google servers"?
- What do you mean by "Gmail will need special handling" - how does it needs to be handled?
- Are you using [v3.0.0-alpha](https://github.com/Webklex/php-imap/releases/tag/3.0.0-alpha)?

You don't have to use my settings, such as `imap.gmail.com` you can use whatever host, port, etc you want or need. You can however set defaults inside [config/imap.php#L49-L66](https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L49-L66).

If you want to fetch a single message by its UID you can also use this method:
```php
$message = $folder->query()->getMessageByUid($uid);
```

If you want to tell the server who you are, you can call the id command like this:
```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->connect();
$client->getConnection()->id(["name", "php-imap", "version", "3.0.0", "vendor", "webklex", "contact", "email@domain.tld"]);
```
..or:
```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->connect();
$client->Id(["name", "php-imap", "version", "3.0.0", "vendor", "webklex", "contact", "email@domain.tld"]);
```
..or request the id:
```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->connect();
$id = $client->Id();
```

Best regards,

**Comment by igmacedo** [comment]
To recap:
1) The first method I referred to was your first message and the second method was your second message.
2) Default settings are being used and the master version (3.0) has been installed as recommended.
3) This ` $message = $folder->query(["X-GM-MSGID", "X-GM-THRID", "X-GM-LABELS"])->all()->limit(100)->paginate();`  retrieves the X-GM-MSGID attribute correctly and this `$message = $folder->messages()->all()->where("CUSTOM X-GM-MSGID", $msgid)->get()->first();` allows to get the correct message through the code returned by X-GM-MSGID, in this particular the message location issue has been resolved.
4) When I said that Gmail needed special handling, I was talking about not working with getMessage(), messages should be searched by the code returned by the X-GM-MSGID attribute and not by the UID, see the difference between a Server's codes Normal IMAP and from a Gmail server:

**IMAP**

```
function namefunction($uid = 1){         
         $account = \Webklex\IMAP\Facades\Client::account('default');
         $folder = $account->getFolders()->all()[0]; // Select inbox
         $message = $folder->getMessage($uid);
         return $message->getTEXTbody();
}
```
**Gmail Server**
```
<?php

use Webklex\PHPIMAP\ClientManager;
use Webklex\PHPIMAP\IMAP;

function gmailfunction($msgid, $thrid){
     $cm = new ClientManager();		
     $client = $cm->make([
        'host'  => 'imap.gmail.com',
        'port'  => 993,
        'encryption'    => 'ssl',
        'validate_cert' => true,
        'username' => 'username',
        'password' => 'password',
        'protocol' => 'imap',
        "extensions" => ["X-GM-MSGID", "X-GM-THRID", "X-GM-LABELS"], // auto. fetch these extensions 
    ]);
    $client->connect();
    $con = $client->getConnection();
    $folder = $client->getFolder("INBOX");
    $client->openFolder($folder->path);
    $message = $folder->messages()->all()->where("CUSTOM X-GM-MSGID", $msgid)->get()->first();
    return $message->getTEXTbody();
}
```
In that sense, I need to know if it's a Google/Gmail server to switch between these two search methods:

 `Imap: $folder->getMessage($uid);`
 `Gmail: $folder->messages()->all()->where("CUSTOM X-GM-MSGID", $msgid)->get()->first();`

That's what I mean by "Identify Google Servers", the way to retrieve a specific message is different in Gmail.

**Comment by Webklex** [comment]
Hi @igmacedo ,
thanks a lot for the clarification. You can reliably identify gmail users by checking the capabilities:

```php
if(in_array("X-GM-EXT-1", $client->getConnection()->getCapabilities())) {
    // is Gmail
}else{
    // is something else
}
```

You can ignore the `$con` and `$client->openFolder($folder->path);`:
```php
function gmailfunction($msgid, $thrid){
     $cm = new ClientManager();		
     $client = $cm->make([
        'host'  => 'imap.gmail.com',
        'port'  => 993,
        'encryption'    => 'ssl',
        'validate_cert' => true,
        'username' => 'username',
        'password' => 'password',
        'protocol' => 'imap',
        "extensions" => ["X-GM-MSGID", "X-GM-THRID", "X-GM-LABELS"], // auto. fetch these extensions 
    ]);
    $client->connect();
    $folder = $client->getFolder("INBOX");
    $message = $folder->messages()->all()->where("CUSTOM X-GM-MSGID", $msgid)->get()->first();
    return $message->getTEXTbody();
}
```
The folder will be opened automatically as soon as you start to query any messages.

Best regards,

**Comment by igmacedo** [comment]
Thanks, this solves the problem.

**Comment by dpacmittal** [comment]
I am not able to get this working. I keep getting this error when I try to do `CUSTOM X-GM-MSGID` search. Using v5.5.
```
Webklex\PHPIMAP\Exceptions\ImapServerErrorException 

BAD
Could
not
parse
command
```
