### ISSUE TITLE
Different time zone of messages from one mail service

### ISSUE THREAD

**Issue by byhaskell** [Webklex/php-imap#183]
Hello. I receive messages of the same day, and the date of the message is in different time zones. Can you set the conversion globally?

**Code to Reproduce**
My code is big, I'll make a snippet to point exactly to the place where the problem is
```php
$getMessage = $folder->query()->since('29.11.2021');
foreach($getMessage as $mail){
   dump($mail->getDate()->toDate()->toDateTime()->getTimestamp());//here is the problem
}
```

**Expected behavior**
Time zone setting to which all dates will always be converted.

**Desktop / Server (please complete the following information):**
- OS: Windows 10
- PHP: 7.4.21
- Version: v2.7.2
- Provider: ukr.net

**Comment by Webklex** [comment]
Hi @byhaskell ,
thanks for the excellent question. I believe all unix timestamps are based on UTC - I've tested my hypothesis with this little sniped:
```php
use Carbon\Carbon;

$date = Carbon::now();
var_dump($date->timestamp, $date->format("d.m.Y H:i:s"), $date->getTimezone()->getName());

$date->setTimezone('America/Los_Angeles');
var_dump($date->timestamp, $date->format("d.m.Y H:i:s"), $date->getTimezone()->getName());
```
..which returns:
```
int(1638214225)
string(19) "29.11.2021 19:30:25"
string(3) "UTC"
int(1638214225)
string(19) "29.11.2021 11:30:25"
string(19) "America/Los_Angeles"
```
If you want to implement some custom magic, you could utilize a custom `MessageMask`:
```php
class CustomMessageMask extends \Webklex\PHPIMAP\Support\Masks\MessageMask {

    /**
     * New custom method which can be called through a mask
     * @return string
     */
    public function Date(){
        return $this->date->toDate()->setTimezone('America/Los_Angeles');
    }
}
```

```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->connect();
$client->setDefaultMessageMask(CustomMessageMask::class);

/** @var \Webklex\PHPIMAP\Folder $folder */
$folder = $client->getFolder("INBOX");

/** @var \Webklex\PHPIMAP\Folder $folder */
$folder->query()->all()->limit(1)->get()->each(function($message){
    /** @var \Webklex\PHPIMAP\Message $message */
    var_dump($message->mask()->Date()->format("Y-m-d H:i:s"));
});
```

Additional references:
- https://www.php-imap.com/api/mask
- https://www.php-imap.com/configuration/masks
- https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L219

Best regards,

**Comment by byhaskell** [comment]
@Webklex  Thank you, very cool approach to solving the problem, your solution clearly has a good future.
