### ISSUE TITLE
How can I set flag in appendMessage() options?

### ISSUE THREAD

**Issue by AnastasiaDolgopolova** [Webklex/php-imap#184]
how can I set flag in appendMessage() options?
```$folder-> appendMessage($message,$options, $date);```

**Comment by Webklex** [comment]
Hi @AnastasiaDolgopolova ,
that's a good question. I'm afraid its not possible - at least not until you have a UID or MsgNumber. You'll need either of those in order to attach or detach any flags.

Best regards,

**Comment by AnastasiaDolgopolova** [comment]
I just realized it! - an array is needed
```$folder-> appendMessage($message,['Draft'], $date);```
![image_2021-12-02_16-03-14](https://user-images.githubusercontent.com/47051058/144437250-eb725773-8c78-42c2-8f7b-7df3770a2bf7.png)
