### ISSUE TITLE
Fatal error on getting emails

### ISSUE THREAD

**Issue by PedroPMS** [Webklex/php-imap#186]
Hi, I'm facing some errors when trying to read some emails. A fatal error is always happening 

```
PHP Fatal error: Uncaught ErrorException: Unknown: Unexpected characters at end of address: ; email.test@host.com (errflg=3) in Unknown:0

Stack trace:
#0 [internal function]: Illuminate\Fundation\Bootstrap\HandlerExceptions->handlerError()
#1 {main}
	thrown in Unknown
Segmentation fault
```

laravel-imap: 2.4.0
php-imap: 2.5.1

**Comment by PedroPMS** [comment]
I figured out that the error occurs when I do `$message->getAttachments()`

**Comment by Webklex** [comment]
Hi @PedroPMS ,
many thanks for your report. This sounds indeed odd. Can you try to pinpoint it down a little bit further? The callstack is a bit short to tell what might have caused this.

Does it still occur if you update to the current alpha version v3.0.0-alpha?

Best regards,

**Comment by PedroPMS** [comment]
I figured out more things about it. The message "Unexpected characters at end of address: ; email.test@host.com (errflg=3)" is a Notice, but laravel try to handle in their own errors handler, and the segfault occurs there.

**Comment by hhniao** [comment]
@PedroPMS that mean "ignore it" is no any problem? i also met some problem.

**Comment by hhniao** [comment]
@PedroPMS do you know how to disable display this message?
