### ISSUE TITLE
Some inline attachments are not reachable with ->attachments()

### ISSUE THREAD

**Issue by MajkiSVK** [Webklex/php-imap#187]
**Describe the bug**
Some incoming emails have inline attachments, but I can not get them with ->attachments();
Idk if I am doing something wrong or it is a bug :D :)

**Code to Reproduce**
The troubling code section which produces the reported bug.
```
 try {
            $client = $this->ConnectToImapClient($model->email);

            $messages = $client->getFolderByPath('INBOX')->messages()->unseen()->get();
        } catch (\Throwable $throwable) {
            $this->loggingService->warningLog($throwable->getMessage(), $throwable->getFile(), $throwable->getLine());
        }

        if (!isset($messages[0])) {
            return null;
        }

        foreach ($messages as $message) {
dd($message, $message->attachments());
}

 private function ConnectToImapClient(string $mail): ?Client
    {
        $mailAccessToken = $this->oauth2Service->GetAccessToken($mail);

        $clientManager = new ClientManager();
        $client = $clientManager->make([
            'host' => 'outlook.office365.com',
            'port' => 993,
            'encryption' => 'ssl', // 'tls',
            'validate_cert' => true,
            'username' => $mail,
            'password' => $mailAccessToken,
            'protocol' => 'imap',
            'authentication' => 'oauth',
        ]);

        $client->connect();

        if ($client->isConnected()) {
            return $client;
        }

    }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/69322217/146020814-41152ee4-473b-4ee0-99b7-265464d4dded.png)
![image](https://user-images.githubusercontent.com/69322217/146020956-0778b4de-b0d6-4c56-a16f-e578b2d26f36.png)

**Desktop / Server (please complete the following information):**

- PHP: 7.4.19
- Version: 2.7.2
- Provider: Outlook

**Comment by eduardom456** [comment]
[https://github.com/Webklex/php-imap/issues/370](https://github.com/Webklex/php-imap/issues/370)

I believe we are having the same problem.

My temporary solution is reprocessing the same email 4, 5 times, and comparing the amount of attachments identified in each process.

Having identified greater recurrence, I consider the email as "read".

Example, 5 processes of the same email, number of attachments identified in each:

identified 10
identified 11
identified 11
identified 11
identified 10

Not guaranteed, but in theory processed all attachments.

**Comment by AdrianKuriata** [comment]
Check this PR and give a feedback if it solve your problem. https://github.com/Webklex/php-imap/pull/372

**Comment by Webklex** [comment]
Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
