### ISSUE TITLE
Parsing date with arabian symbols throw Webklex\PHPIMAP\Exceptions\GetMessagesFailedException Invalid message date 

### ISSUE THREAD

**Issue by shadow762** [Webklex/php-imap#189]
Hi!
I have one message with date which contains arabian symbols.
As far as I know Carbon can't parse this kind of date by default so first I get exception from Carbon

 `"Could not parse '��, 19 ��� 2018 16:20:35': DateTime::__construct(): Failed to parse time string (��, 19 ��� 2018 16:20:35) at position 0 (�): Unexpected character"`

and InvalidMessageDateException later.

This exception stops reading the mailbox  at all. 
Is there way to solve this issue? Perhaps not to set date at all in this case?

**Comment by Webklex** [comment]
Hi @shadow762 ,
many thanks for your report. Can you provide me with such an date?

Can you think of a way to parse those dates?

Best regards,

**Comment by Creatik** [comment]
> Hi @shadow762 , many thanks for your report. Can you provide me with such an date?
> 
> Can you think of a way to parse those dates?
> 
> Best regards,

Hi i have the same problem

<warning>PHP Warning:  DateTime::modify(): Failed to parse time string (Fri, 11 Feb 2022 16:03:10 +0300 (RUS03)) at position 36 (0): Unexpected character in /opt/www/img.voltag.ru/vendor/nesbot/carbon/src/Carbon/Traits/Modifiers.php on line 439</warning>

**Comment by Hanaver** [comment]
webklex\php-imap\src\Header.php

**Comment by Webklex** [comment]
Hi @Creatik @Hanaver ,
man those timestamps are getting weirder and weirder. Thanks for providing new specimens for our collection :)

Best regards & happy coding,
