### ISSUE TITLE
Incomplete subject

### ISSUE THREAD

**Issue by Stenfrank** [Webklex/php-imap#190]
**Describe the bug**
It does not return the full subject, subject:

- 800160124;TRANSPORTES ORO S.A.S;SETP990002156;01;TRANSPORTES ORO S.A.S

**Used config**
Default

**Code to Reproduce**
The troubling code section which produces the reported bug.
```php
dump($message->getSubject());

// Return:
Webklex\PHPIMAP\Attribute^ {#2254
  #name: "subject"
  #values: array:1 [
    0 => "800160124"
  ]
}
```

**Expected behavior**
The whole thing, with the all() function is the same

**Screenshots**

**Desktop / Server (please complete the following information):**
- OS: [e.g. Fedora 25]
- PHP: [e.g. 8.1.1]
- Version [e.g. v2.7.2]
- Provider [e.g. Dovecot 2.2.36.4]

**Additional context**
At the moment I get it in the following way:
```php
imap_utf8(imap_rfc822_parse_headers($message->getHeader()->raw)->subject)
```

I just upgraded from version 1.4.5 to version 2.7.2, thank you very much

**Comment by Webklex** [comment]
Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
