### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by giorg** [Webklex/php-imap#2]
Hi,

I tried installation with composer but I get this:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for webklex/php-imap ^0.0.3 -> satisfiable by webklex/php-imap[0.0.3].
    - Conclusion: remove nesbot/carbon 2.16.0
    - Conclusion: don't install nesbot/carbon 2.16.0
    - webklex/php-imap 0.0.3 requires nesbot/carbon ^1.33 -> satisfiable by nesbot/carbon[1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.37.0, 1.37.1, 1.38.0, 1.38.1, 1.38.2, 1.38.3, 1.38.4, 1.39.0].
    - Can only install one of: nesbot/carbon[1.33.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.34.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.34.1, 2.16.0].
    - Can only install one of: nesbot/carbon[1.34.2, 2.16.0].
    - Can only install one of: nesbot/carbon[1.34.3, 2.16.0].
    - Can only install one of: nesbot/carbon[1.34.4, 2.16.0].
    - Can only install one of: nesbot/carbon[1.35.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.35.1, 2.16.0].
    - Can only install one of: nesbot/carbon[1.36.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.36.1, 2.16.0].
    - Can only install one of: nesbot/carbon[1.36.2, 2.16.0].
    - Can only install one of: nesbot/carbon[1.37.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.37.1, 2.16.0].
    - Can only install one of: nesbot/carbon[1.38.0, 2.16.0].
    - Can only install one of: nesbot/carbon[1.38.1, 2.16.0].
    - Can only install one of: nesbot/carbon[1.38.2, 2.16.0].
    - Can only install one of: nesbot/carbon[1.38.3, 2.16.0].
    - Can only install one of: nesbot/carbon[1.38.4, 2.16.0].
    - Can only install one of: nesbot/carbon[1.39.0, 2.16.0].
    - Installation request for nesbot/carbon (locked at 2.16.0) -> satisfiable by nesbot/carbon[2.16.0].

how do I solve this?
Thanks a lot

**Comment by Webklex** [comment]
Hi @giorg ,
please update to the latest version :)
