### ISSUE TITLE
Base64 content of attachments are corrupted with diamond question marks

### ISSUE THREAD

**Issue by shahmirerror** [Webklex/php-imap#203]
**Describe the bug**
The email Attachments I fetch, the content of the attachments are corrupted and not recognized as a base64 string.

**Screenshot**
![Screenshot (7)](https://user-images.githubusercontent.com/66474122/155521627-a71b952e-1be3-43a7-ad84-c5766ecbc16d.png)

**Desktop / Server (please complete the following information):**
- OS: Windows 11
- PHP: 7.4.26
- Provider : Outlook

**Comment by HelloSebastian** [comment]
Hi @shahmirerror,

are you sure that the attachment is encoded as base64? Microsoft Outlook uses its own file format ([TNEF](https://en.wikipedia.org/wiki/Transport_Neutral_Encapsulation_Format)) for attachments. The attachments are then called winmail.dat.

**Comment by Webklex** [comment]
Hi @shahmirerror ,
unfortunately TNEF isn't currently supported. A feature request to support TNEF can be found here: #21 

Please take a look at the content-type. If it isn't some kind of TNEF, please share an anonymized version (remove all sensible data such as mail addresses, phone numbers, etc) if possible.

Best regards,
