### ISSUE TITLE
Which release to choose

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/php-imap#205]
Thanks for the library.

Can you give an advice on which [release](https://github.com/Webklex/php-imap/releases) is it better to choose at the moment for the production system.

Do 3.x.x-alpha releases contain some important bug-fixes which are present in 2.7.2?

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
this is an excellent question! I would personally recommend the latest alpha version - yes it is an alpha, but I haven't heard of any new problems from within it. However v3.1.1 (a regular release) will be released at the beginning of next week. 

Best regards,
