### ISSUE TITLE
[help] Multiple IMAP connections at the same time - RuntimeException

### ISSUE THREAD

**Issue by catabozan** [Webklex/php-imap#209]
I am trying to create a mailbox app. Where users input their IMAP credentials, and they can manage their emails.

My app must use the `$folder->idle()` function to  listen for incoming emails. To achieve this for all my users and without blocking the execution of the rest of the code (because of the `while(true)` in the `idle()` function), I replaced the `while(true)` with ReactPHP event-loop's `addPeriodicTimer()` function, so the code runs in the background.

If I don't call the custom `idle()` function, the error does not occur (there seems to be a problem with the use of ReactPHP).

Everything works fine with only one user, but when another user tries to connect to the IMAP server, the connection crashes with the error message: `Webklex\PHPIMAP\Exceptions\RuntimeException with message 'failed to read - connection closed?'`.

For each user, I create a different `ClientManager` like this:
```php
protected function createIMAPClient(): Client
    {
        $this->credentials->refresh();

        $clientManager = new IMAPClientManager([ ... ]);

        $client = $clientManager->make([ ... ]);

        $client->checkConnection(); // start the connection

        return $client;
    }
```

The error occurs if I create 2 users and I try to fetch the folders, like this:
```php
// create and connect() users with their IMAP credentials
$bob = createUserWithInbox();
$ted = createAnotherUserWithInbox();

$bob->IMAPClient->checkConnection();

$inbox = $bob->IMAPClient->connect()->getFolders()[0];    // code errors out here
```

As you can see, the error occurs even if I call the `checkConnection()` and `connect()` functions.

How can I keep multiple connection open at once? Have you encountered this before, or do you know what causes the `RuntimeException`?

Edit: the code is executed in PHPUnit tests. I am running this in a Laravel app.

I get this error after all the PHPUnit tests have run:
```
PHP Fatal error:  Uncaught TypeError: fgets(): Argument #1 ($stream) must be of type resource, 
null given in / ... /vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php:106

Script @php artisan test --coverage handling the test event returned with error code 255
```

**Comment by catabozan** [comment]
The problem seems to be the execution of async code (ReactPHP event-loop) inside the PHPUnit tests.

**Comment by HelloSebastian** [comment]
Did the error occur only during PHPUnit tests?

I had a problem with a nested timer using ReactPHP. The timer in a timer was never executed...
