### ISSUE TITLE
PHP 8.1. Compatibility

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/php-imap#212]
The package is not compatible with PHP 8.1 yet.  There were a lot of serious changes in PHP 8.1: https://php.watch/versions/8.1 (see Deprecations in the bottom).

We've started to make php-imap compatible with PHP 8.1 but stuck on the following error when fetching emails via oAuth:
```
ErrorException: Undefined array key 2 in /vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php:593
```

The patch with changes already made is attached. In order to see full error message we added `echo $e;` in Query.php on line 319.

[php81.zip](https://github.com/Webklex/php-imap/files/8212397/php81.zip)

**Comment by HelloSebastian** [comment]
Hi @freescout-helpdesk,

it would be great if the library becomes compatible with PHP 8.1. I'm currently using the library with 8.0 and haven't had any problems yet. Could you open a WIP PR for this, where you upload your changes?

Thanks for your work!

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
this library is designed to support as many php versions as possible. Starting with v5.5.9. I hope we haven't reached a point were its no longer possible to support all of them. If that's the case, we should discuss which php versions this lib should support :)

Please feel free to push a pr - we could also designate a special branch? 

Best regards and many thanks for your feedback.

**Comment by freescout-helpdesk** [comment]
For our helpdesk PHP 8.1 support is required as most new installations are made now on PHP 8.1 So without PHP 8.1 we can't use php-imap package.

**Comment by freescout-helpdesk** [comment]
PR created: https://github.com/Webklex/php-imap/pull/214

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
many thanks for your pull request. I've added some additional return and argument types and changed the php requirement to >=7.0.0. I've done some quick tests on php v7.0, 7.4 and 8.1. Seems to work fine :)

Best regards,

**Comment by freescout-helpdesk** [comment]
Thanks
