### ISSUE TITLE
TAG2 LOGOUT on Microsoft Exchange

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/php-imap#213]
When connecting via oAuth to Microsoft Exchange Server from time to time we get the following:
```
>> TAG1 AUTHENTICATE XOAUTH2 dXNlcj...
>> TAG2 LOGOUT
<< OK AUTHENTICATE completed.

<< BYE Microsoft Exchange Server IMAP4 server signing off.

<< OK LOGOUT completed.
```
When it happens it waits around 30 seconds on `TAG1 AUTHENTICATE XOAUTH2` command.
And after some time it's possible to connect again with the same Access Token...

It's strange that `TAG2 LOGOUT` is called before `OK AUTHENTICATE completed`

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
this looks like a timeout to me. The logout gets always called on __destruct. Given that the OK Auth came afterwards indicates that the call has been aborted before auth could return it's success.

Best regards,

**Comment by freescout-helpdesk** [comment]
Is it possible to set IMAP connection timeout?

**Comment by freescout-helpdesk** [comment]
Nevermind. Not a big problem.

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
just in case you are still wondering if it is possible; yes it is. At least if you aren't using the legacy mode.

```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->setTimeout(60);
$client->connect();
```
This would set the timeout to 60 seconds.

Best regards,
