### ISSUE TITLE
Takes too long while fetching messages

### ISSUE THREAD

**Issue by Albert-Alexander** [Webklex/php-imap#217]
This package is very slow. After connecting when I try to list messages it takes a lot of time (more then 1 minute) while there are only 5 messages in inbox. Also when I try try to get a particular message with uid same thing happens.

**Comment by HelloSebastian** [comment]
Hi @Albert-Alexander,

which version are you using?

**Comment by Albert-Alexander** [comment]
Hello @HelloSebastian. Thanks for replying. I am using versions 2.4.0

**Comment by alexv96** [comment]
@Albert-Alexander I have the same problem the library is very slow to search for messages and that paged and even if it is 5 days it takes a long time. 

Do you have or recommend another library or another way to do it?
