### ISSUE TITLE
IMAP UID Cache Error

### ISSUE THREAD

**Issue by ellisonpatterson** [Webklex/php-imap#218]
**Describe the bug**
When I disable uid_cache it is causing this error to occur:
```
PHP Fatal error:  Uncaught Webklex\PHPIMAP\Exceptions\MessageNotFoundException: unique id not found in /home/frank/cliapps/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php:711
Stack trace:
#0 /home/frank/cliapps/vendor/webklex/php-imap/src/Message.php(1386): Webklex\PHPIMAP\Connection\Protocols\ImapProtocol->getUid()
#1 /home/frank/cliapps/vendor/webklex/php-imap/src/Message.php(1422): Webklex\PHPIMAP\Message->setMsgn()
#2 /home/frank/cliapps/vendor/webklex/php-imap/src/Message.php(211): Webklex\PHPIMAP\Message->setSequenceId()
#3 /home/frank/cliapps/vendor/webklex/php-imap/src/Query/Query.php(447): Webklex\PHPIMAP\Message->__construct()
#4 /home/frank/cliapps/vendor/webklex/php-imap/src/Query/Query.php(466): Webklex\PHPIMAP\Query\Query->getMessage()
#5 /home/frank/cliapps/vendor/webklex/php-imap/src/Folder.php(384): Webklex\PHPIMAP\Query\Query->getMessageByMsgn()
#6 /home/frank/cliapps/src/Email/EmailClient.php(37): Webklex\PHPIMAP\Folder->idle()
#7 /home/frank/cliapps/src/Email/EmailListener.php(53): App\Email\EmailClient->listen()
#8 {main}
```

**Used config**
```
            'options' => [
                'uid_cache' => false,
                'fetch_body' => false
            ]
```

**Code to Reproduce**
I am just processing messages in an idle() loop.

**Additional context**
I originally disabled the uid_cache since I was getting some type of memory limit exceeded message (there are tens of thousands of messages in the email I'm testing with).

**Comment by HelloSebastian** [comment]
Hi @ellisonpatterson,

thanks for your detailed error messages!

The error probably comes from the fact that when a new email is sent, the cache is not refreshed or the new email is not added to the cache.

Does the error come directly with the first new message?

**Comment by ellisonpatterson** [comment]
This problem is related to my other issue #219 where `setUidCache` is adjusting the array keys for all the UIDs and if uid caching is disabled, that array adjustment never happens, causing this error.

**Comment by HelloSebastian** [comment]
Ah, okay now I get it! Thank you!

Does it make sense to set the `uid_cache` not null by default and initialize it directly in the constructor?

**Comment by ellisonpatterson** [comment]
I don't believe it would solve the issue. The problem is that in the `getUid` method, the variable `$uids` is not the same when `uid_cache` is disabled.

https://github.com/Webklex/php-imap/blob/6e76b3552491e437f37721ae113129682489c141/src/Connection/Protocols/ImapProtocol.php#L688-L694

When `uid_cache` is enabled:
`$uids = $this->uid_cache;`
Which had its' keys bumped up by 1.
When `uid_cache` is disabled:
`$uids = $this->fetch('UID', 1, INF);`
It doesn't have its' keys bumped and that's why the error occurs.

**Comment by HelloSebastian** [comment]
Hey @ellisonpatterson,

can you test my PR #221? I tried to fix the issue with your information.

**Comment by ellisonpatterson** [comment]
> Hey @ellisonpatterson,
> 
> can you test my PR #221? I tried to fix the issue with your information.

That resolved the issue, thank you!
