### ISSUE TITLE
facing issue to get messages array 

### ISSUE THREAD

**Issue by makedreams45** [Webklex/php-imap#223]
Showing this error --> 
Return value of Webklex\PHPIMAP\Message::getEvent() must be an instance of Webklex\PHPIMAP\Events\Event, string returned 

query ->
$messages = $query->TO($contact_email)->setFetchOrderDesc()->limit($limit = 5, $page = $page_no)->get();

please suggest best solution

**Comment by Webklex** [comment]
Hi @makedreams45 ,
many thanks for your report. 
Please provide the entire call stack and perhaps a working / failing code snipped.

Providing as much information as possible helps people to look into it. There is also a bug report template available under https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md

Best regards & happy coding,
