### ISSUE TITLE
IOS attachments are not fetching

### ISSUE THREAD

**Issue by irfan9000** [Webklex/php-imap#227]
IOS attachments are not fetching. Kindly someone helps me. My email is: [irfan.iqbal7933@gmail.com](mailto:irfan.iqbal7933@gmail.com)

**Comment by Webklex** [comment]
Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
