### ISSUE TITLE
Empty email fetch

### ISSUE THREAD

**Issue by afawaz2** [Webklex/php-imap#230]
**Describe the bug**
We have a subset of emails that are fetching as blank when using oauth with MS Exchange. See https://github.com/freescout-helpdesk/freescout/issues/1972

The developer at FS suggested I report the issue and share an example with you, please let me know the best way to do so.

**Comment by netspear** [comment]
Hey i'm also having this issue.

https://github.com/freescout-helpdesk/freescout/issues/2094

**Comment by freescout-helpdesk** [comment]
Apparently this has been fixed in https://github.com/Webklex/php-imap/releases/tag/4.1.0

**Comment by freescout-helpdesk** [comment]
It looks like we spoke too fast: https://github.com/freescout-helpdesk/freescout/issues/1972#issuecomment-1326357106
Unfortunately with Webklex/php-imap v4.1.1 people are still experiencing this issue.
