### ISSUE TITLE
How to Send New Message ???

### ISSUE THREAD

**Issue by familiaorlando100** [Webklex/php-imap#231]
Please be aware that these issues will be closed if inactive for more then 14 days.

Also make sure to use https://github.com/Webklex/php-imap/issues/new?template=bug_report.md if you want to report a bug 
or https://github.com/Webklex/php-imap/issues/new?template=feature_request.md if you want to suggest a feature.

Still here? Well clean this out and go ahead :)

**Comment by familiaorlando100** [comment]
Can u help me  to give me a glue or example to how send a new email using this library ??

**Comment by itkfm** [comment]
IMAP (and therefore this library, too) isn’t meant to send emails.
You can add (“append”) emails to mailbox folders using `$folder->appendMessage($rawMessage);`.

To send emails, use an SMTP library (like *PHPMailer* or *SwiftMailer* for example).
