### ISSUE TITLE
Suggestion to implement mail sending

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#235]
They could implement the sending of messages using the same library and not having to install an external library such as PHPMailer.

**Comment by Webklex** [comment]
Hi @alexv96 ,
many thanks for your suggestion. 

This would be a lot of work, since sending emails utilizes a different protocol (SMTP instead of IMAP). Besides this, everybody who uses this library would also have a lot of code overhead for features they don't need.

Best regards & happy coding,
