### ISSUE TITLE
QQ mailbox official mail, failed to get the mail date. Tips：Call to a member function toDate() on null

### ISSUE THREAD

**Issue by Hanaver** [Webklex/php-imap#240]
Does anyone know how to deal with this problem?

![image](https://user-images.githubusercontent.com/25715063/176088586-ece6fe48-f649-463f-88e6-97a9fb1579ce.png)

Mail headers have no date information

Thanks

**Comment by Webklex** [comment]
Hi @Hanaver ,
thanks for this report.

You could try to enable the fallback date inside your config file:
https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L154

Please let me know if this has helped.

Best regards & happy coding,
