### ISSUE TITLE
parseBody() returns no content found

### ISSUE THREAD

**Issue by RafficMohammed** [Webklex/php-imap#241]
**Describe the bug**
I'm trying to fetch mail from rediff mail box. Some emails are providing no content found exception

**Code to Reproduce**
$message->parseBody();

        $mailBodies = $message->getBodies();

        $mailBody = '';

        $isHtmlMail = false;

        if ($mailBodies) {
            $isHtmlMail = !empty($mailBodies['html']);
            $mailBody = ($isHtmlMail) ? $mailBodies['html'] : $mailBodies['text'];
        }

```php
echo "no content found";
```

**Expected behavior**

**Screenshots**
![Screenshot from 2022-06-28 15-07-55](https://user-images.githubusercontent.com/88606418/176146988-b43158a4-e8ba-45b1-ac28-6c3716aaea05.png)
.

**Desktop / Server (please complete the following information):**
- OS: Ubuntu 20.04 LTS
- PHP: 7.3
- Version [e.g. v2.3.1]
- Provider Rediff

**Comment by Webklex** [comment]
Hi @RafficMohammed ,
many thanks for your report. Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
