### ISSUE TITLE
getBodyText is empty when message are sent from microsoft outlook

### ISSUE THREAD

**Issue by zhukovsergei** [Webklex/php-imap#245]
Hi there,
Found some issue: when I send mails from microsoft outlook, the method getBodyText() is empty: `''`.
I've attach the folowing structure of mail. The real body text you can see at the bottom of the scrennshot:
![image](https://user-images.githubusercontent.com/1946769/179543100-609ba093-281c-45bf-974f-fd6a0c08a3bc.png)

**Comment by freescout-helpdesk** [comment]
It looks like duplicate of https://github.com/Webklex/php-imap/issues/230

**Comment by freescout-helpdesk** [comment]
Are you using the latest version of **Webklex/php-imap**?
