### ISSUE TITLE
Listener going to idle

### ISSUE THREAD

**Issue by SakthiFlow** [Webklex/php-imap#249]
We are fetching the message from the inbox. suppose, if the mail does not receive for a while. then the listener go to the idle (but the command is running), It doesn't fetch any messages, even when the messages are arrive in a while. It will working only after we are re-executing the command.

**Comment by Webklex** [comment]
Hi @SakthiFlow ,
thanks for your report. I believe to have determined and fixed the issue with the latest release. Please update to >= [v4.0.0](https://github.com/Webklex/php-imap/releases/tag/4.0.0) and try again.

Best regards & happy coding,
