### ISSUE TITLE
Check other mailbox

### ISSUE THREAD

**Issue by KodaCHC** [Webklex/php-imap#252]
Hello

I want to use OAuth for Microsoft.

I have a user user1@domain.tld which has no own mailbox. Then I have a user user2@domain.tld.

user1 has FullAccess to the mailbox user2. Now how can I access the mailbox of user2 with user1?

Other question: I get the error "connection setup failed" like here: https://github.com/Webklex/php-imap/issues/232
Have you a solution for this?

**Comment by Webklex** [comment]
Hi @KodaCHC  ,
I'm not to familiar with shared outlook mailboxes. Have you checked if they are listed if you dump `var_dump($client->getFolders())` ? Perhaps their name or path are a bit strange.

Best regards,

**Comment by Webklex** [comment]
Regarding OAuth, checkout these examples: https://www.php-imap.com/examples/oauth

If you are still experiencing problems, try to enable the debug mode inside your config file:
https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L152

**Comment by KodaCHC** [comment]
Thank you for answer

I think you missed the first question?

I have used the example. I will now test debug

**Comment by Webklex** [comment]
That's possible, I'm not sure to which function you are referring to.

My experience with microsoft/azure/outlook isn't that great - its usually complicated, not intuitive and works different then everywhere else. They also don't care much about rfc standards :D

Best regards & happy coding,

**Comment by KodaCHC** [comment]
Thank you.
For SharedMailbox: https://stackoverflow.com/questions/28481028/access-office356-shared-mailbox-with-php
Have you a function for this, or what is the best soltion?

> They also don't care much about rfc standards :D
I know. really anoying

The debug:
`>> TAG1 AUTHENTICATE XOAUTH2 dXNlcj......QE= << NO AUTHENTICATE failed. >> TAG2 LOGOUT << BYE Microsoft Exchange Server IMAP4 server signing off. << OK LOGOUT completed.`
The same with the openssl command

I have found an info with the authorization for "https://outlook.office365.com/IMAP.AccessAsUser.All" which I will try

**Comment by Webklex** [comment]
Drop me a mail at github@webklex.com, I'll forward you a conversation I had a few month back.

**Comment by KodaCHC** [comment]
Thank you. I have send you the mail

**Comment by Webklex** [comment]
Hi @KodaCHC ,
I'm closing this issue. If I'm wrong and this one is still active, please feel free to reopen it :)

Best regards,
