### ISSUE TITLE
Save message to file

### ISSUE THREAD

**Issue by Webklex** [Webklex/php-imap#253]
**Is your feature request related to a problem? Please describe.**
I would like to save a message / email as file. This file should contain both the raw header and raw body (including all attachments).

**Describe the solution you'd like**
Callable via `Message::save($path)`

**Additional context**
Inspired by @bilogic question https://github.com/Webklex/laravel-imap/issues/437

**Comment by roylanceb** [comment]
This is some simple code I am using to save the email to a .eml file
```
$eml = "";
$eml .= json_decode(json_encode($smaxEmail->email->getHeader()), true)['raw'];
$eml .= $smaxEmail->email->getRawBody();
file_put_contents($folder . "/" . $filename, $eml);
```
