### ISSUE TITLE
Don't show inline images in the email 

### ISSUE THREAD

**Issue by familiaorlando100** [Webklex/php-imap#256]
Hello! Can u help me? When I try to see the message. The message has an inline attachment and it is an image but I can't see the image in the message. How can I see the image in the message?

In the html message . I have this code :
<img st-image="logo" src="cid:62aa27b50fc8d8ac52e478ae9fd1b2e9" alt="" border="0" width="200" style="float: left;">

**Comment by Webklex** [comment]
Hi @familiaorlando100 ,
the image you are looking for should be inside the attachments array:
```php
/** @var \Webklex\PHPIMAP\Message $message */
/** @var \Webklex\PHPIMAP\Support\AttachmentCollection $attachments */

$attachments = $message->getAttachments();
```

Best regards & happy coding,

**Comment by AdolphYu** [comment]
not found
