### ISSUE TITLE
no message when new message comes while running $folder->idle()

### ISSUE THREAD

**Issue by syedajmal1998** [Webklex/php-imap#257]
hello! hope you are fine.

i can read all mails & mailboxes but when i call (imap:idle), command runs but no message when new mail comes please can you help
it was working fine but 2 days ago it stopped working
'default' => [ // account identifier
            'host' => 'outlook.office365.com',
            'port' => 993,
            'encryption' => "ssl",
            'validate_cert' => true,
            'username' => 'email@domain.com',
            'password' => get_access_token(),
            'authentication' => "oauth",
        ]

**Comment by Webklex** [comment]
Hi @syedajmal1998 ,
thanks for your report. Unfortunately the provided information are not sufficient enough to make any meaningful suggestion.

Please try to provide as much information and context as possible. 
For example, what do I have to do to replicate the result?

You can find a bug report template here: https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md

Best regards & happy coding,

**Comment by syedajmal1998** [comment]
> Hi @syedajmal1998 , thanks for your report. Unfortunately the provided information are not sufficient enough to make any meaningful suggestion.
> 
> Please try to provide as much information and context as possible. For example, what do I have to do to replicate the result?
> 
> You can find a bug report template here: https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md
> 
> Best regards & happy coding,
hello thanks for you replay i created a new issue as you said:
https://github.com/Webklex/php-imap/issues/258
