### ISSUE TITLE
empty message list

### ISSUE THREAD

**Issue by mihakot** [Webklex/php-imap#260]
Hi

I'm trying to get a list of letters, according to the default example
Reads folders, sees them, but the number of letters in folders = 0

code
```
        $cm = new ClientManager(config_path('imap.php'));

        $client = $cm->account('price');
        $client->connect();
        //dump($client->isConnected());
        $folders = $client->getFolders();
        //dump($folders);
        //Loop through every Mailbox
        /** @var \Webklex\PHPIMAP\Folder $folder */
        foreach($folders as $folder){
            dump($folder->full_name);
            //Get all Messages of the current Mailbox $folder
            /** @var \Webklex\PHPIMAP\Support\MessageCollection $messages */
            $messages = $folder->messages()->limit(10,1)->get();
            dump($messages);
        }
```

result
![image](https://user-images.githubusercontent.com/1734182/185738117-5d590176-161e-4324-b4bf-1871a5500ab7.png)

emails in mailbox
![image](https://user-images.githubusercontent.com/1734182/185738187-6771f4cd-ab6b-4e7d-a06a-880f7537f658.png)

version 3.2.0
php 8.1

i enable debug

```
>> TAG1 LOGIN "****" "*****" << CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID IDLE MOVE << OK LOGIN Completed. >> TAG2 LIST "" "%" << LIST (\HasNoChildren \Unmarked \Drafts) "|" Drafts << LIST (\HasNoChildren \Marked \NoInferiors) "|" INBOX << LIST (\HasNoChildren \Unmarked) "|" Outbox << LIST (\HasNoChildren \Unmarked \Sent) "|" Sent << LIST (\HasNoChildren \Unmarked \Junk) "|" Spam << LIST (\HasNoChildren \Unmarked \Trash) "|" Trash << LIST (\HasNoChildren \Marked) "|" test << OK LIST Completed.


>> TAG3 SELECT "Drafts" << FLAGS (\Answered \Seen \Draft \Deleted $Forwarded) << 0 EXISTS << 0 RECENT << OK [PERMANENTFLAGS (\Answered \Seen \Draft \Flagged \Deleted $Forwarded \*)] Limited << OK [UIDNEXT 1] Ok << OK [UIDVALIDITY 1660628761] Ok << OK [READ-WRITE] SELECT Completed. >> TAG4 SEARCH << BAD Command syntax error. sc=PFbZO5C9DKo1_200915_6-c5d450314271

```

**Comment by mihakot** [comment]
i enable debug

>> TAG1 LOGIN "****" "*****" << CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID IDLE MOVE << OK LOGIN Completed. >> TAG2 LIST "" "%" << LIST (\HasNoChildren \Unmarked \Drafts) "|" Drafts << LIST (\HasNoChildren \Marked \NoInferiors) "|" INBOX << LIST (\HasNoChildren \Unmarked) "|" Outbox << LIST (\HasNoChildren \Unmarked \Sent) "|" Sent << LIST (\HasNoChildren \Unmarked \Junk) "|" Spam << LIST (\HasNoChildren \Unmarked \Trash) "|" Trash << LIST (\HasNoChildren \Marked) "|" test << OK LIST Completed.


>> TAG3 SELECT "Drafts" << FLAGS (\Answered \Seen \Draft \Deleted $Forwarded) << 0 EXISTS << 0 RECENT << OK [PERMANENTFLAGS (\Answered \Seen \Draft \Flagged \Deleted $Forwarded \*)] Limited << OK [UIDNEXT 1] Ok << OK [UIDVALIDITY 1660628761] Ok << OK [READ-WRITE] SELECT Completed. >> TAG4 SEARCH << BAD Command syntax error. sc=PFbZO5C9DKo1_200915_6-c5d450314271

**Comment by Webklex** [comment]
Hi @mihakot ,
thanks for your report. Please update to the latest version (>=4.0.0) and enable the debug mode inside your used config or by enabling it manually.
Config file: https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L152
Manual:
```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->getConnection()->enableDebug();
```

The query you are executing seem to miss a condition:
```php
/** @var \Webklex\PHPIMAP\Support\MessageCollection $messages */
$messages = $folder->messages()->all()->limit(10,1)->get();
```
..if you don't have a condition, use `WhereQuery::all()`. A list of available search criteria can be found here: https://www.php-imap.com/api/query

Best regards & happy coding,

**Comment by mihakot** [comment]
thanks. it worked!!
