### ISSUE TITLE
Release cycle & frequency

### ISSUE THREAD

**Issue by Webklex** [Webklex/php-imap#265]
Hi everyone,
I would like to hear from you which release frequency you would prefer. 

I usually like to publish a new release which contains several fixes and improvements at once and with some time given to the community to test them within the master itself. However I can see that this might frustrates if you have to wait quite some time for the next release.

- Should I continue with my approach?
- Switch to immediate / pre-releases?
- Or do something completely different?

Thanks in advance :)

**Comment by mihakot** [comment]
If the bug is critical or fixes the inoperability of the functionality / security, then it is better to publish it immediately.
Is it possible to release a patch version ;)
in other cases, you can also go to the minor version. Frequency can be once a month / 2 weeks
It's up to you.)

**Comment by stanolacko** [comment]
I don't like updating ala Chrome 101.
I agree with @mihakot, to release bug fix and security fix immediately.
Functionality updates will be good to not release so often. Maybe once a month is fine (maybe longer period will be also good)

**Comment by szymekjanaczek** [comment]
also agree with @mihakot - bugfixes and security first. Features can wait 2-4 weeks

**Comment by ainesophaur** [comment]
I personally love the way laravel handles releases. Ive made it a habit to update my active projects weekly where other projects get updated with major version bumps. In my eyes frequent releases keep the juices flowing and provide a motivation for maintaining a package. If a bug gets introduced, no big deal to most of us.. we can roll back to the previous version within composer and report the issue if it hasn't been reported already.

Composer's ability to lock packages within a specified range gives us the ability to control how frequently this package gets updated within our projects. If the package continues using semver then users can lock to the major and minor and not be affected by frequent patches. However, this could prevent "emergency" or security updates from being picked up. A catch 22 I guess. It could be helpful to add an example `composer require` statement to the readme to lock the package to the latest major minor for those who want to avoid patches or changes.
