### ISSUE TITLE
Invalid return type in ImapProtocol::search()

### ISSUE THREAD

**Issue by ken717w** [Webklex/php-imap#266]
**Describe the bug**
In the class `Webklex\PHPIMAP\Connection\Protocols\ImapProtocol`, the return type of `search()` has been specified to `array`. However, `$response` is being returned if it has a falsy value, while the type of `$response` could be either `array`, `bool` or `null` according to `requestAndResponse()`.

**Screenshots**
![image](https://user-images.githubusercontent.com/6499363/186339449-b3e53475-b77d-47c6-8c57-50d346732a13.png)

**Desktop / Server (please complete the following information):**
- PHP: 7.4.30
- webklex/laravel-imap: 4.0.0

**Comment by Webklex** [comment]
Hi @ken717w ,
many thanks for positing it here. I just tried to replicate the result but failed to generate the same error. Could you share some code which throws this error?

I don't doubt that the error exist, I just need to replicate it in order to determine if my patch fixed it or not :)

Best regards,

**Comment by ken717w** [comment]
@Webklex Yes sure!

I have a Laravel console command scanning my mailbox, to find out unseen emails with 'Accept' in the subject.
Here's how I do it:
```
use Webklex\IMAP\Facades\Client as ImapClient;

$client = ImapClient::account('default');
$client->connect();

$folders = $client->getFolders();

foreach ($folders as $folder) {
    $query = $folder->query();
    $query->subject('Accept');
    $query->unseen();
    $query->markAsRead();

    $messages = $query->get(); // This line throws the error

    foreach ($messages as $message) {
        // ...
    }
}
```

**Comment by Webklex** [comment]
Thanks :+1: 

I believe there is something else going on, besides your reported error. `ImapProtocol::search()` shouldn't return null / false - regardless of the outcome. Please enable the debug mode:
- Either via config: https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L152
- ..or via "setter":
```php
/** @var \Webklex\PHPIMAP\Client $client */
$client->getConnection()->enableDebug();
```

You should see something like this:
```
>> TAG10 UID SEARCH SUBJECT "Accept" UNSEEN
<< * SEARCH
<< TAG10 OK Search completed (0.001 + 0.000 secs).
```

But i suspect you'll see something like this:
```
<< TAG10 BAD Error in IMAP command UID SEARCH: ...
```
The later would indicate a failed search - which means that even if the bug didn't exists, you won't find a message with the given query. But lets see what actually happens on your end.

Best regards,

**Comment by Webklex** [comment]
Looks like it failed during the select folder part. The search therefor couldn't work.

```
TAG10 NO [NONEXISTENT] Unknown Mailbox: [Gmail]
```

Perhaps that a special google "folder"? 

`TAG10` also indicates that there were 9 actions before (a few of them are probably related to the login and folder fetching - but all of them?). If you are using the snipped from above, this could mean that it works with some of your folders, but doesn't work with a folder called `[Gmail]` - if that folder gets hit, the whole thing simply dies :)
