### ISSUE TITLE
Broken mail header/body parsing in v4.0.1

### ISSUE THREAD

**Issue by hbraehne** [Webklex/php-imap#268]
**Describe the bug**
Since release 4.0.1 message body is not parsed correctly. I updated this morning and afterwards html body is always null because everything is parsed as text.

After having a look into the changes it seems the change from commit 64ef8f00557ad129238532edf3851576eec8237c broke the message parsing. If I revert this change everything is working as expected again.

**Expected behavior**
If multiple body parts are present they should be parsed correctly and I should receive a text as well as a html part.

**Desktop / Server (please complete the following information):**
- OS: Manjaro/Debian Bullseye
- PHP: 8.1.9/8.0.18
- Version: v4.0.1
- Provider: domainfactory (unknown imap daemon)

**Comment by szymekjanaczek** [comment]
Confirmed - this fix solves the problem in my case.

**Comment by Webklex** [comment]
Ops I didn't mean to close this issue without acknowledging it.

Thanks for taking the time to look into it, It's much appreciated! 
Those regex rules are always a little gamble... 

Best regards & thanks again,
