### ISSUE TITLE
More descriptive errors for connection setup failed

### ISSUE THREAD

**Issue by ricuss** [Webklex/php-imap#282]
Hi @Webklex 

We are currently running version 3.2 in production.

After we updated to 3.2, we noticed that the connection error messages became a generic 'Connection setup failed' message when there was an issue connecting to their imap server.

Before 3.2, the error messages were very descriptive and gave us a lot of useful information on _why_ the connection failed, as sometimes it's not just wrong credentials.

I haven't been able to find a way to get the reason for the failure since the upgrade, is this possibly related to https://github.com/Webklex/php-imap/issues/270 ?

Do you know of a way to get the failure reason as apposed to just the 'Connection setup failed' message?

Thanks :)

**Comment by Webklex** [comment]
Hi @ricuss ,
do you have the same problem with the latest release [4.0.2](https://github.com/Webklex/php-imap/releases/tag/4.0.2)?

Which error message are you expecting?
I assume you are talking about the exception thrown within the `ImapProtocol::connect()` method? 
https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/ImapProtocol.php#L61-L84

The exception thrown in https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/ImapProtocol.php#L82 does contain the original error - at least in the latest release and should look similar in v 3.2. I don't remember changing it :)

Best regards & happy coding,

**Comment by ricuss** [comment]
Hi @Webklex 

The error is from the `authenticate` function in the `Client` class, see below:

![image](https://user-images.githubusercontent.com/17425015/190077249-4cc4d742-c580-472f-ad1a-3d7ad7adf0b6.png)

We hit the `AuthFailedException` and then throw the `ConnectionFailedException` where I can access the AuthFailedException with `->getPrevious()` but there is no message on the `AuthFailedException`, and the message on the `ConnectionFailedException` is the generic 'Connection setup failed`.

Previously we also had the connection wrapped in a try catch, and calling `->getMessage()` on it would return the imap error string we got from the server. The message itself ranged in content, depending on what the server sent back, but it helped a lot in identifying why a connection could not be established.

I checked it out on 4.0.2 quickly, and get the same, see below. 

![image](https://user-images.githubusercontent.com/17425015/190078134-cfee48b2-2d25-44cd-bf9f-1f2cf919ee3d.png)

Any idea why I might not be getting the reason for the failure?

**Comment by Webklex** [comment]
Ah so we are talking about this method:
https://github.com/Webklex/php-imap/blob/master/src/Client.php#L381-L393

It changed with this commit almost two years ago: https://github.com/Webklex/php-imap/commit/b4dc869147e5ecf840dd7c6c6a04776709b7ffca

I don't see where you are missing the exception. It looks like everything is there.
In your case the authentication simply failed. Looking at https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/ImapProtocol.php#L415-L441 it looks like the case you've described gets handled within it: https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/ImapProtocol.php#L429-L435

Which errors besides bad credentials were you expecting to receive?

**Comment by ricuss** [comment]
When I did the upgrade I moved from the laravel one to the core php-imap, I wonder if that is maybe related.

An example of the type of error messages we used to get:

```
imap_open(): Couldn't open stream {imap2.redacted.co.za:143/imap/novalidate-cert}. Kerberos error: No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1001) (try running kinit) for [xxx.xx.xx.xxx]; Retrying PLAIN authentication after AUTHENTICATE failed.; Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (server response) 
```

```
map_open(): Couldn't open stream {outlook.office365.com:993/imap/novalidate-cert/ssl}. Retrying PLAIN authentication after AUTHENTICATE failed.; Retrying PLAIN authentication after AUTHENTICATE failed.; Can not authenticate to IMAP server: AUTHENTICATE failed.
```

I would like to get access to those messages again but haven't been able to.

As a condensed example to be able to reproduce on your side you can try the following:

```php
 $cm = new ClientManager(config('imap'));

      $data = [
          'username'      => "invalid@invalid.com",
          'password'      => "invalid",
          'host'          => 'imap.gmail.com',
          'port'          => 993,
          'encryption'    => 'ssl',
          'protocol'      => 'imap',
          'validate_cert' => false,
      ];

      $oClient = $cm->make($data);

      try{
          $oClient->connect();
      }
      catch(\Exception $e){
         dump($e);
      }
```

I'm trying to get an error message similar to the ones above in the catch, which I'm not able to

**Comment by ricuss** [comment]
Thanks for the time looking into this @Webklex , really appreciate it. I still need to update to v4 (got released just as I updated to v3 haha)

Have a good one
