### ISSUE TITLE
I had the same problem as issue #82, #90

### ISSUE THREAD

**Issue by matran2210** [Webklex/php-imap#283]
Hi @Webklex 
I had the same problem as issue #82, #90
![ccc](https://user-images.githubusercontent.com/64309499/190124553-95885aa7-4ebe-47db-a807-1f858feb81e2.png)

i use $message->getHtmlBody() and receive all (html + base64 attachment) 
i use $message->getAttachments()  and did'nt anything

This is all the content I received:
[getHTMLBody.txt](https://github.com/Webklex/php-imap/files/9565198/getHTMLBody.txt)

**Comment by matran2210** [comment]
@Webklex  Can you help me like issue #82 ?

**Comment by matran2210** [comment]
@Webklex Can you help me like issue https://github.com/Webklex/php-imap/issues/82 ?

**Comment by Trent-A** [comment]
Hello @Webklex.  Thank you for a great library.  I do concur with @matran2210, I am dealing with a similar issue with attachments connecting to Office365 emails.  Several developers have tried, we've updated the config variables 'dispositions' for 'attachment' 'inline', tried various different file types, attached them inline, and tried several different techniques found here within the other issues with no luck.  When outputting the $message->getStructure()->raw, you can see the attachment encoding, but $message->getAttachments never finds anything.  Would love to put this into production before the Microsoft Oct 1, 2022 OAuth 2.0 requirement deadline.  Thanks!

**Comment by Webklex** [comment]
Hi @matran2210 ,
many thanks for your report. To verify and replicate your report I'll need some additional information:
- Used config -- Please provide the used config, if you are not using the package default config.
- Code to Reproduce -- The troubling code section which produces the reported bug.

Desktop / Server (please complete the following information):
- OS: [e.g. Debian 10]
- PHP: [e.g. 5.5.9]
- Version [e.g. v2.3.1]
- Provider [e.g. Gmail, Outlook, Dovecot]

I doubt that this is related to 82 or 90 but please feel free to prove me wrong. 

@Trent-A Regarding your deadline, I'm sorry but I can't promise anything - after all this is an open source project. I'm not getting payed for any of this. What ever pays my rent and food comes first :)

Best regards & happy coding,

**Comment by matran2210** [comment]
Thank you for your support @Webklex 
Used config:
host: imap.gmail.com
port: 993
encrypt: SSL

But, this is caused by the outgoing email server and not related to the imap configuration.
Error outgoing email server:
host: mail.efy.com.vn
port: 25
And when I use another outgoing mail server, I don't have this issue

I sent a test mail to github@webklex.com using error mail server mail.efy.com.vn
Can you help me check? @Webklex

**Comment by Webklex** [comment]
Hi @matran2210 ,
this library isn't capable of sending messages. To send messages, you'll need to use a different protocol (SMTP) which isn't supported by this library.

I'm confused what you are trying to archive. Please provide the code you are using and which is producing the error. Also on which operating system are you having this issue? Which version of this library are you using? Which php version are you using? Does it only happen with Google / gmail accounts or does it work with other providers? 

Best regards & happy coding,
