### ISSUE TITLE
Some Subjects Aren't Properly Decoded

### ISSUE THREAD

**Issue by roylanceb** [Webklex/php-imap#289]
Hi,

Some emails that my script is processing are not having their subjects decoded correctly.

For example, the subject in the browser is:
**ACCEPT SOLUTION: Forespørsel #2168555: GJG: 531117 - CH: WVWZZZCDZNW220304**

But when trying to process the email via a script the subject is:

```
Webklex\PHPIMAP\Attribute Object
(
    [name:protected] => subject
    [values:protected] => Array
        (
            [0] => =?iso-8859-1?Q?ACCEPT_SOLUTION:_Foresp=F8rsel_#2168555:_GJG:_531117_-_CH:?= =?iso-8859-1?Q?_WVWZZZCDZNW220304?=
        )

)
```

Any suggestions on how best to decode this string? I have tried `iconv` and `mb_convert_encoding` but I have not been able to get it to work.

When detecting the encoding with `mb_detect_encoding` the output is **ASCII**

**Comment by Dibbyo456** [comment]
Having the same issue.

**Comment by roylanceb** [comment]
This is still happening. It's often when the subject contains non latin characters. So far we have encountered it with Norwegian characters (ø, æ and å) as well as Chinese and Korean characters.
The way we have fixed it is to decode the subjects using `iconv_mime_decode` but it would be nice to not have to use a workaround

**Comment by Webklex** [comment]
Hi @roylanceb ,
many thanks for your report. Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
