### ISSUE TITLE
parseBody() & nextLine() - problem with double "\n"

### ISSUE THREAD

**Issue by jack-2729** [Webklex/php-imap#293]
**Describe the bug**
When body is separeted from header with two or more "\n" the function nextLine() thows a RuntimeException with message 'empty response'

**Code to Reproduce**
```php
        /** @var Webklex\PHPIMAP\ClientManager $cm */
        $client_manager = new ClientManager($options = []);

        /** @var \Webklex\PHPIMAP\Client $client */
        $client = $client_manager->make([
            'host' => "outlook.office365.com",
            'port' => 993,
            'encryption' => "ssl",
            'validate_cert' => true,
            'username' => "username",
            'password' => "access_token",
            'protocol' => 'imap',
            'authentication' => "oauth"
        ]);

        $client->connect();

        if (!isset($client) || !$client->isConnected()) {
            throw new \Exception("Cannot connect IMAP service");
        }

        $client->checkConnection();

        /** @var Webklex\PHPIMAP\Folder $folder*/
        $folder = $client->getFolderByName("INBOX");

        /** @var \Webklex\PHPIMAP\Message $message */
        $message = $folder->query()->getMessageByUid($uid = $uid);
```

**Expected behavior**
Function nextLine() read body despite it is seperated from header by two or more '\n'

**Screenshots**
Example of raw file
``` 
=?Windows-1252?Q?euHxzLy7ZFW/osqOmPOQn200R+dh7Np2oiEUYA=3D=3D?=


------=_NextPart_001_239A_273F714F.45965D0B
```
**Possibile solution**
I try this solution and for my problem works
```php
    public function nextLine(): string {
        $line = "";
        while (($next_char = fread($this->stream, 1)) !== false && $next_char !== "\n") {
            $line .= $next_char;
        }
        if ($line === "" && $next_char !== "\n") {
            throw new RuntimeException('empty response');
        }
        if ($this->debug) echo "<< ".$line."\n";
        return $line . "\n";
    }
```

**Desktop / Server :**
- OS: RockyLinux
- PHP: 8.0
- Version 4.0.2
- Provider Gmail

**Comment by marcelmolenaar** [comment]
I experienced the same issue. Jack's solution works for me as well

**Comment by Peter-Smith-Activ** [comment]
I'm having the same bug, and Jack's solution worked for me as well. Pull request https://github.com/Webklex/php-imap/pull/274 looks like it will address this - the proposed code there works for me too.

**Comment by Webklex** [comment]
Hi, 
many thanks for your reports. Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
