### ISSUE TITLE
Handle Decoding Attachment Quote Printable Name Property

### ISSUE THREAD

**Issue by freestyledork** [Webklex/php-imap#294]
When calling `getName()` on an attachment that contains quote printable encoded text it's not decoded.  I am not sure if this is by design or not. 
example: `name="=?UTF-8?Q?Mesa=2C_AZ_=2D_Vito=E2=80=99s_Pizza_=26_Italian_Ristorante_pizza=2Epng?="`

It appears the `Header` Class already has logic to handle this, but it's access level is private. I suggest moving parsers to a Trait or modifying the access to public for the `decode()` method. I was able to get it to work with a custom mask navigating the relationships and manually setting the package file method to public. This obviously wont work in production as the composer files are often recreated. 

```
    public function getDecodedName(){
        return $this->parent->getMessage()?->getHeader()->decode($this->parent->name);
    }
```

If there is another solution I am missing please share, thanks.

**Comment by Webklex** [comment]
Hi @freestyledork ,
many thanks for your report. Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
