### ISSUE TITLE
Example issues error message Class "Webklex\PHPIMAP\ClientManager" not found

### ISSUE THREAD

**Issue by freebrowser1** [Webklex/php-imap#295]
**Describe the bug**
On the page https://www.php-imap.com/examples/getting-started I found an example which I tested after installation.

I followed the instructions to install by https://www.php-imap.com/installation in which I performed 

```
cd ~/my web root
git clone https://github.com/Webklex/php-imap.git
cd php-imap
composer install
```
which succeeded all.

Then I executed PHP code :

```php
use Webklex\PHPIMAP\ClientManager;
use Webklex\PHPIMAP\Client;

$cm = new ClientManager('path/to/config/imap.php');

```
That issued an error :

Fatal error: Uncaught Error: Class "Webklex\PHPIMAP\ClientManager" not found in /[path]/php-imap/example.php:12 Stack trace: #0 {main} thrown in /[path]/php-imap/example.php on line 12

But the issue is that the class ClientManager does exist in src/ClientManager.php. 
Even adding `namespace Webklex\PHPIMAP;` at the very beginning did not help.

I tried it on 

* Centos 7 running PHP 7.4 and 8.1, two different servers
* macOS 12.5 running Homebrew'ed PHP 8.1

It issued the same error on all tested platforms and PHP versions.

**Comment by Webklex** [comment]
Hi @freebrowser1 ,
many thanks for your report. 
Did you also include / require the composer bootstrap file or how are you loading the dependencies? 

Best regards & happy coding,
