### ISSUE TITLE
Error in Attachment::__construct 

### ISSUE THREAD

**Issue by d4mn** [Webklex/php-imap#3]
**Describe the bug**
Call to undefined function Webklex\PHPIMAP\config() 
I think this function is from laravel

**To Reproduce**
If message is with attachment this error comes out.  

**Expected behavior**

**Screenshots**

**Desktop / Server (please complete the following information):**
- PHP: [e.g. 5.5.9]

**Additional context**

**Comment by Webklex** [comment]
Hi @d4mn ,
thanks for the info. I just released a fixed version :)
