### ISSUE TITLE
I can't connect to office 365, error authenticate failed.

### ISSUE THREAD

**Issue by wawa67** [Webklex/php-imap#302]
I can connect in gmail but in outlook/office 365 always return the message "Retrying PLAIN authentication after AUTHENTICATE failed." same with user and password correct.

'options' => [
        'delimiter' => '/',
        'fetch' => \Webklex\IMAP\IMAP::FT_UID,
        'fetch_body' => true,
        'fetch_attachment' => true,
        'fetch_flags' => true,
        'message_key' => 'id',
        'fetch_order' => 'asc',
        'open' => [
             //'DISABLE_AUTHENTICATOR' => 'GSSAPI'
        ],
        'decoder' => [
            'message' => [
                'subject' => 'utf-8' // mimeheader
            ],
            'attachment' => [
                'name' => 'utf-8' // mimeheader
            ]
        ]
    ],

$imapClient = new Client([
            'host'          => 'outlook.office365.com',
            'port'          => 993,
            'encryption'    => 'SSL',
            'validate_cert' => false,
            'username'      => 'xyz@outlook.com',
            'password'      => 'password',
            'protocol'      => 'imap',
        ]);

imap_open(): Couldn't open stream {outlook.office365.com:993/imap/novalidate-cert/ssl}. Retrying PLAIN authentication after AUTHENTICATE failed.; Retrying PLAIN authentication after AUTHENTICATE failed.; Can not authenticate to IMAP server: AUTHENTICATE failed.  

was expected that will connected without problems of authenticate.

- Laravel: 5.5
- PHP: 7.2
- Version Webklex: ^1.6
- Provider Outlook/Office 365

**Comment by AzzaAzza69** [comment]
Microsoft are moving away from regular username + password authentication in IMAP and instead you can use OAUTH...
see #297 for an explanation on how to do this.
PS. If you had searched for either "office" or "authenticate" you would have found this!

**Comment by wawa67** [comment]
> A Microsoft está se afastando do nome de usuário regular + autenticação de senha no IMAP e, em vez disso, você pode usar o OAUTH... ver #297 para uma explicação sobre como fazer isso. PS. Se você tivesse procurado por "escritório" ou "autenticar" você teria encontrado isso!

I would like to do this without use the azure, do no is possible?

**Comment by AzzaAzza69** [comment]
AFAIK...You need to use Azure to create the app / client id and client secret...I don't know of any way around it...

**Comment by rmontagud** [comment]
> > Microsoft are moving away from regular username + password authentication in IMAP and instead you can use OAUTH...
> > see #297 for an explanation on how to do this.
> > PS. If you had searched for either "office" or "authenticate" you would have found this!
> 
> @AzzaAzza69 I would like to do this without use the azure, do no is possible?

You're out of luck, there's a grace perioud where You can enable again basic authentication for select protocols (IMAP and POP3 among them) but it will last [until the end of December](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437 )

**Comment by wawa67** [comment]
> > > Microsoft are moving away from regular username + password authentication in IMAP and instead you can use OAUTH...
> > > see #297 for an explanation on how to do this.
> > > PS. If you had searched for either "office" or "authenticate" you would have found this!
> > 
> > 
> > @AzzaAzza69 I would like to do this without use the azure, do no is possible?
> 
> You're out of luck, there's a grace perioud where You can enable again basic authentication for select protocols (IMAP and POP3 among them) but it will last [until the end of December](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437)

@rmontagud i understand do you have a tutorial for me activate for while?
