### ISSUE TITLE
How to get the "oldest" message

### ISSUE THREAD

**Issue by AzzaAzza69** [Webklex/php-imap#304]
I am struggling to see how to instruct the IMAP server to get me the oldest message, 
ie. sort by SORTDATE/SORTARRIVAL (like imap_sort())
and ideally limit results to 1 as I only want the date of the oldest message in a folder that contains thousands of emails..
...any ideas anyone?

**Comment by Webklex** [comment]
HI @AzzaAzza69 ,
unfortunately the IMAP protocol doesn't support much in terms of sorting. You can only sort by message id / uid. However you could sort by uid and only fetch the last 20 messages with the lowest uids and sort them by date or what ever afterwards.

If you find a better way, please let me know :)

Best regards & happy coding,
