### ISSUE TITLE
UTF encoded subject does not get decoded properly without php-imap enabled

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [Webklex/php-imap#31]
I noticed when the php-imap module is not enabled, UTF encoded subjects do not get decoded properly.
The reason for this is the function Header::rfc822_parse_headers transforms the subject to lowercase (line 204) when parsing the headers.

**Comment by Webklex** [comment]
Hi @AntonioDiPassio-AppSys ,
thanks for your report. Unfortunately I'm not able to locate the mentioned location.
Line 204 only consists of `} else {`. 
https://github.com/Webklex/php-imap/blob/master/src/Header.php#L204

Best regards,

**Comment by AntonioDiPassio-AppSys** [comment]
My bad, should be line 207.
