### ISSUE TITLE
connection setup failed

### ISSUE THREAD

**Issue by FatimaAlsabry** [Webklex/php-imap#310]
I am using laravel Webklex\PHPIMAP, i have connect the project to outlook.microsofrt365 and it was working well without errors,
since two days the project stop working and give me "connection setup failed" error.

I tried to use gmail it is working good, but outlook stopped working.

$cm = new ClientManager($options = []);
        $client = $cm->make([
            'host'          => 'outlook.office365.com',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => 'username',
            'password'      => 'password',
            'protocol'      => 'imap'
 ]);
        $client->connect();
        $folders = $client->getFolders('INBOX');
return $folders;

bug apeare in { $client->connect(); }

- OS: [windows]
- PHP: [8.0.2]
- Provider [Outlook]

**Comment by Webklex** [comment]
Hi @FatimaAlsabry ,
do you know if someone changed / modified your azure setup, code or dependencies without you noticing?

Can't think of a "feature" which could have caused this. But please prove me wrong :)

Best regards & happy coding,

**Comment by FatimaAlsabry** [comment]
Thank you, it's true someone close the imap-port without notice.
