### ISSUE TITLE
Incorect attachment name (undefined) with ISO-8859-2

### ISSUE THREAD

**Issue by uiozgadaniel** [Webklex/php-imap#317]
Hi,
I am using Webklex/php-imap to receive messages by IMAP via OAuth (accessToken).
Everything is working except attachments names sending by big polish email provider - interia.pl.

Emails attachments sent via Gmail, RoundCube or Outlook are correctly named, but from Interia.pl unfortunately not.

**Problem:**
Attachment name is "undefined" fo email sent with ZIP attachments which have polish characters in names (ĄĘŁÓŻĆ etc.)
Attachments always has "undefined" name for these type of attachment from Interia.pl provider.
This may not be the only provider with this problem.

**Expected result:**
Attachment name should be "Dane Październik Test"

Attachment header from interia.pl (here we have name with asterisk * and with iso-8859-2 coding):
```
Content-Type: application/zip;
	name*=iso-8859-2''Dane%20Pa%BCdziernik%20Test.zip
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename*=iso-8859-2''Dane%20Pa%BCdziernik%20Test.zip
```

Attachment header from Gmail.com:
```
Content-Type: application/x-zip-compressed; 
	name="=?UTF-8?Q?Dane_Pa=C5=BAdziernik_Test=2Ezip?="
Content-Disposition: attachment; filename="=?UTF-8?Q?Dane_Pa=C5=BAdziernik_Test=2Ezi?=
	=?UTF-8?Q?p?="
Content-Transfer-Encoding: base64
Content-ID: <f_la2f2fy50>
X-Attachment-Id: f_la2f2fy50
```

Attachment header from Roundcube:
```
Content-Transfer-Encoding: base64
Content-Type: application/zip;
 name="=?UTF-8?Q?Dane_Pa=C5=BAdziernik_Test=2Ezip?="
Content-Disposition: attachment;
 filename*=UTF-8''Dane%20Pa%C5%BAdziernik%20Test.zip;
 size=46742
```

I thought I can override Part class (here: https://github.com/Webklex/php-imap/blob/master/src/Part.php#L174 ) with something like this below, but it isn't a solution, because we need to decode this name correctly:
```
        $this->name = $this->header->get("name") ?? $this->header->get("name*");
        $this->filename = $this->header->get("filename") ?? $this->header->get("filename*");
```
Result for above part of code:
`iso-8859-2''Dane%20Pa%BCdziernik%20Test.zip`

This is not same problem like here: https://github.com/Webklex/php-imap/issues/102 . Here we don't have a subject but an attachment name.

Is any possibility to help me to resolve this problem?
Thank you in advance and best regards

**Comment by tbcshifter** [comment]
Having the same issue here with some emails. This has nothing to do with interia.pl. Attachment file name is coming in as `undefined` due to the `name*` header convention with multiple parts.

```
------=_Part_1902_1155419969.1673913790532
Content-Type: text/plain; charset="us-ascii";
	name*0="audit_report_2023-01-16_1673";
	name*1="913600010.txt"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
	filename*0="audit_report_2023-01-16_1673";
	filename*1="913600010.txt"
```

**Comment by tbcshifter** [comment]
I made a patch on my own for this, which works in my case, but may not work in all cases. I made the same patch for `name` and `filename`.

```
if(!empty($this->header->get("name"))) {
  $this->name = $this->header->get("name");
} else if(!empty($this->header->get("name*"))) {
  $this->name = $this->header->get("name*");
} else if(!empty($this->header->get("name*0"))) {
  $this->name = "";
  for($i=0; $i<=100; $i++) {
    if(!empty($this->header->get("name*".$i))) {
      $this->name .= $this->header->get("name*".$i);
    }
  }
}
```

**Comment by Webklex** [comment]
Hi @uiozgadaniel @tbcshifter ,
many thanks for your reports. Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
