### ISSUE TITLE
Attachments - method getId can return empty value

### ISSUE THREAD

**Issue by uiozgadaniel** [Webklex/php-imap#318]
**Bug description**
During use of Webklex PHP Imap I encountered a problem with non-incoming attachments.
After debugging I found a problem with attachment ID in Message.php file on line 592:
https://github.com/Webklex/php-imap/blob/master/src/Message.php#L592
In my case getId method 4 out of 7 attachments, returns an empty value (an empty string value).

**Bug result**
Not all attachments are saved by missing attachments in the message.

**Proposed solution**
One of solution can be changing [this line](https://github.com/Webklex/php-imap/blob/master/src/Message.php#L592) to:
```
...
if (!empty($oAttachment->getId())) { 
    ....
```

Is there a chance to improve this part of code?

**Comment by Webklex** [comment]
Hi @uiozgadaniel ,
many thanks for your report!

Best regards,
