### ISSUE TITLE
Missing symfony/mime dependency

### ISSUE THREAD

**Issue by pwoszczyk** [Webklex/php-imap#323]
symfony/mime is used as fallback in `Webklex\PHPIMAP\Attachment` but dependency is not defined in `composer.json`. It cause fatal error if `symfony/http-foundation` >= 5.0 and `symfony/mime` is not installed.

```
$guesser = "\Symfony\Component\Mime\MimeTypes";
/** @var Symfony\Component\Mime\MimeTypes $guesser */
$extensions = $guesser::getDefault()->getExtensions($this->getMimeType());
```

```
"require": {
    "php": ">=7.0.0",
    "ext-openssl": "*",
    "ext-json": "*",
    "ext-mbstring": "*",
    "ext-iconv": "*",
    "ext-fileinfo": "*",
    "nesbot/carbon": ">=1.0",
    "symfony/http-foundation": ">=2.8.0",
    "illuminate/pagination": ">=5.0.0"
},
```

**Comment by pwoszczyk** [comment]
My fix suggestion https://github.com/Webklex/php-imap/pull/324

**Comment by pwoszczyk** [comment]
Fix: https://github.com/Webklex/php-imap/pull/325

**Comment by Webklex** [comment]
Hi @pwoszczyk ,
many thanks for your report and pull request!

I haven't noticed that it has moved recently.  Thanks for catching it :)

Best regards,
