### ISSUE TITLE
Display all emails conversation and replies 

### ISSUE THREAD

**Issue by raubinjake** [Webklex/php-imap#330]
Hi @Webklex ,
I am still facing the problem for display the email conversation. 

/** @var \Webklex\PHPIMAP\Message $message */
$thread = $message->thread();

And above code is throwing the error undefined thread method. 
Please help.
Thanks:-

**Comment by raubinjake** [comment]
Hi, @Webklex 
This is my code ..



<?PHP

use Webklex\IMAP\Facades\Client;

/** @var \Webklex\PHPIMAP\Client $client */
$oClient = Client::account('default');
$oClient->connect();


/** @var \Webklex\IMAP\Support\FolderCollection $aFolder */
//$mails = $oClient->getFolders();
$aFolder = $oClient->getFolders();

//Loop through every Mailbox
/** @var \Webklex\IMAP\Folder $oFolder */
foreach($aFolder as $oFolder){
    //Get all Messages of the current Mailbox $oFolder
    /** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
    $aMessage = $oFolder->messages()->all()->get();
 
    /** @var \Webklex\IMAP\Message $oMessage */
    foreach($aMessage as $oMessage){
        $msg[] = $oMessage->thread($sent_folder = null);

        echo $oMessage->getSubject().'<br />';
        // echo 'Attachments: '.$oMessage->getAttachments()->count().'<br />';
        // echo $oMessage->getHTMLBody(true).'<br />';
       // echo 'Attachments: '.($oMessage->getAttachments(true));

        $aAttachment = $oMessage->getAttachments();
        $message_id =  $oMessage->getMessageId();
        $message_id = $message_id[0];
      

   }
   return $msg;
	
}


?>



This is throughing error by webklex : ---

Webklex\PHPIMAP\Message::fetchThreadByInReplyTo(): Argument #5 ($sent_folder) must be of type Webklex\PHPIMAP\Folder, null given, called in
vendor\webklex\php-imap\src\Message.php on line 795

**Comment by Webklex** [comment]
Hi @raubinjake ,
thanks for the code snipped. 

Which email provider are you using and have you updated your `webklex/php-imap` and `webklex/laravel-imap` dependencies to the latest release? 
Do you use a custom config or are you using the default config (https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php)?
Is your sent folder path (as configured here: https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php#L163) correct and does that folder exist?

The provided error message suggests that the configured common sent folder could not be found.

Best regards & happy coding,

**Comment by kieranoreilly** [comment]
Im getting this same error. Here are the details:
**Code**:
```
$client = Webklex\IMAP\Facades\Client::account('default');
$client->connect();
$folders = $client->getFolders();
$messages = $folders[0]->messages()->all()->get();
$messages[45]->thread()
```
**webklex/laravel-imap version**: 4.0
**Email provider**: gmail
**imap sent folder config:** 
```
        'common_folders' => [
            "root" => "INBOX",
            "junk" => "INBOX/Junk",
            "draft" => "[Gmail]/Drafts",
            "sent" => "[Gmail]/Sent Mail",
            "trash" => "[Gmail]/Trash",
        ],
```
**error message:**    
```
TypeError  Webklex\PHPIMAP\Query\Query::setFetchBody(): Argument #1 ($fetch_body) must be of type bool, null given, called in vendor/webklex/php-imap/src/Message.php on line 823.
```

Any help would be appreciated

**Comment by kieranoreilly** [comment]
I believe I was able to solve this locally by changing the vendor to have a default of true instead of null for $fetch_body. Now I just need to solve it when I deploy
