### ISSUE TITLE
$folder->idle() breaks on receiving new message

### ISSUE THREAD

**Issue by the-alichemist** [Webklex/php-imap#334]
Hi, for the last day or two, the idle() command throws exception on receiving new message.  My client is connecting just fine and rest of the Imap functions are working okay too. 
![Screenshot 2022-11-19 085000](https://user-images.githubusercontent.com/88083032/202832938-131692b2-c21f-4268-9043-d1a677aa24d9.png)

**Comment by the-alichemist** [comment]
Fix: 
@Webklex
Replace the exception class,
from: \Exception\Runtime
to: \Webklex\PHPIMAP\Exceptions\RuntimeException in Folder.php in catch() section of 'idle' method..

It works then..
![Screenshot 2022-11-22 191846](https://user-images.githubusercontent.com/88083032/203344868-412d3c05-88a0-474b-9e41-145d157128c5.png)

**Comment by Webklex** [comment]
Hi @the-alichemist ,
Many thanks for your report. Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
