### ISSUE TITLE
GetTextBody() return null

### ISSUE THREAD

**Issue by xone0** [Webklex/php-imap#336]
Hi.

whenever I use getTextBody it returns me null but when I do getHTMLBody it gives me html code with the body

here is print_r of message

-> getTextBody() return null

**Comment by Webklex** [comment]
Hi @xone0 ,
Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
