### ISSUE TITLE
move() to Trash function not working

### ISSUE THREAD

**Issue by xone0** [Webklex/php-imap#337]
Can someone help me why do the messages not all go in the trash what am I doing wrong?

here is my code via Laravel 9

        $f = $mail->getFolder('INBOX');
        $messages = $f->query()->since(now()->subDays(1))->get(); // today

        foreach ($messages as $message) {
            kontaktes::create([
                'name' => $message->getSubject(),
                'email' => $message->getFrom(),
                'subject' => $message->getSubject(),
                'message' => strip_tags($message->getHTMLBody())
            ]);

            $message->move('TRASH');
        }

        return view('admin.pages.kontakt', get_defined_vars());

**Comment by stanolacko** [comment]
You are filtering messages for 1 day old. If you need to move after
processing all messages, you need to remove that filter.

Dňa po 28. 11. 2022, 18:17 xone0 ***@***.***> napísal(a):

**Comment by xone0** [comment]
thanks for your message makes sense
