### ISSUE TITLE
idle function only calling the function call on first email received when multiple emails are received simultaneously (with gmail at least)

### ISSUE THREAD

**Issue by mbfdias** [Webklex/php-imap#338]
Hi 

When executing $folder->idle(function($message){ } I noticed that in some cases, when receiving several emails simultaneously, I only get the first email processed, and the rest doesn't trigger any more the function call... 

is there a way to overcome this?

**Comment by Webklex** [comment]
Hi @mbfdias ,
many thanks for your report. Please update to the latest release and try again.

The idle method has been reworked to prevent this issue.

Best regards,
