### ISSUE TITLE
How to move locally saved emails

### ISSUE THREAD

**Issue by Mohaziz93** [Webklex/php-imap#344]
Hello everyone am wondering how to move local saved emails to Sent folder .. Am sending emails using SMTP but I can’t find them on sent folder when i access mail through web

**Comment by mgurg** [comment]
I'am using PHPmailer to send email, try `appendMessage` method:
```php
            $mailToImap->preSend();
            $message = $mailToImap->GetSentMIMEMessage();

            ...
            $mailAccount->appendMessage($message);
```
