### ISSUE TITLE
Attachments not found on some messages

### ISSUE THREAD

**Issue by mdemori** [Webklex/php-imap#348]
**Describe the bug**
Attachment not show on specific message, if same message is open on Thunderbird, Outlook or other clients (even web one like Roundcube) the attachments are shown

**Used config**
All settings are default.

**Below the php-imap version:**
composer show webklex/php-imap

name     : webklex/php-imap
descrip. : PHP IMAP client
keywords : imap, mail, php-imap, pop3, webklex
versions : * 4.1.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://github.com/webklex/php-imap
source   : [git] https://github.com/Webklex/php-imap.git 94bf93ae8868ac1e073cfbaef377f0ca1acac2bc
dist     : [zip] https://api.github.com/repos/Webklex/php-imap/zipball/94bf93ae8868ac1e073cfbaef377f0ca1acac2bc 94bf93ae8868ac1e073cfbaef377f0ca1acac2bc
path     : [REDACTED]/vendor/webklex/php-imap
names    : webklex/php-imap

support
issues : https://github.com/Webklex/php-imap/issues
source : https://github.com/Webklex/php-imap/tree/4.1.2

autoload
psr-4
Webklex\PHPIMAP\ => src

requires
ext-fileinfo *
ext-iconv *
ext-json *
ext-mbstring *
ext-openssl *
illuminate/pagination >=5.0.0
nesbot/carbon >=1.0
php >=7.0.0
symfony/http-foundation >=2.8.0

requires (dev)
phpunit/phpunit ~4.0

suggests
symfony/mime Recomended for better extension support

**Code to Reproduce**
call
$attachments = $message -> getAttachments();
$attachments->count()  

return 0 even if an attachments is present.
- if I do a var_dump($attachments) return an empty Attachments object

**Expected behavior**
I need to extract attachments from message using $attachment->getAttributes()['content']

**Screenshots**
![thunderbird-attachment](https://user-images.githubusercontent.com/2266315/208054236-eddcb53f-8705-45e5-8e13-0d84002f5c41.png)

**Desktop / Server (please complete the following information):**
- OS: Ubuntu 22.04.1 LTS
- PHP: PHP 7.4.33 (cli) (built: Nov  8 2022 11:33:35) ( NTS )
- Version  webklex/php-imap 4.12
- Provider: greenmail-standalone-2.0.0-alpha-2 for testing, Dovecot latest on production
- Client: Thunderbird, Outlook, Roundcube (all are latest version)

**Additional context**
attached below you will find an eml that can be used to test this case, is zip compressed otherwise I can't upload it.
[2 - test_attachment_not_reconized.zip](https://github.com/Webklex/php-imap/files/10243944/2.-.test_attachment_not_reconized.zip)

**Comment by ditug** [comment]
I miss also Files. If i send from Outlook 2 inline & 2 attached Images-Files, i receicve only 2 Files. If i attach a rfc822-Forwarded-Email and different other Files, only the rfc ist available, not the other Files.

**Comment by eduardom456** [comment]
Perhaps this is an add-on to the problem I'm having.

[https://github.com/Webklex/php-imap/issues/370](url)

**Comment by AdrianKuriata** [comment]
Check this PR and give feedback if it solve your problem. https://github.com/Webklex/php-imap/pull/372

**Comment by Webklex** [comment]
Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,
