### ISSUE TITLE
Read all folders?

### ISSUE THREAD

**Issue by consigliere23** [Webklex/php-imap#349]
INBOX/Junk%20E-mail
I have like this folder in Mozilla thunderbird and it's Junk/Spam.
Beside this I also have Archive, Deleted Items and Sent folders.

$folders = $client->getFolders();

This returns only INBOX folder and nothing else.
Can I get all folders and read emails inside each folder?

**Comment by grisha2217** [comment]
+1
Same problem with "INBOX/Newsletters" folder
getFolders() method does not return this folder.

**Comment by consigliere23** [comment]
Any updates?

**Comment by Webklex** [comment]
Hi @consigliere23 @grisha2217 ,
you are probably looking to fetch a folder not hierarchical:
```php
$folders = $client->getFolders(false);
```

Best regards,

**Comment by grisha2217** [comment]
> Hi @consigliere23 @grisha2217 , you are probably looking to fetch a folder not hierarchical:
> 
> ```
> $folders = $client->getFolders(false);
> ```
> 
> Best regards,

No, same problems with getFolders(false) and getFolders(true)
