### ISSUE TITLE
ImapProtocol::logout always throws 'not connected' Exception after upgraded to 4.1.2

### ISSUE THREAD

**Issue by gitstashgithub** [Webklex/php-imap#351]
After the upgrade the logout function always throws the RuntimeException. I checked the `$this->stream` value and it's NULL.

src/Connection/Protocols/ImapProtocol.php
```
public function logout(): array {
        if (!$this->stream) {
            throw new RuntimeException('not connected');
        }

        $result = $this->requestAndResponse('LOGOUT', [], true);

        fclose($this->stream);
        $this->stream = null;
        $this->uid_cache = null;

        return $result;
    }
```

Does anyone know how to solve this? Thanks!

**Comment by Webklex** [comment]
Hi @gitstashgithub ,
many thanks for your report. I was able to replicate the behavior and pushed a fix :)

Best regards,
