### ISSUE TITLE
Why 8.0.2 PHP?

### ISSUE THREAD

**Issue by consigliere23** [Webklex/php-imap#361]
Is there any reasonable reason why need now 8.0.2 PHP version?

**Comment by Webklex** [comment]
Hi @consigliere23 ,
yes - otherwise all php 8 features and functions can't be used.

Best regards,

**Comment by consigliere23** [comment]
What's being improved, was working just nicely on previous versions.
Yes it has some minor bugs (at least for which things I am using it) but in general all fine.
Just a thought if its it really must.
It's pain in the ass now to update PHP version on my machines :/

**Comment by CReimer** [comment]
PHP 8.0.27 is the oldest still upstream supported PHP version.


@Webklex : For him bitching about it you should actually increase the minimal version to 8.2.1. Just for the fun of it.

**Comment by consigliere23** [comment]
@CReimer 💩
