### ISSUE TITLE
incorrect number of attachments - duplicate attachment IDs

### ISSUE THREAD

**Issue by jirifalis** [Webklex/php-imap#364]
**Describe the bug**
When i am fetching attachments, i am not getting all of them. It is because function fetch() in class Webklex\PHPIMAP\Attachment is generating "random" id, but its not random and i am getting multiple attachments with same id.  Every time i try it i get different number of attachments. Tested on email with 22 attachments and throu this function i get 14-17.

When i change line 205
`            $this->id = hash("sha256", (string)microtime(true));`
To 
`            $this->id = hash("sha256", (string)random_bytes(20));`

Its working correctly.

**Desktop / Server (please complete the following information):**
- OS: tested on centos and windows
- PHP: 8.1.10
- Version: tested on 4.1.2 and 5.0.0
- Provider: outlook/office365

**Comment by Guite** [comment]
Already fixed :-)

https://github.com/Webklex/php-imap/commit/3facf95fe88134bc27db672ba6a7dbf1f8b35d05

**Comment by jirifalis** [comment]
That's great, thank you! :)
