### ISSUE TITLE
Error in retrieving the number of emails when the inbox is empty

### ISSUE THREAD

**Issue by Paolo-24** [Webklex/php-imap#365]
When we use this call:

 **$folder->messages()->all()->count()**

all works fine if we have email messages on the server,

but when the box is empty the following errore occurs:

**Fatal error: Uncaught Webklex\PHPIMAP\Exceptions\ResponseException: Command failed to process:
Causes:
	- Empty response**

The function should return 0 if the inbox has no email.

**Comment by vagkaefer** [comment]
This is probably related with the issue #362

**Comment by Webklex** [comment]
Hi @Paolo-24 ,
many thanks for your report. This issue has been solved by https://github.com/Webklex/php-imap/commit/4a6228fbcbe236f7d4feb1015a742d046bfc5ac0

Please update to the latest release and try again.

Best regards,
