### ISSUE TITLE
IMAP Inbox folder name not taken when localized

### ISSUE THREAD

**Issue by Echecivuole** [Webklex/php-imap#368]
**Describe the bug**
Some email providers provide the Inbox folder with translated/localized name. Gmail for example provides the folder as "Posta in arrivo". In this case so the library is not able to take the real Inbox folder. 

Is there any solution into this package to auto-detect the inbox folder? A solution Ould make this library really universal!

- PHP: 7
- Version v2.4.0
- Provider: Gmail, Aruba.it

**Comment by eduardom456** [comment]
Using

`$folders = $client->getFolders();`

It will have the relation of all the e-mail folders.

Locate the desired folder and open it with the command:

$folder = $client->getFolder('FOLDER_NAME');

**Comment by Webklex** [comment]
Hi @Echecivuole ,
v2.4 is really old. I highly recommend to update - if somehow possible to >= v5.x

I'm not sure what you are looking for, if you are looking for the "default" folder - its always `INBOX` (unless your mail provider is doing something funky). Folders or Mailboxes don't have an ID or code - if you want to identify a folder, I suggest you use the folder path `$folder->path` or full name `$folder->full_name`.

I hope this helps :)

Best regards & happy coding,
