### ISSUE TITLE
microsoft 365 imap 

### ISSUE THREAD

**Issue by FatimaAlsabry** [Webklex/php-imap#369]
I am using laravel Webklex\PHPIMAP, I have connect the project to outlook.microsofrt365 and it was working well without errors,
since two days the project stop working and give me "connection setup failed" error. The management told me that microsoft stopped working with IMAP. 

What are the alternatives  to reconnect microsofrt365 email to php-imap.
 Thank you.

**Comment by eduardom456** [comment]
In my current project, I'm connecting to Office 365 IMAP, it's working normally.

Around here, it presented the mentioned error when using an "expired token".

Attempts to redo the request/permission by generating an updated token for the email.

**Comment by ditug** [comment]
You have to use oauth2 für authentifikation to outlook.microsoft365: https://www.php-imap.com/examples/oauth https://github.com/PHPMailer/PHPMailer/wiki/Microsoft-Azure-and-XOAUTH2-setup-guide

**Comment by FatimaAlsabry** [comment]
I have used oauth2 and the response is succesfull but the IMAP "connection setup failed"

**Comment by Dhavalptel** [comment]
I'm getting the same issue @FatimaAlsabry Did you get any solution to this?

**Comment by FatimaAlsabry** [comment]
I have tried many ways but it doesn't work. Then I'v solved it by using microsoft graph api and it works good.

**Comment by FatimaAlsabry** [comment]
> 



> > I have tried many ways but it doesn't work. Then I'v solved it by using microsoft graph api and it works good.
> > @FatimaAlsabry
> > If you can add your sample code here that would be awesome.

- Register app in azure active directory open all mail.read /write permission (User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All).
- use package composer require microsoft/microsoft-graph
-  the code to get access token:
 {
 $guzzle = new Client();
        $url = 'https://login.microsoftonline.com/' . $TenantID . '/oauth2/token?api-version=1.0';
        $token = json_decode($guzzle->get($url, [
            'form_params' => [
                'client_id' => $AppID,
                'client_secret' => $SecretID,
                'grant_type' => 'client_credentials',
                'resource' => 'https://graph.microsoft.com/',
            ],
        ])->getBody()->getContents());
        $accessToken = $token->access_token;
        return $accessToken;
}
- to get unread messages:
-{
        try{
                    $graph = new Graph();
                    $graph->setAccessToken($accessToken);
                    $messages = $graph->createRequest("GET", "/users/youremail@dd.com/mailFolders/Inbox/messages/?\$filter=isRead+ne+true")
                                ->setReturnType(Model\Message::class)
                                ->addHeaders(array("Content-Type" => "application/json"))
                                ->execute();
        } catch (Exception $e) {
            dd($e);
        }
        return $messages;
- you can get more details in graph api Documentayion.

**Comment by Dhavalptel** [comment]
@FatimaAlsabry I've resolved it by adding the below scope to obtain access token.
```
https://outlook.office.com/.default
```
