### ISSUE TITLE
Getting all messages occasionally hangs indefinitely

### ISSUE THREAD

**Issue by Rob-NY** [Webklex/php-imap#371]
**Describe the bug**

1:  $inbox = $client->getFolderByName('INBOX');
2:  $messages = $inbox->messages()->all()->get();

Unpredictably, line #2 will hang indefinitely.

**Used config**
Defaults

**Code to Reproduce**

```
1:  $inbox = $client->getFolderByName('INBOX');
2:  $messages = $inbox->messages()->all()->get();

```
**Expected behavior**

There should be some type of exception thrown or return value indicating timeout.

**Screenshots**
n/a

**Desktop / Server (please complete the following information):**

Unbuntu 18.04LTS
PHP 7.2.24

**Additional context**

**Comment by Webklex** [comment]
Hi @Rob-NY ,
please update to the latest release and give it another try. There have been several fixes including one fixing the issue you're describing.

Once again, thanks for taking the time and effort to make this library better!

Best regards and happy coding,
