### ISSUE TITLE
ImapProtocol hangs after writing due to incorrectly processing fwrite result

### ISSUE THREAD

**Issue by victorr99** [Webklex/php-imap#373]
**Describe the bug**
The `ImapProtocol` class calls PHP's `fwrite` function. As this function is called on a stream resource, the caller must check the number of bytes which has been written, as they may be less than the number of bytes provided to the function.

I've had a few occasions where write calls stalled as it couldn't write all the bytes. As result, it was just endless waiting for a response until PHP terminated due to the max execution time.

**Expected behaviour**
The `fwrite` call is handled correctly and retried when necessary. 

**Desktop / Server (please complete the following information):**
- OS: Linux (I don't know which distro)
- PHP: 8.1.2
- Version: v4.1.2 (and also in v5.0.0)
- Provider: Outlook

**Additional context**
I'm currently applying a workaround for this issue by 'overwriting' the fwrite function in the `Webflex\PHPIMAP\Connection\Protocols` namespace.

The code below is based on some comments in the [fwrite documentation](https://www.php.net/manual/en/function.fwrite.php#125731).

```php
namespace Webklex\PHPIMAP\Connection\Protocols {
    use RuntimeException;
    use function fwrite as fwrite_native;

    function fwrite($stream, string $data, ?int $length = null) {
        $RETRY_LIMIT = 3;

        if ($length !== null) {
            $data = substr($data, $length);
        }

        $originalLength = strlen($data);

        if ($originalLength == 0) {
            return 0;
        }

        $written = 0;
        $length  = $originalLength;
        $retries = 0;

        while (true) {
            $freshlyWritten = fwrite_native($stream, $data);

            if ($freshlyWritten === false) {
                return false;
            }

            if ($freshlyWritten == $length) {
                return $written;
            }

            if ($freshlyWritten <= 0) {
                if ($retries++ >= $RETRY_LIMIT) {
                    throw new RuntimeException("could only write $written/$originalLength bytes! (written: $freshlyWritten)");
                }
            }
            else {
                $written += $freshlyWritten;
                $data = substr($data, $freshlyWritten);

                $length -= $freshlyWritten;
            }
        }
    }
}
```

**Comment by Webklex** [comment]
Hi @victorr99 ,
many thanks for your report. Please update to v5.1 and give it another try.

Best regards,
