### ISSUE TITLE
FETCH RFC822.SIZE

### ISSUE THREAD

**Issue by didi1357** [Webklex/php-imap#378]
**Is your feature request related to a problem? Please describe.**
It would be handy to have the size of a message calculated by the IMAP server and available without having to download the whole mail.

Most IMAP servers implement
`FETCH NNN RFC822.SIZE`
where NNN is the message number/uid shown in this [stackoverflow article](https://stackoverflow.com/questions/8023723/imap-command-to-get-size-of-message).

I think this is the way to go for getting this information.

**Describe the solution you'd like**
To retrieve this information, we can ask for it using the IMAP command directly or parse the result from `imap_fetch_overview()` depending on which protocol implementation is used.

**Describe alternatives you've considered**
Some dirty hack with fetching the whole message and calculating it on my own. But this doesn't scale.

**Additional context**
Relates to Issue #278 
[Pull request](https://github.com/Webklex/php-imap/pull/379)

**Comment by Webklex** [comment]
Hi @didi1357 ,
thanks again for your pr. Live Mailbox testing is now supported as well - thanks for giving me the final push :)

**Comment by didi1357** [comment]
Wow, that was fast. Congratulations, and thanks for the collaboration :handshake:
