### ISSUE TITLE
Does not work when a folder name contains umlauts: Entwürfe

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/php-imap#383]
Previous version of this library (`laravel-imap`) was throwing "Mailbox name is not valid mUTF-7" error. 
Current `php-imap` library simply returns an empty folder:
```
$folder = $client->getFolderByPath('INBOX.Entwürfe');
```

In our fork of `laravel-imap` we've fixed it using `imap_utf8_to_mutf7()` function:
https://github.com/freescout-helpdesk/freescout/issues/2793#issue-1608519028

**Comment by Webklex** [comment]
Fixed as of v5.1. Thanks @freescout-helpdesk for the report.
