### ISSUE TITLE
all thing done, but show me a error message.

### ISSUE THREAD

**Issue by hhniao** [Webklex/php-imap#387]
my code: 

    
    try {
          $cm     = new ClientManager(config('imap'));
          $client = $cm->account('m163');
          $client->connect();
          $folders = $client->getFolders();
          foreach ($folders as $folder) {
              $messages = $folder->search()->setFetchBody(false)->all()->paginate(15);
              /** @var Message $message */
              foreach ($messages as $message) {
                     $model = new Message();
                     $model->subject = $message->subject->toString();
                     $model->save();
              }
          }
          $client->disconnect();
      } catch (Exception $e) {
          dump('exception');
    }
        echo 'done'

<< * 0 EXISTS
<< * 0 RECENT
<< * OK [UIDVALIDITY 1166860708] UIDs valid
<< * FLAGS (\Answered \Seen \Deleted \Draft \Flagged)
<< * OK [PERMANENTFLAGS (\Answered \Seen \Deleted \Draft \Flagged)] Limited
<< TAG43 OK [READ-WRITE] SELECT completed
>> TAG44 UID SEARCH ALL

<< * SEARCH
<< TAG44 OK SEARCH completed
>> TAG45 LOGOUT

<< * BYE IMAP4rev1 Server logging out
<< TAG45 OK LOGOUT completed
done
PHP Fatal error:  Uncaught ErrorException: Unknown: Unterminated mailbox: Waltraud@UNKNOWN (errflg=3) in Unknown:0
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Unknown: Unterm...', 'Unknown', 0)
#1 {main}
  thrown in Unknown on line 0

**Comment by Webklex** [comment]
Hi @hhniao ,
many thanks for your report. Please take look at the issue template available [here](https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md) and try to provide as much information as possible. 

It is much harder to debug an issue without a way to reproduce it or to compare it to similar issues.
Please provide at least the entire callstack and an anonymized version of the troubling email.

If you like to take it a step further, please feel welcome to add a new test like https://github.com/Webklex/php-imap/blob/5.1.0/tests/issues/Issue275Test.php to demonstrate the issue.

Best regards & happy coding,
