### ISSUE TITLE
Incorrect parsing of Boundary

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [Webklex/php-imap#39]
Structure::getBoundary uses incorrect regex.
`$boundary = $this->header->find("/boundary\=\"?(.*)\"?/");`

I have a header which contains:

```
Content-Type: multipart/related;
	boundary="_004_DBAPR05MB6871D506604AD447C496F0EBE4140DBAPR05MB6871eurp_";
	type="multipart/alternative"
```

And the boundary gets parsed as: _004_DBAPR05MB6871D506604AD447C496F0EBE4140DBAPR05MB6871eurp_";

If you change the regex to: `/boundary=\"?(.*)\"/"` , it is parsed correctly, and you don't need the str_replace afterwards.

This will fix a problem where there is an inline image, and it doesn't get parsed as an attachment. (And maybe some other problems too)

**Comment by AntonioDiPassio-AppSys** [comment]
After some thought, I feel the regex should be: `/boundary="?([^"]*)"?/`
So in PHP this would be: `$boundary = $this->header->find("/boundary=\"?([^\"]*)\"?/");`

**Comment by Webklex** [comment]
Hi @AntonioDiPassio-AppSys ,
thanks for your report. I looks like this might also solve https://github.com/Webklex/php-imap/issues/36 ? :)

Best regards,

**Comment by AntonioDiPassio-AppSys** [comment]
@Webklex , yes looks like it would.

**Comment by Webklex** [comment]
Hi @AntonioDiPassio-AppSys   ,
thanks again for your report :+1: 

Please update your `php-imap` dependency to v2.2.5.

Best regards,
