### ISSUE TITLE
Cant search within body with uppercase or special characters on office 365 and outlook.

### ISSUE THREAD

**Issue by SuryaJD** [Webklex/php-imap#391]
**Describe the bug**
I am Using this Package to search within My office365 email content. Search team is Alphanumeric with special characters ex: 'rqI7#lGn'.
If I call body('rqI7#lGn') on inbox folder returns no result. but I have noticed that if I search Lowercase word or convert the search team to lower case before searching, it works. it means only lowercase words can be searched. it can't search words with uppercase and Special characters.

**Used config**
Using same default configuration

**Code to Reproduce**
The troubling code section which produces the reported bug.
```php
        $inbox->query(null)->body('rqI7%') 
            ->get()->each(function($mail){
                echo "<li>";
                echo $mail->getSubject();
                echo "</li>";
            });
```

**Expected behavior**
When searching within email body I should get the collection of all emails containing above search term. But It's returning Blank collection.

**Desktop / Server (please complete the following information):**
- OS: AWS linux
- PHP: [7.4.3]
- Version [2.7.2]
- Provider [office 365 and outlook]

**Additional context**
I tried the same on my local machine with php 8.1 and windows 11. faced the same issue.
I also tried to convert text using utf8_encode() but still no luck.

**Comment by Bartheyrman22** [comment]
Spaces are also not possible to search on.
