### ISSUE TITLE
Create subfolders throws Webklex\PHPIMAP\Exceptions\ImapServerErrorException

### ISSUE THREAD

**Issue by fransweerts** [Webklex/php-imap#394]
Hello,

I'm using your imapserver docker (.github/docker) for my own unit tests. Its working fine, I can connect to the imap server.

I have created an unit test which creates a folder with a subfolder.

         $clientConfig = [
                        'host' => '127.0.0.1',
                        'port' => 993,
                        'encryption' => 'ssl',
                        'validate_cert' => false,
                        'username' => 'root@example.local',
                        'password' => 'foobar',
                        'protocol' => 'imap',
                        'timeout' => 20,
          ];
         $clientManager = new ClientManager();

         // Create a new client
         $client = $clientManager->make($clientConfig);

        // Create folder with subfolder
        $client->createFolder('test');
        $client->createFolder('test/subfolder');

After the 'test' folder has been succesfully created, it will try to create a subfolder. But then it throws an Webklex\PHPIMAP\Exceptions\ImapServerErrorException.

I can not see anymore information in the debugger/logfiles. Is it a bug in the createFolder method?

**Comment by Webklex** [comment]
Hi @fransweerts ,
please enable the debug mode in your local `phpunit.xml`: https://github.com/Webklex/php-imap/blob/master/phpunit.xml.dist#L26

My guts are telling me that you are trying to create a folder that already exist - but I could be wrong :)

Best regards & happy coding,

**Comment by fransweerts** [comment]
Ok, now i can see the 'real' error:    "Mailbox doesn't allow inferior mailboxes"
It looks like a dovecot imap server issue?

See the debug output:
>> TAG9 CREATE "test"
<< TAG9 OK Create completed (0.001 + 0.000 secs).
>> TAG10 EXPUNGE

<< TAG10 OK Expunge completed (0.001 + 0.000 secs).
>> TAG11 LIST "" "*"

<< * LIST (\NoInferiors) "/" test
<< * LIST (\HasNoChildren) "/" INBOX
<< TAG11 OK List completed (0.001 + 0.000 secs).
>> TAG12 CREATE "test/subfolder"

<< TAG12 NO [CANNOT] Mailbox doesn't allow inferior mailboxes (0.001 + 0.000 secs).

**Comment by Webklex** [comment]
You're correct. My apologies :)

Try to place the test folder inside the `INBOX` that should work as expected with dovecot.

For example:
```php
$delimiter = $clientManager->get("options.delimiter");

$client->createFolder(implode($delimiter, ['INBOX', 'test']));
$client->createFolder(implode($delimiter, ['INBOX', 'test', 'subfolder']));
```

Depending on what you are testing, checkout the `LiveMailboxTestCase::class`. It provides several "helper" methods :)

Best regards,

**Comment by fransweerts** [comment]
Yes, it works when I use the INBOX as parent folder.

But... I clean up the created folder after the unit tests, so it can not interfere with other unit tests. The delete call throws an exception. 
$folder->delete();  

See debug logging: 

<< * LIST (\NoInferiors) "/" INBOX/subfolder
<< * LIST (\HasChildren) "/" INBOX
<< TAG4 OK List completed (0.001 + 0.000 secs).
>> TAG5 DELETE "INBOX/subfolder"
<< TAG5 OK Delete completed (0.002 + 0.000 + 0.001 secs).
>> TAG6 EXPUNGE
<< TAG6 BAD No mailbox selected (0.001 + 0.000 secs).


After setting the $expunge param to false, the error is gone, and the folder has been removed succesfully.
$folder->delete(false);

is this a good sollution or does the expunge param have side effects or disadvantages?

**Comment by Webklex** [comment]
Hi @fransweerts ,
yes it's intended functionality - however it's usefulness is certainly up to debate. You are using it correctly - you can always call expunge manually in case you have to expunge later on.

If you would like to change this, please open a new issue since it would be a breaking change :) 
However I would gladly accept and merge such a pull request, if no one comes around the corner with a good argument to keep it as it is.

Best regards &  happy testing,
