### ISSUE TITLE
Hangs sometimes forever

### ISSUE THREAD

**Issue by dariobednarski** [Webklex/php-imap#396]
**Describe the bug**\
Sometimes my PHP process hangs forever and consumes 100% CPU of one core. I have debugged it with log messages and can therefore say that a command with this library is causing the issue:
1. couldn't get the folder
```php
$client->connect();
$this->logger->debug("[$runId] client connected");
$folder = $client->getFolder($this->config['imap_folder_source']);
$this->logger->debug("[$runId] got folder");
$messages = $folder->query()->from('email@address.tld')->limit($limit)->get();
$this->logger->debug("[$runId] got messages");
$this->logger->debug("[$runId] messages count {$messages->count()}");
```
"[$runId] client connected" was written to the logs.\
"[$runId] got folder" wasn't.

2. couldn't move
```php
$this->sendEmail();
$this->logger->debug("[$runId] email sent");
$message->move($this->config['imap_folder_target']);
$this->logger->debug("[$runId] mail moved");
```
"[$runId] email sent" was written to the logs.\
"[$runId] mail moved" wasn't.

**Used config**
```php
[
'host'          => $this->config['imap_hostname'],
'port'          => 993,
'encryption'    => 'ssl',
'validate_cert' => true,
'username'      => $this->config['imap_user'],
'password'      => $this->microsoftApplication->getLastAccessToken(),
'protocol'      => 'imap',
'authentication' => "oauth",
'timeout'       => 5
]
```

**Code to Reproduce**
The troubling code section which produces the reported bug.
see above

**Expected behavior**
I would at least expect an Exception thrown after "timeout" seconds.

**Screenshots**
no screenshots

**Desktop / Server (please complete the following information):**
- OS: Debian GNU/Linux 10 (buster)
- PHP: 7.4
- Version 4.1.2
- Provider Office365

**Additional context**
no additional context needed

**Comment by Webklex** [comment]
Hi @dariobednarski ,
many thanks for your detailed report. This issue should have been fixed by v5 - please update to the latest release and try again. 

If you are still facing the same issue, please enable the debug mode inside your config. Perhaps this can help to locate the issue :)

Best regards & happy coding,
