### ISSUE TITLE
Insane dependencies

### ISSUE THREAD

**Issue by michalkkkd** [Webklex/php-imap#399]
**Describe the bug**
I just deployed the repository, and I was stunned, by the number of external dependencies:
**Actual size of Webklex / php-imap**
63 files in 9 directories
**Count for everything needed by composer**
1969 files in 202 directories in total, after running composer

If these dependencies were used extensively, ok, but I found, that Webklex / php-imap references these:
use Carbon\Carbon; -> used for date handling
use Illuminate\Support\Str; -> used for 2 functions: snake & camel
use Illuminate\Support\Collection;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;

**Expected behavior**
Limit external dependencies. 

**Desktop / Server (please complete the following information):**
- all

**Comment by Webklex** [comment]
Hi @michalkkkd ,
many thanks for your report. Please feel welcome to fork this repository and converting it into something much smaller. I happily link to it in the project readme for anyone looking for an alternative without dependencies.

Best regards & happy coding,
