### ISSUE TITLE
Subject with colon ";" is truncated

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/php-imap#401]
**Describe the bug**

An email with the subject **1;00pm Client running few minutes late** is imported with the following subject: **1**

Originally reported in https://github.com/freescout-helpdesk/freescout/issues/2964

**Desktop / Server (please complete the following information):**

OS: Debian GNU/Linux 10
PHP: 8.2
Version 4.1.1
Provider: Office365

**Comment by freescout-helpdesk** [comment]
This happens only with Webklex/php-imap and does not happen with previous Webklex/laravel-imap library.

**Comment by freescout-helpdesk** [comment]
This can be fixed by changing

https://github.com/Webklex/php-imap/blob/6ea5a94f2f8936ac5c2c40a46fbbd88f2bdeb16b/src/Header.php#L613

to:

```
    if (($key == "user_agent") === false && ($key == "subject") === false) {
```

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,

Thanks a lot for reporting this issue. I really appreciate it! I was able to reproduce the issue and just pushed a fix.

Once again, thanks for taking the time and effort to make this library better! If you have any more questions or need further assistance, feel free to let me know.

Best regards and happy coding!

**Comment by freescout-helpdesk** [comment]
Thanks for all your work.
