### ISSUE TITLE
Throwing exceptions without descriptions

### ISSUE THREAD

**Issue by TonyMarston** [Webklex/php-imap#408]
**Is your feature request related to a problem? Please describe.**
After connecting to a mailbox and then attempting to call $client->getFolder('INBOX') I get the following error:
Uncaught exception from Webklex\PHPIMAP\Exceptions\ImapServerErrorException in vendor\webklex\php-imap\src\Connection\Protocols\ImapProtocol.php, line=306. I stopped at than line with my debugger to see the contents of $tokens contained the message "BAD User is authenticated but not connected." This is FAR more meaningful than simply the name of the exception.

**Describe the solution you'd like**
I consider it to be bad form to throw an exception without an error description. Please include proper descriptions when throwing errors as I HATE having to debug somebody else's code.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Webklex** [comment]
Hi @TonyMarston ,
many thanks for your report and suggestion. Please feel welcome to fix what ever bothers you and invited to share it with others via pull requests. 
That's the great power of open source :)

Best regards and happy coding,
