### ISSUE TITLE
Reading mail on Office365 accounts using FT_PEEK marking all messages as read

### ISSUE THREAD

**Issue by james-apex27** [Webklex/php-imap#409]
Hi Folks,

General question about an issue we are seeing with some of our customers. A little background, we are using the library with our SaaS CRM product.

Some of the functionality we offer includes connecting to the customer's email server and importing any emails that are linked to contacts stored inside our SaaS.

When we do this, we don't want to mark any of those imported emails as read, as we're only storing the emails for archival and audit purposes.

For some (not all) of our customers who use the hosted Office365 email from Microsoft, we are having a problem.

When fetching emails using the FT_PEEK option, it would seem that Office365 is marking those emails as read.

Like I said, this isn't for all customers, and I cannot reproduce this problem with our own Office365 account, so I thought I would ask if anyone else has seen such a problem and or has any ideas?

Many thanks.

James.

**Comment by mpryvkin** [comment]
Are you using `leaveUnread()` method when querying a folder?

**Comment by james-apex27** [comment]
Hi Michael,

Appreciate your help, yes, we're doing that.

$messages = $folder->messages()->since($dts_since)->leaveUnread()->get();

The reason I put this as a general query rather than a bug is that I don't believe it's an issue with the library, more the combination of the library with Office365 and our use case, I was hoping someone else might've come across this before.

I do thank you for responding though.

**Comment by mpryvkin** [comment]
I am using php-imap v4.1.0 with `fetch` option set to `IMAP::FT_PEEK` while accessing Office365 mailbox via IMAP and it works as expected when using `leaveUnread()`.

**Comment by james-apex27** [comment]
Same here. I think we're going to have to chalk this one up as unsolvable at the moment. Once again, appreciate the response, have a nice day.

**Comment by Webklex** [comment]
Hi @james-apex27 ,
many thanks for posting this question here. It's indeed the first time I've heard this and it sounds really interesting. Should you be able to figure out a reason, please consider sharing it :)

Best regards and happy coding,

**Comment by fresent** [comment]
@james-apex27 how were you able to resolve this (as this has been closed).
For some weird reason we are seeing this exact behaviour on some of the office 365 mailboxes.

**Comment by james-apex27** [comment]
@fresent We didn't resolve it, instead we switched to using an MS Graph integration, we've not had the problem since.
