### ISSUE TITLE
$message->getSize() throws an exception

### ISSUE THREAD

**Issue by TonyMarston** [Webklex/php-imap#411]
**Describe the bug**
A call to $message->getSize() fails with:

Uncaught exception: Cannot use object of type stdClass as array, code=0, file=F:\Apache2\HTDOCS\GMX-Transix\includes\vendor\webklex\php-imap\src\Connection\Protocols\LegacyProtocol.php, line=339 

**Used config**

**Code to Reproduce**
The troubling code section which produces the reported bug.
```php
$size = $message->getSize();
```

**Expected behavior**
I expect it to return the size of the message body.

**Screenshots**

**Desktop / Server (please complete the following information):**
- OS: Windows 10
- PHP: 8.2.5
- Version 5.2
- Provider Office365

**Additional context**

**Comment by Webklex** [comment]
Hi @TonyMarston,
many thanks for your report. I was able to reproduce the issue and pushed a fix.

If you have any more questions or need further assistance, feel free to let me know.

Best regards and happy coding!
