### ISSUE TITLE
I can not imap to business email or company email eg (myname@company.country)

### ISSUE THREAD

**Issue by ssekimuli** [Webklex/php-imap#415]
**Describe the bug**
i have tried to imap my company email was given under outlook but it cant connect.

```php
        $cm = new ClientManager($options = []);
        $client = $cm->account('account_identifier');

        // or create a new instance manually
        $client = $cm->make([
           //eg
            'username'      => 'noreply@company.ug',
            'password'      => 'password',
            'host' => 'outlook.office365.com',
            'port' => 993,
            'protocol' => 'imap',
        ]);
     

        //Connect to the IMAP Server
        $client->connect();
        $message = [];
        $aFolder = $client->getFolders();
        return [$aFolder];
```
ERROR
Webklex\PHPIMAP\Exceptions\ImapServerErrorException:  in file /Users/Invullen/Desktop/mmeta/Metadent-Backend-v2/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php on line 306

**Comment by Webklex** [comment]
Hi @ssekimuli ,
you have to use oAuth in order to connect to an outlook.office365.com imap account. Here are some resources:
- https://github.com/Webklex/php-imap/issues/369
- https://github.com/PHPMailer/PHPMailer/wiki/Microsoft-Azure-and-XOAUTH2-setup-guide
- https://www.php-imap.com/examples/oauth

Best regards & happy coding,

**Comment by ssekimuli** [comment]
thank @Webklex , you mean my company email will start to work (andrew@companyA.nl)

**Comment by tiamatloc** [comment]
> thank @Webklex , you mean my company email will start to work ([andrew@companyA.nl](mailto:andrew@companyA.nl))

You cannot use a plain email address and password anymore with Office accounts, Microsoft have disabled this. What you have to do is create an App Registration in Azure, register the Enterprise Application as a Service Principle using Powershell and then use Powershell to map the service principle to the mailbox(es) you are trying to access. Then you use those details to request tokens you can use to connect to the mailbox. These are 2 guides that helped me solve the issue with my company 365 email accounts.

https://vielhuber.de/en/blog/access-with-php-to-exchange-office-365/
https://www.limilabs.com/blog/oauth2-client-credential-flow-office365-exchange-imap-pop3-smtp
