### ISSUE TITLE
Custom Flag

### ISSUE THREAD

**Issue by lsbescorpion** [Webklex/php-imap#43]
How do I assign a custom flag to a message?

**Comment by Webklex** [comment]
Hi @lsbescorpion ,
you can set a custom flag by calling `Message::setFlag($flag="MY_FLAG")`.

```php
/** @var \Webklex\PHPIMAP\Message $message */
$bool = $message->setFlag("MY_FLAG");
```

However your mail provider may not support custom flags.

Best regards,
