### ISSUE TITLE
Allow for larger attachments

### ISSUE THREAD

**Issue by allestuetsmerweh** [Webklex/php-imap#433]
**Is your feature request related to a problem? Please describe.**
I have written an email forwarder, which reads the incoming messages from a catch-all mailbox using `php-imap`. I am generally very happy with it, but when people send email with large attachments, I see errors like these:
`[...] Uncaught Exception Symfony\Component\ErrorHandler\Error\OutOfMemoryError: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 9282368 bytes)" at [...]/vendor/webklex/php-imap/src/Part.php line 196`

**Describe the solution you'd like**
It would be nice, if `php-imap` would not load the whole `Part` content to memory, but instead, e.g. write the raw message to a temp file, and only reference parts by offset within that file (or similar)

**Describe alternatives you've considered**
None so far, but I am very open to other solutions, to the problem!

**Additional context**
I would like to contribute a PR, once we know how to solve the problem.

**Comment by tiamatloc** [comment]
@allestuetsmerweh PHP is running out of RAM. Increase `memory_limit` in your PHP.ini and it should fix it.

**Comment by kasoft** [comment]
I have a similiar problem with e-mails that provoke a memory problem. i don't know if it's possible to 'not load' attachements when you just want to load the mail content. in my case the memory limit is 128MB per Script which seems not enough for a 8 MB File in an attachement (that i do not want to load, but which is always load in memory when you loop/check the attachement). Maybe there is a way to prevent this? At the moment i use this chain

```
$message = $folder->query()->getMessageByUid($this->uid);
$html = $message->getHTMLBody();
if($message->hasAttachments()) {
            foreach ($message->getAttachments() as $akey => $attachment) {
                      $attributes = $attachment->getAttributes();
                      //do soemthing with filename and size, nothing with save oder content
            }
}
```

Memory Current: 37.4 MB MB // 39213912 Bytes
Memory Peak true: 96.3 MB MB // 100937728 Bytes
Memory Peak: 82.1 MB MB // 86113200 Bytes

**Comment by freescout-help** [comment]
The main reason of this issue are `substr()` and `exlode()` functions which are applied to the email content. The thing is that PHP has to allocate extra memory to perform those operations:

![2024-08-14_14-58-51](https://github.com/user-attachments/assets/32631fff-b9a4-446b-9ad1-eda149b9f838)
https://github.com/Webklex/php-imap/blob/master/src/Structure.php#L135

![2024-08-14_14-58-51](https://github.com/user-attachments/assets/bcff16d3-7533-4cec-a8b7-5486fc269308)
https://github.com/Webklex/php-imap/blob/master/src/Structure.php#L108

Here is an attempt to get rid of `explode()` function: https://github.com/freescout-help-desk/freescout/commit/be4a1234c3fa34a5910b5d5df9dbd1a5c533a6b5
It reduced memory consumption but not so much: 2-10% less (depending on email body size).
