### ISSUE TITLE
Build connect stream php imap way

### ISSUE THREAD

**Issue by blagi** [Webklex/php-imap#447]
I have a legacy mail handling subsystem in Codeigniter 2 and PHP 7.1.  I had to use Oauth2 and choose this Webklex PHP IMAP solution.
Now I have a DB configuration with server connection parameters like this: '/imap/ssl/novalidate-cert'. Because I'll use it for some old mail server and MS Outlook 365 I'd like to use same parameters. Can I use that with Webklex/php-imap instead of $clientManager make array like this
```PHP
				$client = $clientManager->make([
					...
					'encryption'    => 'ssl',
					'validate_cert' => false,
					'protocol'      => 'imap',
				]);

```

**Comment by tiamatloc** [comment]
I cannot see any reason why this would not work.

**Comment by blagi** [comment]
Thanks, but I change my DB configuration to cover both types of parameters.
