### ISSUE TITLE
Attachment name is undefined. Too long name or cyrillic?

### ISSUE THREAD

**Issue by myrzan** [Webklex/php-imap#45]
Hi!
I'm using `webklex/php-imap 2.2.0`.
Protocol: **imap**.
I want to get attachments from letters, **.zip** files are being saved properly (e.g. Astronomia0091023-2020-11-05.zip),
 but one letter has **.xlsx** file attached with name "Прокрастинация и другие методы избежать работу 2020-11-02.xlsx" and its saved like "undefined" without any extension (not even undefined.xslx).
I saw the issue #37, but it's not solving this problem. Can you help?

**Comment by myrzan** [comment]
I've tested out that if I rename same file to latin characters like **pricelist.xlsx**, php-imap can define name correctly.
I think it's because of length of original filename, but don't know where to fix that.

**Comment by Webklex** [comment]
Hi @myrzan ,
thanks for your report. Please dump the raw body and post an anonymized version of the region around it.
You can dump the raw content by calling `var_dump($message->getStructure()->raw)`. This will hopefully allow me or others to reproduce the problem and determine the problem.

Best regards,

**Comment by danbka33** [comment]
> Hi @myrzan ,
> thanks for your report. Please dump the raw body and post an anonymized version of the region around it.
> You can dump the raw content by calling `var_dump($message->getStructure()->raw)`. This will hopefully allow me or others to reproduce the problem and determine the problem.
> 
> Best regards,

I have same issue. Hope this helps solve the problem. 

For this mail I get undefined. Real file name is Остатки 4.02..xls
`--=_0b2d23d5602ca8725a5d021a1cddaeb4\r\n
Content-Transfer-Encoding: 8bit\r\n
Content-Type: text/plain; charset=UTF-8;\r\n
 format=flowed\r\n
\r\n
\r\n
\r\n
-- \r\n
НОВЫЕ МОДЕЛИ ПО ССЫЛКЕ\r\n
https://yadi.sk/d/kcFmVekKijIiPA?w=1\r\n
\r\n
С Уважением к Вам и Вашему бизнесу,\r\n
  Команда BaltGaz\r\n
\r\n
  Серебренникова Анастасия Николаевна\r\n
  Менеджер по продажам\r\n
  8-495-902-5504, доб 803\r\n
\r\n
  BaltGaz.ru\r\n
--=_0b2d23d5602ca8725a5d021a1cddaeb4\r\n
Content-Transfer-Encoding: base64\r\n
Content-Type: application/vnd.ms-excel;\r\n
 name="=?UTF-8?Q?=D0=9E=D1=81=D1=82=D0=B0=D1=82=D0=BA=D0=B8_4=2E02=2E=2Ex?=\r\n
 =?UTF-8?Q?ls?="\r\n
Content-Disposition: attachment;\r\n
 filename*=UTF-8''%D0%9E%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%B8%204.02..xls;\r\n
 size=94208\r\n
\r\n`

For this mail I get - Авангард склад 07.02.2021.xls. Everything works well here. 
`--------_29865_-1932362997_6316\r\n
Content-Type: text/plain;\r\n
\tcharset="utf-8"\r\n
Content-Transfer-Encoding: base64\r\n
\r\n
0KHQvNC+0YLRgNC40YLQtSDQstC70L7QttC10L3QuNC1Lg==\r\n
\r\n
--------_29865_-1932362997_6316\r\n
Content-Type: application/octet-stream;\r\n
\tname="=?utf-8?B?0J7RgtGH0LXRgg==?="\r\n
Content-Disposition: attachment;\r\n
\tfilename="=?utf-8?B?0JDQstCw0L3Qs9Cw0YDQtCDRgdC60LvQsNC0IDA3LjAyLjIwMjE=?=\r\n
\t=?utf-8?B?Lnhscw==?="\r\n
Content-Transfer-Encoding: base64\r\n
\r\n`
