### ISSUE TITLE
$client->getFolder('INBOX') returns null

### ISSUE THREAD

**Issue by blagi** [Webklex/php-imap#450]
I have 2 accounts on MS Outlook 365 that I'm polling for messages. For one of them getFolder('INBOX') is ok, but for another one it returns null. How can I debug that?

Part of code:
```PHP
				$client->connect();
				$folder_name = 'INBOX';
				$folder = $client->getFolder($folder_name); // @todo check if mail can be in other folders
				if (null === $folder) {
					throw new Exception(sprintf('Error getting folder %s', $folder_name));
				}
```

**Comment by tiamatloc** [comment]
Use getFolders() and then loop through the results to make sure it is actually called INBOX. If getFolders() fails, use getFolders(false).

**Comment by blagi** [comment]
Thanks, but there was no folders at all. I set a debug and got some meaningful errors:

> TAG2 LIST "" "*" 
> TAG2 BAD User is authenticated but not connected. Exception : Error getting folder INBOX

Searching for that I find a solution in this [link](https://learn.microsoft.com/en-us/answers/questions/280259/user-is-authenticated-but-not-connected)

This PowerShell command solved issue:

`Add-MailboxPermission -identity user_to_be_migrated@domain.tld -user office365_admin@domain.tld -accessrights fullaccess -inheritancetype all`
