### ISSUE TITLE
Read message from file

### ISSUE THREAD

**Issue by blagi** [Webklex/php-imap#454]
Because of legacy application and PHP 7.1 I had to use php-imap v 4.1.2. I'd like to use some new features from latest versions like read message from file and did make changes to Message.php adding fromFile & fromString methods, and in ClientManager.php adding getMask(). While trying to use it I'm getting this Fatal error:

> Uncaught Webklex\PHPIMAP\Exceptions\MaskNotFoundException: Unknown message mask provided in C:\git\austriataxi\vendor\webklex\php-imap\src\Message.php on line 326

In Message.php:

        $default_mask  = ClientManager::getMask("message");

$default-mask gets null value.

How can I set some default mask, or make somehow this to work?

**Comment by professorallman** [comment]
Through trial and error I was able to get it to work with this:
```PHP
\Webklex\PHPIMAP\ClientManager::$config = [
    'masks' => ['message' => '\Webklex\PHPIMAP\Support\Masks\MessageMask'],
    'options' => ['rfc822' => '', 'decoder' => ['message' => 'utf-8'], 'offset' => '']];
$Message = \Webklex\PHPIMAP\Message::fromFile($Filepath);
$Message->setFolderPath('');
```
Hope this helps

**Comment by blagi** [comment]
> Through trial and error I was able to get it to work with this:
 
> Hope this helps

Thanks. Currently I'm working on something other. Probably I'll use PHP Imap on new project with PHP 8.
