### ISSUE TITLE
Reorder all folders to get INBOX first

### ISSUE THREAD

**Issue by bjaverhagen** [Webklex/php-imap#458]
Hi!

Is there a way to reorder all folders to get first the INBOX folder with children and after that the other folders?
Reorder or shift with the common php array functions (usort etc.) won't work because $folders is an object and not an array.
I can't find a solution for this.

```
$folders = $client->getFolders();

foreach ( $folders as $folder ) {

     echo $folder->name;

     if ( $folder->hasChildren() ) {

          foreach ( $subfolders as $subfolder ) {

               echo $subfolder->name;

          }

     }
}
```

Thanks in advance!

**Comment by michalkortas** [comment]
Hello again!
The `getFolders()` method returns a `FolderCollection`, which extends the `Collection` class known from Laravel. This allows you to use any method supported by the `Collection` class on the result returned by this method.

To sort the results as you've specified, you can use the `sort()` method. You'll need to pass a callback implementing your custom algorithm, just like you would with a pure PHP function like `uasort()`.

```php
$client->getFolders()->sort(function($a, $b) {
    if ($a->name === 'INBOX') {
        return -1;
    } elseif ($b->name === 'INBOX') {
        return 1;
    } else {
        return strcmp($a->name, $b->name);
    }
})
```

**Comment by bjaverhagen** [comment]
Hi, thanks so much for your clear explanation. This helped me to get INBOX first!
