### ISSUE TITLE
Search orWhere

### ISSUE THREAD

**Issue by lsbescorpion** [Webklex/php-imap#46]
How can I perform an orWhere search for several fields at once, for example, from-to-subject-text

**Comment by Webklex** [comment]
Hi @lsbescorpion ,
if the "OR" operation is supported by your mail provider you can use it a few different ways:
```php
$messages = $folder->query()->subject("some subject")->orWhere()->to("some@one.tld")->orWhere(function($query){
    $query->text("some custom text")->orWhere("from@someone.com");
})->get();
```

Best regards,

**Comment by daniel89fg** [comment]
I have an error when executing the following query.

`$messages = $folder
                ->query()
                ->subject("Contacto Web")
                ->orWhere()
                ->to("messages-noreply@linkedin.com")
                ->orWhere(function($query){
                    $query->text("Fernando");
                })
                ->get();`

This is a var_dump() of the error

`object(Whoops\Exception\ErrorException)#291 (8) {
  ["message":protected]=>
  string(26) "Array to string conversion"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(2)
  ["file":protected]=>
  string(98) "/var/www/html/Plugins/MultiEmail/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php"
  ["line":protected]=>
  int(309)
  ["trace":"Exception":private]=>
  array(12) {
    [0]=>
    array(4) {
      ["function"]=>
      string(11) "handleError"
      ["class"]=>
      string(10) "Whoops\Run"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(4) {
        [0]=>
        int(2)
        [1]=>
        string(26) "Array to string conversion"
        [2]=>
        string(98) "/var/www/html/Plugins/MultiEmail/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php"
        [3]=>
        int(309)
      }
    }
    [1]=>
    array(4) {
      ["file"]=>
      string(98) "/var/www/html/Plugins/MultiEmail/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php"
      ["line"]=>
      int(309)
      ["function"]=>
      string(7) "implode"
      ["args"]=>
      array(2) {
        [0]=>
        string(1) "
"
        [1]=>
        array(10) {
          [0]=>
          string(3) "BAD"
          [1]=>
          string(5) "Error"
          [2]=>
          string(2) "in"
          [3]=>
          string(4) "IMAP"
          [4]=>
          string(7) "command"
          [5]=>
          string(3) "UID"
          [6]=>
          string(7) "SEARCH:"
          [7]=>
          string(7) "Missing"
          [8]=>
          string(8) "argument"
          [9]=>
          array(4) {
            [0]=>
            string(5) "0.001"
            [1]=>
            string(1) "+"
            [2]=>
            string(5) "0.000"
            [3]=>
            string(6) "secs)."
          }
        }
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(98) "/var/www/html/Plugins/MultiEmail/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php"
      ["line"]=>
      int(383)
      ["function"]=>
      string(12) "readResponse"
      ["class"]=>
      string(49) "Webklex\PHPIMAP\Connection\Protocols\ImapProtocol"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(3) {
        [0]=>
        object(Webklex\PHPIMAP\Connection\Protocols\Response)#290 (8) {
          ["commands":protected]=>
          array(1) {
            [0]=>
            string(97) "TAG4 UID SEARCH SUBJECT "Contacto Web" OR TO "messages-noreply@linkedin.com" OR TEXT "Fernando"
"
          }
          ["response":protected]=>
          array(1) {
            [0]=>
            string(83) "TAG4 BAD Error in IMAP command UID SEARCH: Missing argument (0.001 + 0.000 secs).
"
          }
          ["errors":protected]=>
          array(0) {
          }
          ["result":protected]=>
          NULL
          ["noun":protected]=>
          int(4)
          ["response_stack":protected]=>
          array(0) {
          }
          ["debug":protected]=>
          bool(false)
          ["can_be_empty":protected]=>
          bool(false)
        }
        [1]=>
        string(4) "TAG4"
        [2]=>
        bool(false)
      }
    }
    [3]=>
    array(6) {
      ["file"]=>
      string(98) "/var/www/html/Plugins/MultiEmail/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php"
      ["line"]=>
      int(1223)
      ["function"]=>
      string(18) "requestAndResponse"
      ["class"]=>
      string(49) "Webklex\PHPIMAP\Connection\Protocols\ImapProtocol"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        string(10) "UID SEARCH"
        [1]=>
        array(1) {
          [0]=>
          string(79) "SUBJECT "Contacto Web" OR TO "messages-noreply@linkedin.com" OR TEXT "Fernando""
        }
      }
    }
    [4]=>
    array(6) {
      ["file"]=>
      string(76) "/var/www/html/Plugins/MultiEmail/vendor/webklex/php-imap/src/Query/Query.php"
      ["line"]=>
      int(197)
      ["function"]=>
      string(6) "search"
      ["class"]=>
      string(49) "Webklex\PHPIMAP\Connection\Protocols\ImapProtocol"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        array(1) {
          [0]=>
          string(79) "SUBJECT "Contacto Web" OR TO "messages-noreply@linkedin.com" OR TEXT "Fernando""
        }
        [1]=>
        int(1)
      }
    }
    [5]=>
    array(6) {
      ["file"]=>
      string(76) "/var/www/html/Plugins/MultiEmail/vendor/webklex/php-imap/src/Query/Query.php"
      ["line"]=>
      int(378)
      ["function"]=>
      string(6) "search"
      ["class"]=>
      string(27) "Webklex\PHPIMAP\Query\Query"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [6]=>
    array(6) {
      ["file"]=>
      string(58) "/var/www/html/Plugins/MultiEmail/Controller/InboxEmail.php"
      ["line"]=>
      int(1254)
      ["function"]=>
      string(3) "get"
      ["class"]=>
      string(27) "Webklex\PHPIMAP\Query\Query"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [7]=>
    array(6) {
      ["file"]=>
      string(58) "/var/www/html/Plugins/MultiEmail/Controller/InboxEmail.php"
      ["line"]=>
      int(131)
      ["function"]=>
      string(17) "renderInboxAction"
      ["class"]=>
      string(55) "FacturaScripts\Plugins\MultiEmail\Controller\InboxEmail"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [8]=>
    array(6) {
      ["file"]=>
      string(40) "/var/www/html/Core/App/AppController.php"
      ["line"]=>
      int(187)
      ["function"]=>
      string(11) "privateCore"
      ["class"]=>
      string(55) "FacturaScripts\Plugins\MultiEmail\Controller\InboxEmail"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(3) {
        [0]=>
        object(Symfony\Component\HttpFoundation\Response)#24 (6) {
          ["headers"]=>
          object(Symfony\Component\HttpFoundation\ResponseHeaderBag)#26 (5) {
            ["computedCacheControl":protected]=>
            array(2) {
              ["no-cache"]=>
              bool(true)
              ["private"]=>
              bool(true)
            }
            ["cookies":protected]=>
            array(0) {
            }
            ["headerNames":protected]=>
            array(6) {
              ["cache-control"]=>
              string(13) "Cache-Control"
              ["date"]=>
              string(4) "Date"
              ["x-frame-options"]=>
              string(15) "X-Frame-Options"
              ["x-xss-protection"]=>
              string(16) "X-XSS-Protection"
              ["x-content-type-options"]=>
              string(22) "X-Content-Type-Options"
              ["strict-transport-security"]=>
              string(25) "Strict-Transport-Security"
            }
            ["headers":protected]=>
            array(6) {
              ["cache-control"]=>
              array(1) {
                [0]=>
                string(17) "no-cache, private"
              }
              ["date"]=>
              array(1) {
                [0]=>
                string(29) "Wed, 27 Sep 2023 08:06:57 GMT"
              }
              ["x-frame-options"]=>
              array(1) {
                [0]=>
                string(10) "SAMEORIGIN"
              }
              ["x-xss-protection"]=>
              array(1) {
                [0]=>
                string(13) "1; mode=block"
              }
              ["x-content-type-options"]=>
              array(1) {
                [0]=>
                string(7) "nosniff"
              }
              ["strict-transport-security"]=>
              array(1) {
                [0]=>
                string(16) "max-age=31536000"
              }
            }
            ["cacheControl":protected]=>
            array(0) {
            }
          }
          ["content":protected]=>
          string(0) ""
          ["version":protected]=>
          string(3) "1.0"
          ["statusCode":protected]=>
          int(200)
          ["statusText":protected]=>
          string(2) "OK"
          ["charset":protected]=>
          NULL
        }
        [1]=>
        object(FacturaScripts\Dinamic\Model\User)#143 (19) {
          ["admin"]=>
          bool(true)
          ["codagente"]=>
          NULL
          ["codalmacen"]=>
          string(3) "ALG"
          ["creationdate"]=>
          string(10) "04-07-2023"
          ["email"]=>
          string(16) "hola@danielfg.es"
          ["enabled"]=>
          bool(true)
          ["homepage"]=>
          string(9) "Dashboard"
          ["langcode"]=>
          string(5) "es_ES"
          ["lastactivity"]=>
          string(19) "27-09-2023 10:01:15"
          ["lastbrowser"]=>
          string(101) "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
          ["lastip"]=>
          string(10) "172.18.0.1"
          ["level"]=>
          int(99)
          ["logkey"]=>
          string(62) "ymFBYM7oOUzEwaeJ5XTLux8cINrGWS12f0ZqnstgV6jb4HiRKdQDP3vChk9lAp"
          ["nick"]=>
          string(5) "admin"
          ["idempresa"]=>
          int(1)
          ["newPassword"]=>
          NULL
          ["newPassword2"]=>
          NULL
          ["password"]=>
          string(60) "$2y$10$KNBpWIW948Ef0eVM.9.nfuicSImxZrVWafjDSrcAGrf4JfHQvP4Vu"
          ["allow_send_notification"]=>
          bool(true)
        }
        [2]=>
        object(FacturaScripts\Core\Base\ControllerPermissions)#248 (7) {
          ["accessMode"]=>
          int(99)
          ["allowAccess"]=>
          bool(true)
          ["allowDelete"]=>
          bool(true)
          ["allowExport"]=>
          bool(true)
          ["allowImport"]=>
          bool(true)
          ["allowUpdate"]=>
          bool(true)
          ["onlyOwnerData"]=>
          bool(false)
        }
      }
    }
    [9]=>
    array(6) {
      ["file"]=>
      string(45) "/var/www/html/Core/App/AppDebugController.php"
      ["line"]=>
      int(56)
      ["function"]=>
      string(14) "loadController"
      ["class"]=>
      string(37) "FacturaScripts\Core\App\AppController"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(10) "InboxEmail"
      }
    }
    [10]=>
    array(6) {
      ["file"]=>
      string(40) "/var/www/html/Core/App/AppController.php"
      ["line"]=>
      int(110)
      ["function"]=>
      string(14) "loadController"
      ["class"]=>
      string(42) "FacturaScripts\Core\App\AppDebugController"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(10) "InboxEmail"
      }
    }
    [11]=>
    array(6) {
      ["file"]=>
      string(23) "/var/www/html/index.php"
      ["line"]=>
      int(93)
      ["function"]=>
      string(3) "run"
      ["class"]=>
      string(37) "FacturaScripts\Core\App\AppController"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
  ["severity":protected]=>
  int(2)
}`
