### ISSUE TITLE
Changing image attachment path in mail body 

### ISSUE THREAD

**Issue by blagi** [Webklex/php-imap#460]
After reading a Message I'm saving attachments to disk. New file-path for image should rewrite original one in message body. Does php-imap have a method for this?

**Comment by tiamatloc** [comment]
Do you mean altering the original message in the inbox, or changing the path so you can display the message in HTML? I posted some code on https://github.com/Webklex/php-imap/issues/425 which may be useful to you.

**Comment by blagi** [comment]
Your code is useful because you are using php-imap classes. Thanks.
