### ISSUE TITLE
Not flagged Spam

### ISSUE THREAD

**Issue by lsbescorpion** [Webklex/php-imap#47]
Good afternoon, a question, how can I access the messages that are not marked as spam, I have tried this way but it does not return anything, and there are several emails.
$folder->search()->not_flagged('spam')->get();

I also try to assign it the spam flag and it always returns false.
$message->setFlag(['Spam']);

Also looking in the library I found this, what does it mean that it only supports those flags?
private $available_flags = ['recent', 'flagged', 'answered', 'deleted', 'seen', 'draft'];

**Comment by lsbescorpion** [comment]
I also try to assign it the spam flag and it always returns false.
$message->setFlag (['spam']);

**Comment by Webklex** [comment]
Hi @lsbescorpion ,
please use "Flagged" instead of "Spam".

The supported "flag range" is limited by design. These are the "default" flags which are supported by the official rfcs. 
You're welcome to prove me wrong :)

Best regards,
