### ISSUE TITLE
connection setup failed

### ISSUE THREAD

**Issue by consigliere23** [Webklex/php-imap#48]
Hi, 

I am trying to conenct to google:

```php
$cm = new ClientManager();
$client = $cm->make([
	'host' => 'imap.gmail.com',
	'port' => 993,
	'encryption' => 'ssl',
	'validate_cert' => TRUE,
	'username' => '****@gmail.com',
	'password' => 'PASSWORD',
	'protocol' => 'imap'
]);
$client->connect();
```

Then getting error: "connection setup failed"
What did I wrong?

Thanks

**Comment by Webklex** [comment]
Hi @consigliere23 ,
please take a look at this: https://github.com/Webklex/php-imap/wiki/Google-Mail---Gmail

Best regards,

**Comment by consigliere23** [comment]
Hi, 

thanks 👍 
What about yahoo? 
Outlook for example works...

**Comment by consigliere23** [comment]
And one thing, how about to send reply to some message? :)

**Comment by consigliere23** [comment]
I found a way, I mean it's same as for gmail :)
But can't get any spam messasages? 
Sent email, marked it as spam, but do not see flag for that email :/

**Comment by consigliere23** [comment]
Seems Yahoo! Spam/Junk is "Bulk Mail" folder....
