### ISSUE TITLE
Pagination empty on page 2+

### ISSUE THREAD

**Issue by zu007** [Webklex/php-imap#49]
```
$paginator = $f->query()->all()->paginate(10, 1);
return 10 emails
```
<img width="655" alt="Page 1" src="https://user-images.githubusercontent.com/11349938/100496127-7fcbe100-3173-11eb-98bc-08a4675c05c4.PNG">

```
$paginator = $f->query()->all()->paginate(10, 2);
on page 2 or other page .return 0 email.
```
<img width="221" alt="page 2" src="https://user-images.githubusercontent.com/11349938/100496142-a25dfa00-3173-11eb-8fcb-942c779c8e73.PNG">

**Desktop / Server :**
 - OS:Windows 10
- PHP: 7.4.7
 - Version: 2.2.0

**Comment by Webklex** [comment]
Hi @zu007   ,
thanks for your report :+1: 

Please update your `php-imap` dependency to v2.2.5.

Best regards,
