### ISSUE TITLE
Outlook connection setup failed

### ISSUE THREAD

**Issue by zu007** [Webklex/php-imap#50]
```
        $client = Client::make([
            'host' => 'outlook.office365.com',
            'port' => 993,
            'encryption' => 'ssl',
            'validate_cert' => true,
            'username' => 'xyz@outlook.com',
            'password' => 'abz',
            'protocol' => 'imap'
        ]);
```
working fine

```
   $client = Client::make([
            'host' => 'outlook.office365.com',
            'port' => 993,
            'encryption' => 'ssl',
           'validate_cert' => true,
            'username' => 'xyz@outlook.com',
            'password' => 'AccessToken',
            'protocol' => 'imap',
           'authentication' => "oauth",
        ]);
```
return connection setup failed

**Microsoft OAuth 2.0 Authorization**
```
  "accessTokenResponseBody": {
    "token_type": "Bearer",
    "scope": "User.Read openid profile IMAP.AccessAsUser.All POP.AccessAsUser.All SMTP.Send",
    "expires_in": 3600,
    "ext_expires_in": 3600,
    "access_token": "AccessToken",
    "refresh_token": "RefreshToken",
    "id_token": "IdToken"
  },
  "token": "Token",
  "refreshToken": "refreshToken",
  "expiresIn": 3600,
  "id": "11111",
  "nickname": null,
  "name": "Zubair",
  "email": "axy@outlook.com",
  "avatar": null,
  "user": {
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "displayName": "Zubair",
    "surname": "Zubair",
    "givenName": "Zubair",
    "id": "11111",
    "userPrincipalName": "xyz@outlook.com",
    "businessPhones": [
      
    ],
    "jobTitle": null,
    "mail": null,
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null
  },
  "businessPhones": [
    
  ],
  "displayName": "Zubair",
  "givenName": "Zubair",
  "jobTitle": null,
  "mail": null,
  "mobilePhone": null,
  "officeLocation": null,
  "preferredLanguage": null,
  "surname": "Zubair",
  "userPrincipalName": "xyz@outlook.com"
}
```

**Remember**:for google oauth working fine only issue with Microsoft

**Comment by Webklex** [comment]
Hi @zu007 ,
please provide a bit more context. I'm not sure what kind of problem you want to report or demonstrate.

Best regards,

**Comment by EthraZa** [comment]
@zu007 did you find the answer? I guess I'm facing the same problem. 
Gmail works but Outlook no.
It returns "**Connection setup failed**" and logs "**NOTICE: PHP message: got failure response: NO AUTHENTICATE failed.**"

**Comment by Webklex** [comment]
Hi @EthraZa ,
please take a look at this article: https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040?ui=en-US&rs=en-US&ad=US

> "You may receive a connection error if you configured your Outlook.com account as IMAP in multiple email clients. We’re working on a fix and will update this article when we have more information. For now, try the following workaround:"

1. Go to [account.live.com/activity](https://go.microsoft.com/fwlink/p/?linkid=842341) and sign in using the email address and password of the affected account.
2. Under **Recent activity** find the **Session Type** event that matches the most recent time you received the connection error and click to expand it.
3. Select **This was me** to let the system know you authorize the IMAP connection.
4. Attempt to connect to the account via your IMAP client. For more information on how to use the Recent activity page, go to [What is the recent activity page?](https://go.microsoft.com/fwlink/p/?linkid=842344)

Best regards,

**Comment by EthraZa** [comment]
Hi thank you for the answer.
In the outlook webapp I found that the IMAP info is:
**Host: outlook.office365.com
Port: 993
Method: TLS**
So, the big change here is from SSL to TLS, but now php-imap timeouts with a blank return and no logs. The activity page shows my browser logins only and looks all ok.
