### ISSUE TITLE
mb_decode_mimeheader() fails on emails with multiple references

### ISSUE THREAD

**Issue by hyperalghorithm** [Webklex/php-imap#51]
**Describe the bug**
I'm using laravel however this seems to be a php-imap issue so I will post it here. The connection used was gmail with the settings described in the wiki (app-password)

```
mb_decode_mimeheader() expects parameter 1 to be string, array given
on src/Header.php  private function decode($value)
on line 388
```

I have traced the issue back to 'References:' raw header

<img width="549" alt="unknown" src="https://user-images.githubusercontent.com/49185208/101159752-2ad61200-362e-11eb-88a4-90b95e9cb361.png">

On normal emails, there is only one reference but some emails can have a hierarchy of emails in them so it picks up multiple references. This causes the `public function rfc822_parse_headers($raw_headers) on line 171` to parse  'References:'  as an array rather than a string. 

**To Reproduce**
1. use gmail connection (app password)
2. 
 ```
 $client->connect();
        return $client->getFolders('folder name')->messages()->all()->get();
```
3. emails with multiple references will fail on mb_decode_mimeheader()

**Desktop / Server (please complete the following information):**
 - OS: macos 10.15.7 (19H2)
- PHP: 7.4.13

**Additional context**
This only happens when an email contains multiple  'References:' on a single reference the behaviour is normal with out any issues.

**Comment by lutchin** [comment]
I have the same problem.
solution to the problem:
`\vendor\webklex\php-imap\src\Header.php 145
      if (property_exists($header, 'references')) {
            !is_array($header->references)?:$header->references=$header->references[1];
            $this->attributes["references"] = $this->decode($header->references);
        }`

**Comment by Webklex** [comment]
Hi @lutchin ,
thanks for your report :+1: 

Please update your `php-imap` dependency to v2.2.5.

Best regards,
