### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by consigliere23** [Webklex/php-imap#53]
Is there any option to be used with proxy? If can, some example would be nice :)

**Comment by consigliere23** [comment]
We can use proxy now? :)

**Comment by Webklex** [comment]
Hi @consigliere23 ,
if you use the master yes - otherwise you'll have to wait for the next release :)

Best regards,

**Comment by Webklex** [comment]
Here is an usage example:
```php
/** @var \Webklex\PHPIMAP\Clientmanager $cm */
/** @var \Webklex\PHPIMAP\Client $client */
$client = $cm->make([
    'host' => 'imap.somehost.com',
    'port' => 993,
    'encryption' => 'ssl',
    'validate_cert' => true,
    'username' => 'example@somehost.com',
    'password' => 'Password',
    'protocol' => 'imap',
    'proxy' => [
        'socket' => "tcp://proxy.com:3444",
        'request_fulluri' => false,
        'username' => null,
        'password' => null,
    ]
]);

//Connect to the IMAP Server
$client->connect();
```

**Comment by consigliere23** [comment]
Thank you handsome man :) I owe you a bear :)

**Comment by consigliere23** [comment]
Hm when I try with proxy, I am getting this error:
A PHP Error was encountered

Severity:    Warning
Message:     stream_context_create(): options should have the form ["wrappername"]["optionname"] = $value
Filename:    vendor\webklex\php-imap\src\Connection\Protocols\Protocol.php
Line Number: 191

Using it like:
$client = $cm->make([
	'host' => 'imap.mail.yahoo.com',
	'port' => 993,
	'encryption' => 'ssl',
	'protocol' => 'imap',
	'validate_cert' => true,
	'proxy' => [
		'socket' => "tcp://X.X.X.X:33128",
		'request_fulluri' => false,
		'username' => null,
		'password' => null,
	],
	'username' => 'xxxxxx@yahoo.com',
	'password' => 'xxxxxx',
]);
$client->connect();

Do you know what's the issue? :/

**Comment by consigliere23** [comment]
Also, managed to get 2 folders read, but won't others:
Archive [Archive]
Bulk Mail [Bulk Mail]
and got 2x this error above :/

**Comment by Webklex** [comment]
Hi @consigliere23 ,
thanks for testing :+1: 

Unfortunately I don't have a proxy setup to play around with, so I can't really test any of this myself. While I was looking for the correct options I was wondering myself, why a proxy wrapper wasn't mentioned.

If you take a look at: 
https://github.com/Webklex/php-imap/blob/a9d60f5caf7fa33aa8e3f5479caeeb0e771d5e6b/src/Connection/Protocols/Protocol.php#L146-L174

all ssl settings are within the `ssl` "wrapper". And the proxy options are added on the root level. Perhaps they have to be wrapped inside something like `proxy`, `http`, `https` or within `ssl` itself? These options get used by the native php `stream_context_create()` function (https://www.php.net/manual/en/function.stream-context-create.php). Please try changing it to something like this:
```php
/**
 * Prepare socket options
 *
 * @return array
 */
private function defaultSocketOptions() {
    $options = [];
    if ($this->encryption != false) {
        $options["ssl"] = [
            'verify_peer_name' => $this->getCertValidation(),
            'verify_peer'      => $this->getCertValidation(),
        ];
    }

    if ($this->proxy["socket"] != null) {
        $proxy = [
            "proxy" => $this->proxy["socket"],
            "request_fulluri" => $this->proxy["request_fulluri"],
        ];

        if ($this->proxy["username"] != null) {
            $auth = base64_encode($this->proxy["username"].':'.$this->proxy["password"]);

            $proxy["header"] = [
                "Proxy-Authorization: Basic $auth"
            ];
        }

        // Please play around with this option key
        $options["http"] = $proxy;
    }

    return $options;
}
```

Why you were able to fetch a few folders is beyond my imagination.. Sry :)

Best regards,

**Comment by rigesjahgo** [comment]
Proxy is still not working, i wonder why. I've tried all means. it just ignores the proxy and connects directly. Please is there a work around to this ? I can provide a proxy for you for testing

**Comment by rigesjahgo** [comment]
I found a work around to it, the proxy is working now

**Comment by consigliere23** [comment]
> I found a work around to it, the proxy is working now

How? Can you post code here?
