### ISSUE TITLE
how can I use setFetchBody(true) in combination with leaveUnread() ? 

### ISSUE THREAD

**Issue by vesper8** [Webklex/php-imap#55]
Currently if I run something like

```
$folder
        ->query()
        ->leaveUnread()
        ->since(\Carbon\Carbon::now()->subWeeks(1))
        ->setFetchFlags(false)
        ->setFetchBody(true)
        ->get();
```

Then it will leave all messages as read. It basically ignores the leaveUnread()

If I change `setFetchBody` to false then it doesn't mark the messages as read, but then I also don't have access to the email body

I want to be able to read the body but still leave the messages as unread so that when viewed in webmail they still appear to be unread

I suppose I could loop through the messages, determine if they were previously unread, and then set the flag to unread again after consuming the email body, but I would have thought that the `leaveUnread` would be doing this by default?

Is there a better way to achieve what I am after?

I am using 2.2.5 by the way

Many thanks

**Comment by Webklex** [comment]
Hi @vesper8 ,
thanks for your report. This might be related to #33 . Strangely enough I can't replicate this behavior but @TCURT15  has a similar problem. 

Anyway please go ahead and try a few things:
1.) Set `options.fetch` inside your config from `\Webklex\PHPIMAP\IMAP::FT_UID` to `\Webklex\PHPIMAP\IMAP::FT_PEEK`.
2.) Use `Query::setFetchFlags(true)` instead of `Query::setFetchFlags(false)`

Best regards,

**Comment by reimax** [comment]
```
self::$imap = $cm->make([
                'host'  => $account_server,
                'port'  => $account_port,
                'protocol'  => 'imap', //might also use imap, [pop3 or nntp (untested)]
                'encryption'    => $account_encryption,
                'validate_cert' => true,
                'username' => $account_login,
                'password' => $account_password,
                'authentication' => null,
                'options' => [
                    'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                ],
            ]);

$email_list = $folder->query()->leaveUnread()->setFetchFlags(true)->setFetchBody(true)->since(date('d.m.Y', $time))->get();
```

and now help for me

**Comment by reimax** [comment]
I think I understand what the problem is. i wrote my settings above, but if you check

print_r(ClientManager::get('options'));

it turns out that the options section is taken only from the settings file, and not from the array that I passed

**Comment by TCURT15** [comment]
Yeah I too noticed an issue where the options I passed when calling Client::make didn't take (specifically when I was trying to set the fetch_order). However, even setting fetch to FT_PEEK in the imap config file did not fix the issue.

**Comment by Webklex** [comment]
Hi @vesper8 @reimax @TCURT15  ,
please update to the latest release [v2.3.0](https://github.com/Webklex/php-imap/releases/tag/2.3.0) and give it another try.

Feel free to reopen this issue if the issue persists.

Thanks again for your report and your testing efforts. I highly appreciate this.

**Regarding the configuration:**
Please checkout https://www.php-imap.com/configuration/configuration

It is not possible to parse these options at that point. If you want to change the config on the fly, you can try something this instead:
```php
use Webklex\PHPIMAP\ClientManager;

$cm = new ClientManager('path/to/config/imap.php');

ClientManager::$config["options"]["fetch"] = \Webklex\PHPIMAP\IMAP::FT_PEEK;
```

Best regards,
