### ISSUE TITLE
Not receiving messages on idle

### ISSUE THREAD

**Issue by sweebee** [Webklex/php-imap#57]
**Describe the bug**
When using idle, I never get a response from the mail server.

**To Reproduce**

code:

```
$client = Client::make([
            'host'          => 'imap.gmail.com',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true ,
            'username'      => 'myemail',
            'password'      => 'mypassword',
            'protocol'      => 'imap',
        ]);

        $client->connect();

        $folder = $client->getFolder("INBOX");

        $this->info('Waiting for new messages...');
         
        $folder->idle(function($message){
            $this->info('message received');
            $this->line($message->subject);
        });
```

**Expected behavior**
idle function should display new messages

**Desktop / Server (please complete the following information):**
 - OS: MacOS
- PHP: 7.3.24

**Comment by Webklex** [comment]
Hi @sweebee ,
thanks for the excellent report.

However I assume you are building a laravel command. Please note that  `$this` in `$this->line($message->subject);` is not referenced to the command class. If you want to use the command inside the closure please use something like this:
```php
$that = $this;
$folder->idle(function($message) use($that){
        $that->info('message received');
	$that->line($message->subject);
});
```

Best regards,

**Comment by sweebee** [comment]
oh wow, stupid me. But that also doesn't work.

Also tried 
```
$folder->idle(function($message) use($that){
        Log::info($message->subject);
       dump($message->subject);
});
```

but it wont do anything.

**Comment by Webklex** [comment]
Stuff happens :)

Please do the following:
1.) Login to the mail account using any other client (web, thunderbird, outlook, etc)
2.) Execute the command
3.) Send an email to the account you are monitoring
4.) Wait until the email appears on the other client
5.) Still no output? Has your message an actual subject or is it None / ""?  

Best regards,

**Comment by sweebee** [comment]
Seems something with gsuite/gmail. I've setup my mac mail client with IMAP and I don't get any mail until I restart the application. 

So IMAP server > client push doesn't work somehow.

**Comment by sweebee** [comment]
okay it did work in the client, but took some time to arrive. But I don't get anything in my PHP application.

**Comment by sweebee** [comment]
Also tried my private email using an app password but also then I don't get the message.

**Comment by Webklex** [comment]
I found the bug.

https://github.com/Webklex/php-imap/blob/bb2dd818ba00bb675127d686dd5939eab3d68144/src/Connection/Protocols/ImapProtocol.php#L948

Google does not respond with anything if you send the "DONE" command. 

Best regards,

**Comment by sweebee** [comment]
yep was checking myself:

```
$this->client->getConnection()->setConnectionTimeout($timeout);
        $this->client->reconnect();
        $this->client->openFolder($folder->path, true);
        $connection = $this->client->getConnection();
        $connection->idle();

        while (true) {
            dump(1);
            $line = $connection->nextLine();
            dump($line);
            if (($pos = strpos($line, "EXISTS")) !== false) {
                dump('received something!');
                $msgn = (int) substr($line, 2, $pos -2);
                dump($msgn);
                $connection->done();
                dump(2);
                $this->client->openFolder($folder->path, true);
                $message = $this->query()->getMessage($msgn);

                dump($message);
                $callback($message);

                $event = $folder->getEvent("message", "new");
                $event::dispatch($message);

                $connection->idle();
            }
        }
```

```dump(2)``` doesnt run.
