### ISSUE TITLE
Bug in array_merge_recursive_distinct() function.

### ISSUE THREAD

**Issue by LondonWebFactory** [Webklex/php-imap#59]
Hi

I think there might be a bug in the **array_merge_recursive_distinct()** function in **ClientManager.php**.

I get the following errors:

**Notice: Undefined index: default in /www/html/t/imap/vendor/webklex/php-imap/src/ClientManager.php on line 200**

**Warning: array_merge(): Argument #1 is not an array in /www/html/t/imap/vendor/webklex/php-imap/src/ClientManager.php on line 207**

**The array looks malformed - print_r($config) at Line 189 in ClientManager.php gives:** 

Array ( [default] => default [date_format] => d-M-Y [accounts] => Array ( [gmail] => Array ( [host] => imap.gmail.com [port] => 993 [encryption] => ssl [validate_cert] => 1 [username] => test@abc.co.uk [password] => password [authentication] => imap ) ) [options] => Array ( [delimiter] => / [fetch] => 1 [fetch_body] => 1 [fetch_flags] => 1 [message_key] => list [fetch_order] => asc [common_folders] => Array ( [root] => INBOX [junk] => INBOX/Junk [draft] => INBOX/Drafts [sent] => INBOX/Sent [trash] => INBOX/Trash ) [open] => Array ( ) [decoder] => Array ( [message] => utf-8 [attachment] => utf-8 ) ) [events] => Array ( [message] => Array ( [new] => Webklex\PHPIMAP\Events\MessageNewEvent [moved] => Webklex\PHPIMAP\Events\MessageMovedEvent [copied] => Webklex\PHPIMAP\Events\MessageCopiedEvent [deleted] => Webklex\PHPIMAP\Events\MessageDeletedEvent [restored] => Webklex\PHPIMAP\Events\MessageRestoredEvent ) [folder] => Array ( [new] => Webklex\PHPIMAP\Events\FolderNewEvent [moved] => Webklex\PHPIMAP\Events\FolderMovedEvent [deleted] => Webklex\PHPIMAP\Events\FolderDeletedEvent ) [flag] => Array ( [new] => Webklex\PHPIMAP\Events\FlagNewEvent [deleted] => Webklex\PHPIMAP\Events\FlagDeletedEvent ) ) [masks] => Array ( [message] => Webklex\PHPIMAP\Support\Masks\MessageMask [attachment] => Webklex\PHPIMAP\Support\Masks\AttachmentMask ) )

**Comment by Webklex** [comment]
Hi @LondonWebFactory ,
thanks for your report. This functionality is actually intended. You've removed the default account from your accounts array, but you are still referencing to it. You can either add a new "default" called account or change the `default` option to `gmail` since that seems to be the only available account in your case.

Best regards,

**Comment by LondonWebFactory** [comment]
Hi @Webklex 

Many thanks for the speedy reply and you were spot on. I had commented out the default connection in the config file.

Kind Regards,
Adrian

**Comment by Webklex** [comment]
Thanks, your welcome :)
