### ISSUE TITLE
incomplete values when php IMAP extension is not loaded

### ISSUE THREAD

**Issue by Polfo** [Webklex/php-imap#60]
**Describe the bug**
When the php IMAP extension is not loaded, some header fields contain unexpected values
- `getTo()` contains one address maximum
- `getCc()` contains one address maximum
- `getMessageId()` is empty
- `getInReplyTo()` is empty

**To Reproduce**
`extension=imap` disabled in `php.ini`

**Desktop / Server**
- OS: Windows 10
- PHP: 7.4.9
- "name": "webklex/laravel-imap", "version": "2.2.0"
- "name": "webklex/php-imap", "version": "2.2.5",

**Comment by Polfo** [comment]
A quick fix could be that an explicit exception is raised when IMAP extension is not loaded by default, with an option to disable this exception.

**Comment by Webklex** [comment]
Hi @Polfo ,
thanks for the followup. 

I already identified the problem. 
The method `Header::rfc822_parse_headers()` does not convert `-` into `_` which are required for the magic methods `Message::__call()` and `Header::__call()`. 

There is also inconsistent usage of  `-` and `_` - I'm fixing it right now :)

Best regards,

**Comment by Webklex** [comment]
Hi @Polfo ,
please feel free to reopen this issue if the issue persists.

Thanks again for your report and your testing efforts. I highly appreciate this.

Best regards,
