### ISSUE TITLE
Cert validation issues

### ISSUE THREAD

**Issue by TCURT15** [Webklex/php-imap#62]
Hi again.

I updated to 2.3.0 to try and test the issues I was having with it setting the read flag, and now I am having a new issue. When I have the validate_cert option set to true I cannot authenticate at all and get the following error. The cert is valid on the mail server. Tested with the same Dovecot based mail server and a Gmail account. 

```
ErrorException: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed 
```

```
Next Webklex\PHPIMAP\Exceptions\ConnectionFailedException: connection failed in vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php:77
```

**Comment by Webklex** [comment]
Hi @TCURT15 ,
thanks for your report.

Please replace "ssl" here:
https://github.com/Webklex/php-imap/blob/d74fbddfafb8e2d8d296a1b0c7352c7d2b88367a/src/Connection/Protocols/Protocol.php#L155
..with `$transport` and try again. I assume you don't use the encryption method `ssl`?

Best regards and thanks for testing,

**Comment by TCURT15** [comment]
I am using the `ssl` encryption option. I tried that and had the same result. I also dumped `$transport` to ensure it is returning `ssl`

**Comment by Webklex** [comment]
Alright, and if you comment out this section:
https://github.com/Webklex/php-imap/blob/d74fbddfafb8e2d8d296a1b0c7352c7d2b88367a/src/Connection/Protocols/Protocol.php#L155-L158
..it works?

**Comment by TCURT15** [comment]
With `validate_cert` set to `true` and that section commented out, I still am unable to connect. It is not a self signed cert. Tried the `verify_host` option as well.

**Comment by Webklex** [comment]
Then I'm not sure it is actually related to v2.3.0. I currently can't think of anything else regarding the connection setup, which could be responsible. 

Please let me know if you get any additional information.

Best regards and many thanks for testing,

**Comment by TCURT15** [comment]
Okay, thanks. Would you be able to try with a Gmail account, if you have not already?

**Comment by Webklex** [comment]
Yes, I've tested the latest release on both a Google (gmail) account and on my own debian / postfix server setup.

I can't test for Yahoo, Outlook, GMX and Web - they keep deleting my test accounts -.-

Best regards,

**Comment by TCURT15** [comment]
It seems to be working fine on my production server with the `validate_cert` option set to `true`, but not on my Mac locally. Not sure what is causing that, but we can close this issue.

**Comment by Webklex** [comment]
Hi @TCURT15 ,
thanks for the followup. You've demonstrated the potential need for additional connection options. I have to think about the integration though. 

While googling my way through that ssl error message, I also came across some reports which mentioned a missing certificates in the php-openssl extension. 

Best regards,
