### ISSUE TITLE
Problems searching for Uuid

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#63]
I don't know if I'm doing the method call wrong. I know there is a uuid 168 in my emails but I can't get it.

```
            $oClient->connect();

            $aFolder = $oClient->getFolders(false);

            $aFolder = $oClient->getFolder('INBOX');
            $aMessage = $aFolder->query(null)->getMessage(168)->limit(10)->get();
            //$aMessage = $aFolder->query()->getMessage(168)->get();
            //$aMessage = $aFolder->query(null)->since('11.10.2020')->limit(10)->get();

            foreach ($aMessage as $value) {
                echo "\n Correo es: ".$value->getFrom()[0]->mail." | La fecha del correo es: ".$value->getDate() ." ID= ". $value->getUid() ."\n";
            }
```
![image](https://user-images.githubusercontent.com/33232796/102842866-bd283500-43e6-11eb-84d3-b67e8f8fd343.png)

I would also like to know if it is possible to search by uuid, that is to say, to start from uuid 168 onwards or 184 onwards

**Comment by Webklex** [comment]
Hi @alexv96 ,
you have to update the config option `options.sequence` inside your `config/imap.php` file or options array to `IMAP::ST_UID`.

You can search for a uid or msgn range by using `$folder->overview($range = "168:*")` and `$folder->query()->getMessage($id = 168)` if you want to fetch a specific message.

Here is an example with the response: https://www.php-imap.com/api/folder

Best regards,

**Comment by Webklex** [comment]
Hi @alexv96 ,
please update to the latest release v2.3.1 and try again. Please let me know if this issue persists.

Best regards,
