### ISSUE TITLE
Too few arguments to function Webklex\PHPIMAP\Query\Query::fetchOrderDesc(),

### ISSUE THREAD

**Issue by Polfo** [Webklex/php-imap#65]
**Describe the bug**
Too few arguments Exception on Query::fetchOrderDesc(),

**To Reproduce**
$folder->query()->fetchOrderDesc()->get();

Source code D:\laragon\www\ecoob_laravel\vendor\webklex\php-imap\src\Query\Query.php:550
```
public function fetchOrderDesc($fetch_order) {
        return $this->setFetchOrderDesc();
}

```

**Comment by Webklex** [comment]
Hi @Polfo ,
I assume you are not using v2.3.0? Please update to v2.3.0 and try again.

https://github.com/Webklex/php-imap/blob/d74fbddfafb8e2d8d296a1b0c7352c7d2b88367a/src/Query/Query.php#L550-L569

Best regards,

**Comment by Polfo** [comment]
Indeed. Thanks.
