### ISSUE TITLE
getMessage() not work?

### ISSUE THREAD

**Issue by reimax** [Webklex/php-imap#66]
Hi.
latest version lib, use code:

```
$cm = new ClientManager([
                'options' => [
                    'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                    'fetch_order' => 'desc',
                ],
            ]);
            
            $imap = $cm->make([
                'host'  => $account_info->account_server,
                'port'  => $account_info->account_port,
                'protocol'  => 'imap', //might also use imap, [pop3 or nntp (untested)]
                'encryption'    => $account_info->account_encryption ,
                'validate_cert' => true,
                'username' => $account_info->account_login,
                'password' => $account_info->account_password,
                'authentication' => null,
            ]);

$folder = $imap->getFolder($folder_title);
$message_info = $folder->query()->getMessage($message_msgn);
```

and... not work. i try test witch msgn or uid.

**Comment by Webklex** [comment]
Hi @reimax ,
thanks for your report. I need some more information:
- Do you get any exceptions? 
- Whats the value of `$message_info`?
- Have you updated your imap.php config file?
- What the output of `var_dump(ClientManager::$config['options']["sequence"]);`?
- How have you obtained the message number / uid you are trying to query?

Best regards,

**Comment by reimax** [comment]
1. "Webklex \ PHPIMAP \ Exceptions \ MessageHeaderFetchingException
no headers found"

2. after last line i try 
$message_info->move($folder_title);

3. yes

4. 3

5.
```
$email_list = $folder->query()->leaveUnread()->since(date('d.m.Y', $time))->get();
.....
$uid = $value->getUid();
$msgn = $value->getMsgn();
...
```

**Comment by Webklex** [comment]
Hi @reimax ,
thanks for the fast response.

The message numbers are not stable. They change if you move / remove messages from a folder. Please switch to using a uid based sequence. You can do this by updating `options.sequence` to `IMAP::FT_UID`. 

Best regards,

**Comment by Webklex** [comment]
Here is an updated example:
```php
$cm = new ClientManager([
    'options' => [
        'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
        'fetch_order' => 'desc',
        'sequence' => \Webklex\PHPIMAP\IMAP::FT_UID,
    ],
]);

$imap = $cm->make([
    'host'  => $account_info->account_server,
    'port'  => $account_info->account_port,
    'protocol'  => 'imap',
    'encryption'    => $account_info->account_encryption ,
    'validate_cert' => true,
    'username' => $account_info->account_login,
    'password' => $account_info->account_password,
    'authentication' => null,
]);

$folder = $imap->getFolder($folder_title);
$message = $folder->query()->getMessage($message_uid);
```

**Comment by reimax** [comment]
Have you checked your solution?
If you use uid instead of msdn-then nothing changes, the exception also. But a non-working leaveUnread () is also added to the specified error. I checked now and if put ST_MGN - leaveUnread () works, if FT_UID() - leaveUnread() does not work.

**Comment by Webklex** [comment]
Hi @reimax ,
well I can't "check" the solution, because I can't reproduce the problem with my accounts. However I could imagine a possible problem and tried to provide a solution ;)

Are you sure you are querying the correct folder?
```php
$headers = $folder->overview();
if (isset($headers[$message_uid])){
    var_dump($headers[$message_uid]);
}else{
    echo "Message not in folder";
}
```

What do you mean by "a non-working leaveUnread () is also added to the specified error"? Has the exception changed?

Best regards,

**Comment by reimax** [comment]
yes, i get message info: subject, body, date and other.
then i try
$email_list = $folder->query()->leaveUnread()->since(date('d.m.Y', $time))->get();
all message in folder get read flag.

**Comment by Webklex** [comment]
This is so strange..

To recap:
- You can't query the message directly using `Query::getMessage()` -> results in an exception `no headers found`
- But you can query the headers using `Folder::overview()`
- If `options.sequence` is set to `IMAP::ST_MGN` `Query::leaveUnread()` works as expected
- But if `options.sequence` is set to `IMAP::ST_UID` or `IMAP::FT_UID`, `Query::leaveUnread()` does not work

Can you confirm this? 
I have to think about it. If you have any additional information, please let me know.

Best regards,

**Comment by reimax** [comment]
yes. 
I don't understand why this is happening. If it helps, I'll use yandex mail.
before i use https://github.com/SSilence/php-imap-client
and for this mail and other mail service with php-imap-client there were no such errors

**Comment by dobrynin-andrey** [comment]
Hello, I have a similar error with Yandex Mail.
```php
Webklex\PHPIMAP\Exceptions\MessageHeaderFetchingException : no headers found
 /var/www/html/vendor/webklex/php-imap/src/Message.php:430
 /var/www/html/vendor/webklex/php-imap/src/Message.php:237
 /var/www/html/vendor/webklex/php-imap/src/Query/Query.php:284
 /var/www/html/vendor/webklex/php-imap/src/Message.php:909
 /var/www/html/app/Api/Imap.php:31
 /var/www/html/tests/Unit/ImapApiTest.php:20
```

The error occurs with the parameters:
```php
 'options' => [
        'delimiter' => '|',
        'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
        'sequence' => \Webklex\PHPIMAP\IMAP::ST_MSGN,
        'fetch_body' => true,
        'fetch_flags' => true,
        'message_key' => 'list',
        'fetch_order' => 'asc'
]
```

But 1 letter is moved to the "Done" folder (or any other), after which the error falls.
If you use parameter `IMAP::ST_UID`, then there is no error, but the message is not moved to the folder, and the flag changes to read (SEEN) and that's it.

My code: 
```php
        $client = Client::account('default');
        $client->connect();

        /** @var Folder $folder */
        $folder = $client->getFolder(self::FOLDER_INBOX);

        $messages = $folder
            ->messages()
            ->whereFrom(self::FROM)
            ->get();

        /** @var \Webklex\PHPIMAP\Message $message */
        foreach ($messages as $message) {
            if ($message->move(self::FOLDER_DONE) == true) {
                dump('Move');
            } else {
                dump('Not move');
            }
        }
```

**Comment by alexv96** [comment]
> yes.
> I don't understand why this is happening. If it helps, I'll use yandex mail.
> before i use https://github.com/SSilence/php-imap-client
> and for this mail and other mail service with php-imap-client there were no such errors

I'm trying out that library and I wanted to ask you how do you search by date? **SSilence/php-imap-client**

**Comment by Webklex** [comment]
Hi @reimax @dobrynin-andrey @alexv96 ,
please update to the latest release v2.3.1 and let me know if the issue persits.

Best regards,
