### ISSUE TITLE
Subfolders do not work

### ISSUE THREAD

**Issue by Polfo** [Webklex/php-imap#68]
**Describe the bug**
I cannot work with subfolders

**To Reproduce**

This code return null two times
```php
$fn = 'INBOX.read';
if (!$this->client->getFolder($fn)) {
    dump($this->client->createFolder($fn, true));
}
dump($this->client->getFolder($fn));
```
Altough null is returned, the folder is created as can be seen through the browser webmail.

Running the same code with 
```php
$fn = 'INBOXread'; // note the missing dot
```
dumps `Webklex\PHPIMAP\Folder` as expected.

**Version**
- PHP 7.4.9
- Version 2.3.0

**Comment by Webklex** [comment]
Hi @Polfo ,
thanks for the report. Which provider are you using? Try changing the config option `options.delimiter` to `.` - If you do so, please also update the `options.common_folders` paths.

Best regards,
