### ISSUE TITLE
Copy paste error in documentation for query()->count() 

### ISSUE THREAD

**Issue by Polfo** [Webklex/php-imap#69]
https://www.php-imap.com/api/query
The documentation for `query()->count()` is an unadapted copy of `query()->limit()` 

```
Limit the result
Limit the result to a specific limit and / or page. This has a great positive effect on your execution time.

Count the result
Limit the result to a specific limit and / or page. This has a great positive effect on your execution time.
```

**Comment by Webklex** [comment]
Hi @Polfo ,
thanks for the report. An update has been applied:

- https://github.com/Webklex/php-imap-documentation/commit/8d23858d5bfd70c0b91ffbea0fd9f3bca36744a8
- https://www.php-imap.com/api/query

Best regards,
