### ISSUE TITLE
query limit() and paginate() documentation improvements

### ISSUE THREAD

**Issue by Polfo** [Webklex/php-imap#70]
https://www.php-imap.com/api/query 

The documentation does not indicate if page numbering starts at 0 or 1
```
Limit the result to a specific limit and / or page. This has a great positive effect on your execution time.
$messages = $query->all()->limit($limit = 10, $page = 2)->get();
```

The examples look like a mix of 
- function declaration `function limit($limit, $page = 1)`
- example `$query->all()->limit(10, 2)`, in php 8 this could be `$query->all()->limit(limit: 10, page: 2)`

It would be nice to show the function declaration with self explaining default values.

For `paginate()` it would be nice to have a more elaborate example. it is currently not clear what `$page` and `$page_name` are supposed to do.

```
Get a paginated collection of all available messages. Here is a pagination example.
$paginator = $query->all()->paginate($per_page = 5, $page = null, $page_name = 'imap_page');
```

Also the source code does not bring enough clarity
```php
/**
     * Paginate the current query
     * @param int $per_page
     * @param null $page
     * @param string $page_name
     *
     * @return LengthAwarePaginator
     * @throws GetMessagesFailedException
     */
    public function paginate($per_page = 5, $page = null, $page_name = 'imap_page'){
```
It remains unclear what `$page` and `$page_name` are supposed to do without trying and dumping.

https://www.php-imap.com/examples/pagination brings some relief. Presumable implementating that and analysing `$paginator->links()` would bring some clarity.

Also, the source code of `paginate()` shows a `get()` while this is not the case for the other methods in `Query`. Shouldn't that be documented?

**Comment by Webklex** [comment]
Hi @Polfo ,
thanks for your report. I can see why this might be unclear. Thanks for pointing this out. I've added some more context to the mentioned sections. It still needs some more attention, but I guess that's true for the entire documentation :)

https://github.com/Webklex/php-imap-documentation/commit/5b628cfc4ad81f73a2d092f992344ee681b5670a

The Documentation repository if publicly available under https://github.com/Webklex/php-imap-documentation.

Best regards,
