### ISSUE TITLE
How can I get the message using Uid?

### ISSUE THREAD

**Issue by harshitpeer** [Webklex/php-imap#72]
I remember using Uid to get a specific message previous but I saw the newer version is using Message Number rather than Uid. 
I'm not sure why this change was applied as message number gets constantly change if the messages are removed/moved.

I want to know if it's possible to fetch a specific message with Uid? If yes, please let me know.

Thanks!

**Comment by harshitpeer** [comment]
Oops! My apologies, I didn't saw that the recent version is indeed using Uid.

**Comment by harshitpeer** [comment]
Okay, so I upgraded to the latest version 2.3.0 and everything stopped working 😂

Below is my code and it results in "no headers found" exception. 
```
        $cm = new ClientManager([
            'options' => [
                'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                'fetch_order' => 'desc',
                'sequence' => \Webklex\PHPIMAP\IMAP::FT_UID,
            ],
        ]);
        $client = $cm->make([
            'host'          => 'XXXXXXX',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => 'XXXX@XXXX.com',
            'password'      => 'XXXXXXXXXXXXXX',
            'protocol'      => 'imap',
            'authentication' => null,
        ]);
        $mailbox = $client->getFolder('INBOX');
        return $mailbox->query()->getMessage(14);
```

However, if I ran below code, I do get the message headers

```
        $headers = $mailbox->overview();
        if (isset($headers[14])) {
            return $headers[14];
        } else {
            return "Message not in folder";
        }
```

I'm not sure what I'm doing wrong. Can you please help? 

Thanks!

**Comment by Webklex** [comment]
Hi @harshitpeer ,
thanks for your report.
Please update to the latest version (v2.3.1). You can now query for a message by its uid or msgn directly:

```php
$message = $folder->query()->getMessageByUid($uid);
$message = $folder->query()->getMessageByMsgn($uid);
```

Best regards,

**Comment by harshitpeer** [comment]
You're a ROCKSTAR!

BTW, why you don't have a DONATE link on your Github or Documentation page? I (and pretty sure others as well) would love to do some small contribution towards your efforts on keeping this repo active.
