### ISSUE TITLE
double mail in return_path header

### ISSUE THREAD

**Issue by damian-g** [Webklex/php-imap#73]
**Describe the bug**
Atfer update php-map to v 2.3.0 (or maybe earlier) I have doubled email in return_path header part:

` "<mail@domain.pl> <mail@domain.pl>"`

**To Reproduce**
My Code:
```
$client = ImapClient::account('default');
$client->setDefaultMessageMask(MessageMask::class);
$client->connect();
$folder = $client->getFolder('INBOX');
$messages = $folder->messages()->all()->get();
foreach($messages as $message){
 $header = $message->getHeader();
 dd($header->getAttributes()['return_path']);
}
```

**Expected behavior**
Should be only one:
<mail@domain.pl>

**Desktop / Server (please complete the following information):**
webklex/php-imap": "^2.3.0",
php 7.4.11
debian 9.13

**Comment by Webklex** [comment]
Hi @damian-g ,
thanks for your report. Please dump the raw message header and look for the row which looks like this: `ReturnPath: something` or `Return Path: something` and post it here. I can't test this otherwise.

You can dump the message header like this:
```php
var_dump($message->getHeader()->raw);
``` 

Best regards,

**Comment by damian-g** [comment]
@Webklex try use:

`$header->getAttributes()`

if  I use raw header, it's ok 

`Return-Path: <mail@domain.pl>\r\n`
vs
`"return_path" => "<mail@domain.pl.pl> <mail@domain.pl.pl>"`

but cannot use raw to get one parameter.

Looks a raw, few lines is doubled too:

```
Return-Path: <mail@domain.pl>\r\n
Delivered-To: receipent@domain.pl\r\n
Received: from h2.server.pl\r\n
\tby h2.server.pl with LMTP\r\n
\tid 4IDTIEUkm18ZSSkA87l24w\r\n
\t(envelope-from <mail@domain.pl>)\r\n
\tfor <receipent@domain.pl>; Thu, 29 Oct 2020 21:21:25 +0100\r\n
Return-path: <mail@domain.pl>\r\n
Envelope-to: receipent@domain.pl\r\n
Delivery-date: Thu, 29 Oct 2020 21:21:25 +0100\r\n
Received: from domain.pl ([94.23.89.102])\r\n
\tby h2.server.pl with esmtps  (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\r\n
\t(Exim 4.94)\r\n
\t(envelope-from <mail@domain.pl>)\r\n
\tid 1kYEQG-00BPgD-S0\r\n
\tfor receipent@domain.pl; Thu, 29 Oct 2020 21:21:25 +0100\r\n
Received: by domain.pl (Postfix, from userid 1000)\r\n
\tid 57DADAB; Thu, 29 Oct 2020 21:21:23 +0100 (CET)\r\n
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=domain.pl; s=default;\r\n
\tt=1604002883; bh=CsZufJouWdjY/W12No6MSSMwbp0VaS8EOMGg9WptEaI=;\r\n
\th=From:To:Subject:Date;\r\n
\tb=v0NAncnNT/w+gInANxAkMt20ktM4LZquuwlokUmLpPyO3++8dy112olu63Dkn9L2E\r\n
\t GwfHGqW+8f7g494UK6asUKqTx8fHxlEJbHqAiEV5QrlynSeZDFXsKvGDW8XNMFBKop\r\n
\t sAjvp8NTUiNcA4MTbFaZ7RX15A/9d9QVEynU8MaNP2ZYKnq9J/JXgUjjMnx+FiULqf\r\n
\t xJN/5rjwHRx7f6JQoXXUxuck6Zh4tSDiLLnDFasrSxed6sTNfnZMAggCyb1++estNk\r\n
\t q6HNBwp85Az3ELo10RbBF/WM2FhxxFz1khncRtCyLXLUZ2lzhjan765KXpeYg7FUa9\r\n
\t zItPWVTaTzTEg==\r\n
From: jakisinnyuser@domain.pl\r\n
To: receipent@domain.pl\r\n
...
\r\n
```

**Comment by Webklex** [comment]
Hi @damian-g ,
thanks for the followup along with the header dump. 

Looking at the dump, the result is correct:
Line 1 **and** 8 contain a return path header - which means the parsed header should contain two entries, which it does.

Best regards,
