### ISSUE TITLE
Overview method does not work if I enter a parameter other than 1

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#74]
I have a problem or doubt more than anything else, I am occupying the overview method because I want to make the search list me even if it is from a UID onwards, the issue that I know that a mail has as UID 165 -168 to 185 but when I put the range brings me null and if I list from 1:* brings me all but I would like to start from a specific sequence and not from the beginning.

This is the code that I am occupying.

```
$cm = new ClientManager([
                'options' => [
                    'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                    'fetch_order' => 'desc',
                    'sequence' => \Webklex\PHPIMAP\IMAP::FT_UID,
                ],
            ]);
            
            $oClient = $cm->make([
                'host' => 'imap.gmail.com',
                'port' => 993,
                'protocol' => 'imap',
                'encryption' => 'ssl',
                'validate_cert' => true,
                'username' => 'jer******@gmail.com',
                'password' => '*****',
            ]);
               
            $oClient->connect();
            $folder = $oClient->getFolder('INBOX');
            $message = $folder->overview($range = "1:*");//Working ✔
            //$message = $folder->overview($range = "168:*");//Not working ❌

            foreach ($message as $key => $value) {
                
                dd($folder->query()->getMessageByUid($key));
            }
```

If I occupy $folder->overview('1:*'); it brings me this

![image](https://user-images.githubusercontent.com/33232796/103392453-c27b3300-4afc-11eb-985a-ce35a4cf1388.png)

But if I occupy $folder->overview('168:*'); it brings me null

![image](https://user-images.githubusercontent.com/33232796/103392490-edfe1d80-4afc-11eb-987e-814f529d4fae.png)

Because the idea of this method would be to bring a quick description between 2 ranges, but I don't know if the sequence works by UID search or by a number as it is in the mail

Here I made the query $folder->query()->getMessage(165) ; to check if this UID exists so the overview method should work too and not bring me null.

![image](https://user-images.githubusercontent.com/33232796/103412215-c8036800-4b52-11eb-9e3b-29ae108b6d84.png)

**Comment by alexv96** [comment]
@Webklex Try these modifications by doing it manually and now it works :D thank you very much.

Should I leave it manual while or wait for the new version to be uploaded?

**Comment by Webklex** [comment]
Hi @alexv96 ,
thanks for the feedback. I would recommend to use an updatable version. I'm currently working on the next release v2.4.0. This might still take a few days... 

I believe composer can checkout certain commits instead of version tags - but I'm not sure..

I'll let you know if the new release is available.

Best regards,

**Comment by Webklex** [comment]
Hi @alexv96 ,
a new version has been released. Please check out the changelog / breaking changes before updating.

Best regards,
