### ISSUE TITLE
2.3.1 not found by composer

### ISSUE THREAD

**Issue by Polfo** [Webklex/php-imap#75]
When I try to test 2.3.1, I cannot load is with composer.

`"webklex/laravel-imap": "^2.3"`
installs 2.3.0

`"webklex/laravel-imap": "^2.3.1"`
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires webklex/laravel-imap ^2.3.1, found webklex/laravel-imap[dev-master, 1.0.0, ..., 1.6.2, 2.0.0, ..., 2.3.0] 
but it does not match the constraint.
```

**Comment by Webklex** [comment]
Hi @Polfo ,
you are trying to update the wrong dependency. `webklex/laravel-imap` is not equal to `webklex/php-imap`. The Laravel wrapper depends on the php-imap package. If you want to use a newer version of php-imap inside the Laravel wrapper, just add `webklex/php-imap` to your project dependencies:

```json
"require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "webklex/laravel-imap": "^2.3",
        "webklex/php-imap": "^2.3.1"
    },
```

..or use composer directly to require a newer version: `composer require webklex/php-imap:2.3.1`.


Best regards,

**Comment by Polfo** [comment]
Indeed, thanks
