### ISSUE TITLE
I can't access the attributes

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#77]
'm doing a search with overview, the theme goes that when I want to access the attributes it never leaves me and I get error messages, so I don't know if it's because I've been doing something wrong.

```
$cm = new ClientManager([
                'options' => [
                    'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                    'fetch_order' => 'desc',
                    'sequence' => \Webklex\PHPIMAP\IMAP::FT_UID,
                ],
            ]);
            
            $oClient = $cm->make([
                'host' => 'imap.gmail.com',
                'port' => 993,
                'protocol' => 'imap',
                'encryption' => 'ssl',
                'validate_cert' => true,
                'username' => 'jer******@gmail.com',
                'password' => '*****',
            ]);
               
            $oClient->connect();
            $folder = $oClient->getFolder('INBOX');
            $messages = $folder->overview($sequence = "190840:190842");
```
Because if I get the messages.

![image](https://user-images.githubusercontent.com/33232796/103488204-6577c980-4de9-11eb-9550-6700cbe89ade.png)

But when I go through the data you brought me in the foreach it doesn't let me access your data.

```
            foreach ($messages as $key => $value) {
                dd($value->getAttributes()["subject"]); //Not working ❌
            }
```

![image](https://user-images.githubusercontent.com/33232796/103488235-aa036500-4de9-11eb-9361-3bb965b07b24.png)

For example, the attributes that I occupied the most in the last library were getFrom(), getSubject(), getDate(). In this new library or version it is occupied so I understood the ```$message->getAttributes()["attribute_name"];``` 

Am I doing something wrong?

**Comment by Webklex** [comment]
Hi @alexv96 ,
thanks for your question. I guess something got lost in translation :)

The method `Folder::overview()` does not return an array of messages. Instead it return an array of header values (an overview). Please use `Folder::query()` if you want to fetch messages.

Best regards,
