### ISSUE TITLE
 Doubt to get the email of the message

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#78]
I did the update but I am not very clear about the attributes and address.

Before the update I got the email so **$data->from[0]->mail** now I can't understand very well the Attribute class to get it because I get the staff that many times doesn't bring the email but brings text.

![image](https://user-images.githubusercontent.com/33232796/103491121-d32ef000-4dff-11eb-97e6-638a84cfb8d8.png)

And I read the documentation and I don't get it

```
$oClient->connect();
$folder = $oClient->getFolder('INBOX');
$messages = $folder->overview($sequence = "190840:190842");

            foreach ($messages as $key => $value) {
                $data = $folder->query()->getMessageByUid($key);
                echo "Date => $data->date <br/>";
                echo "Subject => $data->subject <br/>";

                dd($data->from);

                echo "Email =>". $data->from[0]->mail ."<br/>";
                echo "<br/><br/>";
            }
```

**Comment by Webklex** [comment]
Hi @alexv96 ,
thanks for testing. It looks like you mixed up two different methods;

1.) `Folder::overview()` does not return a message collection and does not contain "Attribute::class" instances. It's a simple multidimensional array
2.) To access the first from address try something like this: `$message->from->first()->mail`

## Folder::overview() example:
```php
$array = $folder->overview($sequence = "190840:190842");
foreach($array as $values){
    echo $values["from"][0]->mail."\n";
}
```

## Folder::query() example:
```php
$folder->query()->all()->get()->each(function($message){
    echo $message->from->first()->mail."\n";
});
```

Ill hope this helps :)

Best regards,

**Comment by alexv96** [comment]
Thank you very much, everything is clearer now. :D
