### ISSUE TITLE
move message not work

### ISSUE THREAD

**Issue by reimax** [Webklex/php-imap#79]
last version php-imap,
php 7.4

code:
```
$folder = self::$imap->getFolder($folder_title);
$message_info = $folder->query()->getMessageByUid($message_uid);
$status = $message_info->move('$folder_name');
```

not work, message in mailbox not move to target folder. i check docs and in example i see 

```
$message = $message->move($folder_path = "INBOX.name");
```

if i use $folder_path for $message_info->move() message in mailbox not move to target folder. i open Message.php and check why in public function move():

$status = $this->client->getConnection()->examineFolder($folder_path) - need **folder path** 
$folder = $this->client->getFolder($folder_path); - need **folder name**.

if i use code 
```
$folder = self::$imap->getFolder($folder_title);
$message_info = $folder->query()->getMessageByUid($message_uid);
$status = $message_info->move('$folder_path');
```

and in Message.php replace
`$folder = $this->client->getFolder($folder_path);`

to

`$folder = $this->client->getFolder($folder_name);`

move message work

**Comment by reimax** [comment]
908 line in Message.php i replace to 

`$folder = $this->client->getFolderByPath($folder_path);`

and move message work for me.

**Comment by Webklex** [comment]
Hi @reimax ,
thanks for your report.

I updated the documentation accordingly: https://github.com/Webklex/php-imap-documentation/commit/3b82150514c6aaec14011fbdb64b774c708cba76

Does `$folder_path` contain the delimiter defined in your config? If not please make sure they do :)

https://github.com/Webklex/php-imap/blob/6c2c54f9f99a1f5fff99f98bfacc2dcd706c9c9a/src/Client.php#L398-L408
`Client::getFolder()` is pretty flexible and accepts both a "name" or a "path".

Best regards,

**Comment by reimax** [comment]
i test witch **.** and not work. i not set other delimiter.
i return to original message.php and set 
`$status = $message_info->move('$folder_path');`

$folder_path witch path and name folder. not work =)

**Comment by Webklex** [comment]
Hi @reimax ,
thanks for the quick followup. 
Please try to use `/` instead or set your delimiter to `.` inside your config options.

Best regards,

**Comment by reimax** [comment]
i test this and not work witch / or .

**Comment by Webklex** [comment]
Alright, whats the output of `\Webklex\PHPIMAP\ClientManager::get("options")`?

**Comment by reimax** [comment]
Alright,
\Webklex\PHPIMAP\ClientManager::get("options") show me my settings witch delimiter /

Client::getFolder() is pretty flexible and accepts both a "name" or a "path". - okey, but 

$status = $this->client->getConnection()->examineFolder($folder_path);

return null when i send folder_path/folder_title.

**Comment by Webklex** [comment]
Hi @reimax ,
thanks for the followup. 
Please make sure you've set the delimiter inside your config to `.`. 

If you are using the laravel package, take a look at the config file located under `config/imap.php`. If it doesn't exists, please make sure to publish the package config first.

If you are using the "plain" `webklex/php-imap` package and you are using your own custom config file, please make sure you've updated the delimiter inside it under `options.delimiter`.

If you are initializing the `ClientManager` class from an config array, please make sure to include `"options" => ["delimiter" => "."]` in it.

You might also want to update the commons folder array as well, and update the default paths.

Best regards,

**Comment by reimax** [comment]
I wrote in the last message that you will be divided in the settings of the site. i test witch . and /
I not use laravel package
I use "plain" webklex/php-imap , and config array:

```
$cm = new ClientManager([
                'options' => [
                    'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                    'fetch_order' => 'desc',
                    'delimiter' => '/',
                ],
            ]);
            
            self::$imap = $cm->make([
                'host'  => $account_server,
                'port'  => $account_port,
                'protocol'  => 'imap', //might also use imap, [pop3 or nntp (untested)]
                'encryption'    => $account_encryption,
                'validate_cert' => true,
                'username' => $account_login,
                'password' => $account_password,
                'authentication' => null,
            ]);
```

**Comment by Webklex** [comment]
What the output of the following?

```php
$cm = new ClientManager([
    'options' => [
        'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
        'fetch_order' => 'desc',
        'delimiter' => '.',
        'common_folders' => [
            "root" => "INBOX",
            "junk" => "INBOX.Junk",
            "draft" => "INBOX.Drafts",
            "sent" => "INBOX.Sent",
            "trash" => "INBOX.Trash",
        ],
    ],
]);

self::$imap = $cm->make([
    'host'  => $account_server,
    'port'  => $account_port,
    'protocol'  => 'imap', 
    'encryption'    => $account_encryption,
    'validate_cert' => true,
    'username' => $account_login,
    'password' => $account_password,
    'authentication' => null,
]);

$check = strpos($folder_path, \Webklex\PHPIMAP\ClientManager::get("options.delimiter")) !== false;
var_dump($check);
var_dump($folder_path);
var_dump(\Webklex\PHPIMAP\ClientManager::get("options"));

$other_folder = $this->client->getFolder($other_folder_path);
$folder = $this->client->getFolder($folder_path);

var_dump($other_folder->path);
var_dump($folder->path);

$message = $folder->query()->getMessageByUid($message_uid);
var_dump($message->uid);

$new_message = $message->move($other_folder->path, true);

var_dump($new_message->uid);
```

Best regards,

**Comment by reimax** [comment]
use path
$folder_path = "INBOX";
$other_folder_path = "&BCMENAQwBDsENQQ9BD0ESwQ1-";
$message_uid = 9822;

```
account.php:92:boolean false
account.php:93:boolean false
account.php:94:string '&BCMENAQwBDsENQQ9BD0ESwQ1-' (length=26)
account.php:95:string 'INBOX' (length=5)
account.php:96:
array (size=11)
  'delimiter' => string '.' (length=1)
  'fetch' => int 2
  'sequence' => int 3
  'fetch_body' => boolean true
  'fetch_flags' => boolean true
  'message_key' => string 'list' (length=4)
  'fetch_order' => string 'desc' (length=4)
  'dispositions' => 
    array (size=2)
      0 => string 'attachment' (length=10)
      1 => string 'inline' (length=6)
  'common_folders' => 
    array (size=5)
      'root' => string 'INBOX' (length=5)
      'junk' => string 'INBOX.Junk' (length=10)
      'draft' => string 'INBOX.Drafts' (length=12)
      'sent' => string 'INBOX.Sent' (length=10)
      'trash' => string 'INBOX.Trash' (length=11)
  'decoder' => 
    array (size=2)
      'message' => string 'utf-8' (length=5)
      'attachment' => string 'utf-8' (length=5)
  'open' => 
    array (size=0)
      empty
account.php:101:null
account.php:102:string 'INBOX' (length=5)
account.php:105:int 9822
account.php:109:null
```


use name
$folder_path = "INBOX";
$other_folder_path = "Удаленные";
$message_uid = 9822;

```
account.php:92:boolean false
account.php:93:boolean false
account.php:94:string 'Удаленные' (length=18)
account.php:95:string 'INBOX' (length=5)
account.php:96:
array (size=11)
  'delimiter' => string '.' (length=1)
  'fetch' => int 2
  'sequence' => int 3
  'fetch_body' => boolean true
  'fetch_flags' => boolean true
  'message_key' => string 'list' (length=4)
  'fetch_order' => string 'desc' (length=4)
  'dispositions' => 
    array (size=2)
      0 => string 'attachment' (length=10)
      1 => string 'inline' (length=6)
  'common_folders' => 
    array (size=5)
      'root' => string 'INBOX' (length=5)
      'junk' => string 'INBOX.Junk' (length=10)
      'draft' => string 'INBOX.Drafts' (length=12)
      'sent' => string 'INBOX.Sent' (length=10)
      'trash' => string 'INBOX.Trash' (length=11)
  'decoder' => 
    array (size=2)
      'message' => string 'utf-8' (length=5)
      'attachment' => string 'utf-8' (length=5)
  'open' => 
    array (size=0)
      empty
account.php:101:string '&BCMENAQwBDsENQQ9BD0ESwQ1-' (length=26)
account.php:102:string 'INBOX' (length=5)
account.php:105:int 9822
account.php:109:int 32524
```

use path.name
$folder_path = "INBOX.INBOX";
$other_folder_path = "&BCMENAQwBDsENQQ9BD0ESwQ1-.Удаленные";
$message_uid = 9822;

```
account.php:92:boolean true
account.php:93:boolean true
account.php:94:string '&BCMENAQwBDsENQQ9BD0ESwQ1-.Удаленные' (length=45)
account.php:95:string 'INBOX.INBOX' (length=11)
account.php:96:
array (size=11)
  'delimiter' => string '.' (length=1)
  'fetch' => int 2
  'sequence' => int 3
  'fetch_body' => boolean true
  'fetch_flags' => boolean true
  'message_key' => string 'list' (length=4)
  'fetch_order' => string 'desc' (length=4)
  'dispositions' => 
    array (size=2)
      0 => string 'attachment' (length=10)
      1 => string 'inline' (length=6)
  'common_folders' => 
    array (size=5)
      'root' => string 'INBOX' (length=5)
      'junk' => string 'INBOX.Junk' (length=10)
      'draft' => string 'INBOX.Drafts' (length=12)
      'sent' => string 'INBOX.Sent' (length=10)
      'trash' => string 'INBOX.Trash' (length=11)
  'decoder' => 
    array (size=2)
      'message' => string 'utf-8' (length=5)
      'attachment' => string 'utf-8' (length=5)
  'open' => 
    array (size=0)
      empty
account.php:101:null
account.php:102:null
```

**Comment by EthraZa** [comment]
I guess it's not related, so I'm felling bad to hijack this issue, but move message is not working for me for another reason.

```
$messagge->move('INBOX.Trash');   // fails silently.
```

Why?

move method at https://github.com/Webklex/php-imap/blob/master/src/Message.php#L901 does
```
$status = $this->client->getConnection()->examineFolder($folder_path);

if (isset($status["uidnext"])) {
```
but, "uidnext" does no exists for me.

```
dd($this->client->getConnection()->examineFolder('INBOX.Trash'));

array:4 [
  "flags" => array:1 [
    0 => array:6 [
      0 => "\Draft"
      1 => "\Answered"
      2 => "\Flagged"
      3 => "\Deleted"
      4 => "\Seen"
      5 => "\Recent"
    ]
  ]
  "exists" => "1"
  "recent" => "0"
  "uidvalidity" => 1444046641
]
```
Now next line is 917:
```
return null;
```
That lets me wondering what just happened that message was not moved and no exception was raised.

**Comment by linhuchiha01** [comment]
i use copy() is working, but use move() is not working?
please help me.
my code: 
`  $client->connect();
        //Get all Mailboxes
        /** @var \Webklex\IMAP\Support\FolderCollection $folders */
        $folders = $client->getFolder('INBOX');
        /** @var \Webklex\IMAP\Message $message */
        $message = $folders->messages()->getMessageByUid($uid = $id);
        $message = $message->move('TRASH');`
