### ISSUE TITLE
Search by date does not work for me

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#80]
I'm trying the date search with the since method but always even if I throw a var_dump, print_r or dd I get this error message with that method.

![image](https://user-images.githubusercontent.com/33232796/103537567-648b7a00-4e73-11eb-9516-2e277477e6b7.png)

I have tried other functions and if they work as the overview, so I rule out that it is connection to the outlook email

```
            $oClient->connect();
            $folder = $oClient->getFolder('INBOX');
            $messages = $folder->query()->since('07.12.2020')->get();

            dd($messages); //The error message appears
```

**Comment by Webklex** [comment]
Hi @alexv96 ,
thanks for the report.
I've never seen this error message before, so I had to Google it. It seems like it indicates a problem with the established connection. This can be caused by a lot of things, such as an unstable internet connection, a lag of ram, an internal timeout or the fup of your mail provider.

Please try to search for a smaller time frame, such as (now - 1 day) or so and see if this works. 

Given the location of the error, I doubt that you actually reach the `dd()`. The error occurs in `Query::get()` which gets executed / called before.

Best regards,

**Comment by alexv96** [comment]
So if you are in production those time limit errors should not happen? Because at least in the last webklex/laravel-imap library I did a 30-day search but it never showed me the time limit error when I was searching by date too far back 

Now if I bring more than 2 messages I throw that error message, doing the test with date 5.01.2021 and with limit(2)

![image](https://user-images.githubusercontent.com/33232796/103654065-2dd16480-4f44-11eb-89af-532460a089cb.png)

```
            $messages = $folder->query()->since('05.01.2021')->limit(2)->get(); ///Workig 
            $messages = $folder->query()->since('05.01.2021')->limit(20)->get(); ///Not Workig [execution exceeded] 

//            dd($messages);
        
            foreach ($messages as $key => $data) {
                echo "Date => $data->date <br/>";
                echo "Subject => $data->subject <br/>";
                echo "Email =>". $data->from->first()->mail ."<br/>";
                echo "Uuid => ". $data->uid."<br/>";
                echo $data->getHTMLBody();
                echo "<br/><br/>";
            }
```

**Comment by Webklex** [comment]
Hi @alexv96 ,
do you have any big messages in your inbox? Try to disable the body fetching:
```php
$messages = $folder->query()->since('05.01.2021')->setFetchBody(false)->limit(20)->get();
```
If you have a message with a big attachment or a "never ending" body this could happen. If you have to fetch them regardless, you could increase the php timeout but I would recommend not to do so.. 

Which previous version were you using?

Best regards,

**Comment by alexv96** [comment]
Ok I'm going to try it out and let you know how it goes.

I used to occupy: 

"webklex/laravel-imap": "^1.4",

**Comment by alexv96** [comment]
I executed it and it still shows the error of the exceeded time, I tried with 5 of limit and it still fell if I only put limit 2 the search does not fall.

Because the email I extract is constantly receiving emails throughout the day.

**Comment by alexv96** [comment]
@Webklex Question to increase the limit I do it in php.ini with max_input_time =-1 or not?
