### ISSUE TITLE
Cannot get OCTET-stream attachment 

### ISSUE THREAD

**Issue by AbetaNL** [Webklex/php-imap#82]
Hello,

Thank you for the great package. I have some problems when trying to open an attachment which has a CSV format. When checking in G-mail I see the CSV attachment and can open and download it without problems. However, when I use php-imap / laravel-imap I cannot open any attachments. (Actually it says the specific message does not have any attachments.)

When checking the body of the mail with the `$message->getHtmlBody()` function I get the following:

![image](https://user-images.githubusercontent.com/25418904/103658504-954eda80-4f6b-11eb-9e0d-d7b6e2677e27.png)

So it seems the attachment has some kind of encoding and is considered as part of the actual message. I am pretty sure it has to do with the Content-Type being OCTET-stream. However, the sender of the attachment told me he cannot change this encoding at all.  Any ideas on how I can correctly get this attachment using the `$message->getAttachments()` function?

Thank you in advance!

**Comment by Webklex** [comment]
Hi @AbetaNL ,
thanks for your report.

Please share a redacted dump of `$message->getStructure()->raw`. This might provide some clues :)

Best regards,

**Comment by AbetaNL** [comment]
Hi @Webklex , here is the output. Since the attachment is multiple megabytes I cut the middle part out.

![image](https://user-images.githubusercontent.com/25418904/103661561-27a4ad80-4f6f-11eb-82b5-2604f7ad5af1.png)

Best regards

**Comment by AbetaNL** [comment]
Hi @Webklex , here is the output. Since the attachment is multiple megabytes I cut the middle part out.

![image](https://user-images.githubusercontent.com/25418904/103661778-633f7780-4f6f-11eb-96d9-95a48ac33d63.png)

Best regards

**Comment by Webklex** [comment]
Thank, but could you share the text (redacted of course!)? I don't want to type it all off in order to test it ;)

Best regards,

**Comment by AbetaNL** [comment]
Hi @Webklex , is there anything I can do or anything you need from me to help discover the cause of this bug? Cheers!

**Comment by Webklex** [comment]
Hi @AbetaNL ,
please update to the latest release [v2.4.3](https://github.com/Webklex/php-imap/releases/tag/2.4.3).

Best regards,

**Comment by AbetaNL** [comment]
Hi @Webklex , just installed the update. I use php-imap through laravel-imap as in the code below. 
Unfortunately I am not able to open the attachment yet. (I can find the messages, they still have the attachment in the body.)  
  
        $client->connect();
        
        $folder = $client->getFolder('Inbox');
        $messages = $folder->query()->from('example@example.org')->limit(1, 1)->get();
        
        if(count($messages) == 0)
        {
            echo "No messages found";
            return false;
        }

        foreach($messages as $message){
            $attachments = $message->getAttachments();
            foreach ($attachments as $attachment) {
                if ($attachment->getName() == $import->attachment_name) {
                    $attachment->save(storage_path('/app/import/'));
                    return "import/" . $import->attachment_name;
                }
            }
        }

        echo "No attachments found";
       `
        
I am pretty sure I updated everyhing correctly:

![image](https://user-images.githubusercontent.com/25418904/105487176-f850a900-5caf-11eb-905d-982360bef7b2.png)

Is it because I used laravel-imap that this does not work? Sorry for not mentioning this earlier btw.

**Comment by Webklex** [comment]
Hi @AbetaNL ,
thanks for testing. 
Is this an excerpt from you composer.lock? The reference looks fine to me - should be on the latest version / commit.

Just to make sure there is no cache left:
```php
composer dump-autoload
php artisan clear-compiled
php artisan optimize
```

Could you donate a test mail to github@webklex.com? I can't reproduce this behavior.

Also, does this return any output?
```php
foreach($messages as $message){
    $attachments = $message->getAttachments();
    foreach ($attachments as $attachment) {
        dump($attachment->getContent());
        dump($attachment->getName());
        dump($attachment->getSize());
        dump($attachment->getType());
    }
}
```

Best regards,

**Comment by Webklex** [comment]
Ps.: feel free to checkout https://github.com/Webklex/php-imap/commit/5941cee4cde42d88086b99f7d1c2c12cbc136c8e . This might solve your problem as well :)

**Comment by Webklex** [comment]
Hi @AbetaNL ,
please update to the latest release [v2.4.4](https://github.com/Webklex/php-imap/releases/tag/2.4.4).

Best regards,

**Comment by AbetaNL** [comment]
Hi @Webklex, good news, everything seems to work! The only irregularity is that the geName() function seems to result in "text/csv" instead of the name which appears in my Gmail account. I will try and see if I can have the sender of these mails have one send directly to you. If I forward these mails something changes in the encoding.

Thank you for your help!

**Comment by Webklex** [comment]
Hi @AbetaNL  ,
please update to [v2.5.0](https://github.com/Webklex/php-imap/releases/tag/2.5.0).

Best regards,

**Comment by AbetaNL** [comment]
Hi @Webklex , getName() works perfectly now as well! Thanks for your efforts, much appreciated!
