### ISSUE TITLE
Since 2.4.0 I can no longer search for emails earlier than ~2 years

### ISSUE THREAD

**Issue by vesper8** [Webklex/php-imap#84]
I've been testing my program by fetching emails since the last 3 years. I noticed a sudden huge drop in emails being returned since updating to 2.4.0

To test that this isn't related to something else, I just downgraded `webklex/php-imap` and forced it to be `2.3.0` and the problem went away

On 2.3.0
```
php artisan mail:check 'Some String' '5 year'
Checking for new bookings from Some String since 2016-01-06 in all folders
Found 422 messages matching criteria since 2016-01-06
```

On 2.4.0
```
php artisan mail:check 'Some String' '5 year'
Checking for new bookings from Some String since 2016-01-06 in all folders
Found 58 messages matching criteria since 2016-01-06
```

I can provide more info if necessary

**Comment by Webklex** [comment]
Hi @vesper8 ,
thanks for your report. 

Looks like I screwed up, or I'm confused right now:
https://github.com/Webklex/php-imap/blob/356432e631e1adac495d48f832444806a2d300c3/src/Query/Query.php#L225

..gets overwritten here:
https://github.com/Webklex/php-imap/blob/356432e631e1adac495d48f832444806a2d300c3/src/Query/Query.php#L243-L257

..which leads to `$message_key` being overwritten. Imagine you have several emails without message id; well they will get overwritten..

Best regards,

**Comment by vesper8** [comment]
Sounds like you're on to something.. let me know if you want me to test anything. Currently this is a show-stopper so I'm hoping you can release a hot fix soon

**Comment by Webklex** [comment]
I can imagine.
Hotfix has been applied: https://github.com/Webklex/php-imap/releases/tag/2.4.1

Best regards,

**Comment by vesper8** [comment]
Super! I can confirm it is back to working like before. Thanks for the quick work!
