### ISSUE TITLE
Overview method doesn't work with Outlook but it does with Gmail

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#86]
I'm using the overview method, I tried it with GMAIL accounts and it works perfectly, but with Outlook it doesn't always work, it brings me empty

I don't know if this is a bug or not

```
$cm = new ClientManager([
                'options' => [
                    'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
                    'fetch_order' => 'desc',
                    'sequence' => \Webklex\PHPIMAP\IMAP::ST_UID,
                ],
            ]);
            
            $oClient = $cm->make([
                'host' => 'outlook.office365.com',
                'port' => 993,
                'protocol' => 'imap',
                'encryption' => 'ssl',
                'validate_cert' => true,
                'username' => 'my-xompany@outllok.cl',
                'password' => '####',
            ]);
               
            $oClient->connect();
            $folder = $oClient->getFolder('INBOX');
            $messages = $folder->overview("292264:*");//It doesn't work with outlook return null
```

I know that uid exists and it is, because when I execute a search by date I register in my Data Base the UID 

![image](https://user-images.githubusercontent.com/33232796/103933686-89e1e780-5102-11eb-9595-30f3a98cbf1c.png)

For example, here is the UID I want you to bring me a quick visualization and return me the UID 292264
```
$messages = $folder->query()->getMessageByUid(292264);
```
![image](https://user-images.githubusercontent.com/33232796/103933896-d4fbfa80-5102-11eb-8fd1-c27c3d16e647.png)

And if I search with the maximum 292274 if you bring it to me but if I occupy the overview ("292264:292274") it always returns null with Outlook and not with Gmail.
```
$messages = $folder->query()->getMessageByUid(292274);
```
![image](https://user-images.githubusercontent.com/33232796/103934109-32904700-5103-11eb-8158-0d53f59f8b03.png)

**Comment by alexv96** [comment]
@Webklex  Another example is that if the method works but for something it brings me null and not data, because I'm doing a quick look from the UID 292274:* now generate an error to prove that if there are more emails as it comes out reaches 310793 but always brings me null. All this happens only with Outlook and not with Gmail.

![image](https://user-images.githubusercontent.com/33232796/104113228-332d0700-52d6-11eb-9cf0-0b6be57b4440.png)

**Comment by Webklex** [comment]
Hi @alexv96 ,
thanks for your report. 
Unfortunately I can't test nor verify your report - Outlook keeps banning my test accounts.

Since Outlook is a Microsoft product is very well possible that they don't support this operation. Maybe @EthraZa can help? :)

Best regards,

**Comment by EthraZa** [comment]
Hi.
I just checked overview on an Outlook account. It took me about 10 tries to get a return other then timeout or null, but then it worked.
```
$client->getFolder('Inbox', null)->overview();
```
```
{"1":{"from":[{"personal":"Windows Insider Program","mailbox":"windowsinsiderprogram","host":"e-mail.microsoft.com","mail":"windowsinsiderprogram@e-mail.microsoft.com","full":"Windows Insider Program "}],"to":[{"personal":false,"mailbox": ...
```

Outlook IMAP is a trash and most of the time it give me bad results, even for simple things like couting emails it will timeout or just return null:
```
$client->getFolder('Inbox', null)->query()->where('ALL')->count();
```
What I do is recommend my costumers to go to Gmail, but for those who insist in use Outlook, they will must accept it is just lag.

**Comment by alexv96** [comment]
And with this method it is possible to paginate so that the process does not die in the Outlook?
