### ISSUE TITLE
Folder->idle CPU 100%

### ISSUE THREAD

**Issue by WaldemarOrobanche** [Webklex/php-imap#89]
**Describe the bug**
The `while(true)` contains the condition that sometimes doesn't match and runs without timeout that will gonna to take all CPU resources. The same could happen at the `catch` block, because callback could throw any type of exception.

https://github.com/Webklex/php-imap/blob/54375296a53e01308d7a0f7f77f667fc23237214/src/Folder.php#L369-L391

**Expected behavior**
Normal usage of CPU

**Comment by Webklex** [comment]
Hi @WaldemarOrobanche ,
thanks for your report.

I have a few questions though:
- Can you specify the conditions which lead to this behavior? 
- How can this be reproduced? 
- Does this only occur with one specific account / mail provider?
- How does your code look like which:
  - initialize the `Client::class` instance?
  - initialize the `Folder::class` instance?
  - call the `Folder::idle()` method?
- Which `webklex/php-imap` version are you using?
- Which operating system are you using?

Best regards,

**Comment by WaldemarOrobanche** [comment]
> Can you specify the conditions which lead to this behavior?

- when the `$line` variable holds `* OK Still here`.
- when an exception occurs like `failed to read - connection closed?`.

**Comment by Webklex** [comment]
Hi @WaldemarOrobanche  ,
please update to the latest release [v2.4.3](https://github.com/Webklex/php-imap/releases/tag/2.4.3).

Best regards,
