### ISSUE TITLE
Error with Attachement::getExtension

### ISSUE THREAD

**Issue by fklee** [Webklex/php-imap#9]
**Describe the bug**
As I call this function (on version 1.4.5), I get this error :
```
Class 'Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser' not found
```
As looking into your declaration it should : use Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser;

And I can't find in Symphony http-foundation/File such a class ? Maybe symphony has change this to : Beetween versions 4.x and 5.x (read here, Deprecated: https://pkp.sfu.ca/ojs/doxygen/master/html/classSymfony_1_1Component_1_1HttpFoundation_1_1File_1_1MimeType_1_1ExtensionGuesser.html)
https://symfony.com/doc/current/components/mime.html
```
use Symfony\Component\Mime\MimeTypes;

$mimeTypes = new MimeTypes();
$mimeType = $mimeTypes->guessMimeType('/some/path/to/image.gif');
// Guessing is not based on the file name, so $mimeType will be 'image/gif'
// only if the given file is truly a GIF image
```

I did the same like this which is OK, you could use this code in the function getExtension(), Warning, It return an array, so I returned the first one, I t should be tested if the array is empty, if no extension is found
```
$guesser = new MimeTypes();
return isset($guesser->getExtensions($this->getMimeType())[0]) ? $guesser->getExtensions($this->getMimeType())[0] : null ;
```

**Comment by Webklex** [comment]
Hi @fklee ,
thanks for your detailed report. 
A fix has been applied. Please update to the latest version.

Best regards,
