### ISSUE TITLE
getAttachments on mail from IOS

### ISSUE THREAD

**Issue by Krzysztof-Pluskota** [Webklex/php-imap#90]
Hi,

I have a little problem. This package working fine, but when i try get an email attachment, which was send from ios, and attachment is into text body, then he handled as a text and `hasAttachments()` return false, or `getTextBody()` return email content with attachment as a string value.

**Comment by Webklex** [comment]
Hi @Krzysztof-Pluskota ,
thanks for your report.

Please provide an anonymized version of your mail content:
```php
echo $message->getStructure()->raw;
```

Also which version are you running? 
Are you using a legacy protocol or "imap"?

Best regards,

**Comment by Krzysztof-Pluskota** [comment]
Hi @Webklex 
Thanks for quickly response.
I send you a dump of `$message->getStructure()->raw;`
I use 2.4.0 package version and imap protocol
"""
\r\n
--Apple-Mail-CB6C9F65-9FDD-4F33-864A-21E33CD728F0\r\n
Content-Type: text/plain;\r\n
\tcharset=utf-8\r\n
Content-Transfer-Encoding: quoted-printable\r\n
\r\n
\r\n
--Apple-Mail-CB6C9F65-9FDD-4F33-864A-21E33CD728F0\r\n
Content-Type: image/jpeg;\r\n
\tname=IMG_0832.jpg;\r\n
\tx-apple-part-url=BD9FDA9F-8907-4350-AA6B-FA140A45806F\r\n
Content-Disposition: inline;\r\n
\tfilename=IMG_0832.jpg\r\n
Content-Transfer-Encoding: base64\r\n
\r\n
/9j/4AAUSkZJRgABAQEBLAEsAABBTVBG/+EI0kV4aWYAAE1NACoAAAAIAA0BDwACAAAABgAAAKoB\r\n
EAACAAAACgAAALABEgADAAAAAQAGAAABGgAFAAAAAQAAALoBGwAFAAAAAQAAAMIBKAADAAAAAQAC\r\n
AAABMQACAAAABwAAAMoBMgACAAAAFAAAANIBPAACAAAACgAAAOYBQgAEAAAAAQAAAgABQwAEAAAA\r\n

etc

\r\n
--Apple-Mail-CB6C9F65-9FDD-4F33-864A-21E33CD728F0\r\n
Content-Type: text/plain;\r\n
\tcharset=utf-8\r\n
Content-Transfer-Encoding: quoted-printable\r\n
\r\n
\r\n
\r\n
Wys=C5=82ane z iPhone'a=\r\n
\r\n
--Apple-Mail-CB6C9F65-9FDD-4F33-864A-21E33CD728F0--\r\n
"""

**Comment by Webklex** [comment]
Hi @Krzysztof-Pluskota ,
thanks for the quick followup. Which part / section of it are you expecting to be an attachment?

Best regards,

**Comment by Krzysztof-Pluskota** [comment]
I'm not sure if you are asking about it, but inside this is a encoded attachment

![image](https://user-images.githubusercontent.com/30027192/104933359-1ca73f80-59a9-11eb-9732-47c626c51438.png)

**Comment by Webklex** [comment]
Hi @Krzysztof-Pluskota ,
please update to the latest release [v2.4.3](https://github.com/Webklex/php-imap/releases/tag/2.4.3).

Best regards,

**Comment by Krzysztof-Pluskota** [comment]
Hi @Webklex 
Thx for working on my case. I updated to v2.4.3 but i still have the same issue. I attach a file with all what a i get from `$msg->getTextBody()`
[getTextBody.txt](https://github.com/Webklex/php-imap/files/5855567/getTextBody.txt)

for example 
 `$msg->hasAttachments()` still return false.

**Comment by Webklex** [comment]
Hi @Krzysztof-Pluskota ,
thanks for testing.

Could you donate a test message to github@webklex.com? This way I can parse it myself and take a closer look at it.

Best regards,

**Comment by Krzysztof-Pluskota** [comment]
Hi @Webklex

My boss just send you a test email. His mail: przemyslaw.tkaczyk@gmail.com

**Comment by Webklex** [comment]
Hi @Krzysztof-Pluskota ,
please update to the latest release [v2.4.4](https://github.com/Webklex/php-imap/releases/tag/2.4.4).

Best regards,

**Comment by Krzysztof-Pluskota** [comment]
Hi @Webklex 

Thx for help. Now it's working fine.

**Comment by irfan9000** [comment]
@Webklex @Krzysztof-Pluskota @Korko @Max13 @Slauta 

IOS attachment is not fetching. Kindly someone helps me. My email is:  irfan.iqbal7933@gmail.com
