### ISSUE TITLE
Empty body when there is a file attachment

### ISSUE THREAD

**Issue by narguelles** [Webklex/php-imap#91]
Returns an empty message body when there is an attachment detected on the email.

    "data": [
        {
            "fetch_options": 2,
            "fetch_body": null,
            "fetch_flags": null,
            "header": {
                "raw": "REDACTED",
                "fallback_encoding": "UTF-8"
            },
            "raw_body": null,
            "bodies": [],
            "attachments": [
                {},
                {}
            ],
            "flags": []
        }
    ],

**Comment by Webklex** [comment]
Hi @narguelles ,
thanks for your report.

The raw body looks off - which provider are you using?

Best regards,

**Comment by narguelles** [comment]
Office 365. it was doing okay until yesterday though

**Comment by Webklex** [comment]
Oh Office aka Microsoft...
Well you might want to check #81 and #86

You can try a few things: 
- Remove this particular email if you feel like it is stuck at this particular one (the message structure you are getting is not valid at all)
- Try to fetch the message a few times and / or wait a few minutes - office seems to have some troubles from time to time
- Migrate to a different provider

Best regards,

**Comment by narguelles** [comment]
I also tried it using a gmail account. but still got the same result.

**Comment by Webklex** [comment]
Please take a look at https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and try to provide as much additional context as possible (code to reproduce, config used, used versions, etc). I'm unable to reproduce this behavior (testen on custom debian/postfix and gmail).

**Comment by narguelles** [comment]
I'm sorry, I do some testing and I found out that it only happens when there is an inline image attachment on the body together with an attached file.

**Comment by narguelles** [comment]
This is the rawbody that I get.

"""
--00000000000085f71905b97b79cf
Content-Type: multipart/related; boundary="00000000000085f71905b97b79ce"

--00000000000085f71905b97b79ce
Content-Type: multipart/alternative; boundary="00000000000085f71805b97b79cd"

--00000000000085f71805b97b79cd
Content-Type: text/plain; charset="UTF-8"

Test[image: image.png]

--00000000000085f71805b97b79cd
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">Test<img src="cid:ii_kk878x030" alt="image.png" width="452" height="328"><br></div>

--00000000000085f71805b97b79cd--
--00000000000085f71905b97b79ce
Content-Type: image/png; name="image.png"
Content-Disposition: inline; filename="image.png"
Content-Transfer-Encoding: base64
Content-ID: <ii_kk878x030>
X-Attachment-Id: ii_kk878x030

iVBORw0KGgoAAAANSUhEUgAAAiYAAAGPCAYAAABoNRv9AAAgAElEQVR4Aey93U9cV5736z8FJCQu

**Comment by Webklex** [comment]
Hi @narguelles ,
I just forwarded you my test message. Please try to parse this one, if it does not fail, please donate a "broken" one to github@webklex.com.

Best regards,

**Comment by narguelles** [comment]
I forwarded it to my imap email, your email does not fail on parsing, with inline image, but I re forwarded it with email attachment and it fails.








________________________________

**Comment by Webklex** [comment]
So you have a client which "creates" non working messages? Could you use it to forward it back to me so I can take a closer look at it? :)

Best regards,

**Comment by narguelles** [comment]
Done.. Thanks!



________________________________

**Comment by narguelles** [comment]
I also found out the text/html content type is missing when there is an inline attachment and file attachment on the email


Webklex\PHPIMAP\Attribute {#1625
  #name: "content_type"
  #values: array:1 [
    0 => "multipart/related"
  ]
}


Webklex\PHPIMAP\Attribute {#1616
  #name: "content_type"
  #values: array:1 [
    0 => "multipart/alternative"
  ]
}


Webklex\PHPIMAP\Attribute {#1667
  #name: "content_type"
  #values: array:1 [
    0 => "image/png"
  ]
}


Webklex\PHPIMAP\Attribute {#1679
  #name: "content_type"
  #values: array:1 [
    0 => "image/jpeg"
  ]
}

________________________________

**Comment by Webklex** [comment]
https://github.com/Webklex/php-imap/commit/5941cee4cde42d88086b99f7d1c2c12cbc136c8e should solve this one as well :)

**Comment by Webklex** [comment]
Hi @narguelles ,
please update to the latest release [v2.4.4](https://github.com/Webklex/php-imap/releases/tag/2.4.4).

Best regards,

**Comment by narguelles** [comment]
its now working fine, thank you very much.
