### ISSUE TITLE
How to bring the message more recently?

### ISSUE THREAD

**Issue by alexv96** [Webklex/php-imap#93]
I am trying to get the most recent message only the first one but with the custom I only get null, I don't know if the query is wrong or if it is missing some parameter.

```
            $oClient = $cm->make([
                'host' => 'outlook.office365.com',
                'port' => 993,
                'protocol' => 'imap',
                'encryption' => 'ssl',
                'validate_cert' => true,
                'username' => 'hola@outlook.cl',
                'password' => '******',
            ]);
               
            $oClient->connect();
            $messages = $oClient->getFolder('INBOX')->query()->WHERE('RECENT')->get();
            dd($messages);
```

![image](https://user-images.githubusercontent.com/33232796/105648284-6c927480-5e89-11eb-9ca0-ddb365c73d1b.png)

**Comment by Webklex** [comment]
Hi @alexv96 ,
thanks for your report.

A few guesses:
1. Maybe Outlook / Office365 doesn't support the `RECENT` search criteria?
2. Outlook / Office365 is known to have "hickups" - retry it a few dozen times...
3. Are there actually any "recent" messages available? 

Best regards,

**Comment by alexv96** [comment]
Recent messages yes, I have several that are from 30 minutes ago, all day I have been receiving messages to the mail.

Because there is another library that occupied in already Yii1 that has 0 problems but more complicated to implement it that is the horde_imap and if they receive data.

**Comment by Webklex** [comment]
Hi, perhaps we have a different understanding of what "recent" means? :)

A message is only considered "recent" by the server, if it has never been fetched; How many clients have access to this account and might have an active session? 
Maybe `Query::since(Carbon::now()->subDays(1))->unseen()` is more what you are looking for?

Btw what is the output of:
```php
/** @var \Webklex\PHPIMAP\Folder $folder */
$folder = $oClient->getFolder('INBOX');

var_dump($folder->getStatus());
```

Best regards,

**Comment by alexv96** [comment]
The old application still works but with another more complex library from what I saw of the email capture, so I don't know if I should look for the ones that haven't been opened since the overview method doesn't work in outlook beyond 6 data limits before it crashes, I thought about capturing the last uid of the most recent message.

And create a for that goes through and makes the query by single message.

**Comment by Webklex** [comment]
Hi @alexv96 
how about `Folder::idle()` to capture all new messages?
```php
/** @var \Webklex\PHPIMAP\Folder $folder */
$folder->idle(function($message){
    echo "New message with the subject '".$message->subject."' received\n";
}, $timeout = 1200, $auto_reconnect = true);
```

Btw what is the output of the following?
```php
/** @var \Webklex\PHPIMAP\Folder $folder */
$folder = $oClient->getFolder('INBOX');

var_dump($folder->getStatus());
```

Best regards,

**Comment by alexv96** [comment]
The output of the folder folder is this

![image](https://user-images.githubusercontent.com/33232796/105729167-b459e000-5f0b-11eb-8a4e-ae47e52717a7.png)

**Comment by Webklex** [comment]
Thanks for the dump, so there should be 3 recent messages currently available.
Is `$folder->query()->recent()->get()` still returning an empty array?

Best regards,

**Comment by alexv96** [comment]
If it works.

Another question a try catch for an exception in case the message id or uid number does not exist and the app does not crash?

![image](https://user-images.githubusercontent.com/33232796/105739589-06ecc980-5f17-11eb-8ca9-8ee5642a0ff4.png)

**Comment by Webklex** [comment]
Hi @alexv96 ,
I'm not sure what you are asking..

Are you trying to catch the exception and prevent a "crash"?
You can do it by surrounding your code with a try catch block:
```php
try {
    $messages = $folder->query()->recent()->get();
} catch (\Webklex\PHPIMAP\Exceptions\RuntimeException $e) {
   // ...do something
}
```

Best regards,
