### ISSUE TITLE
Null bodies when email has both inline image attachment and "normal" attachment

### ISSUE THREAD

**Issue by ricus-zero2one** [Webklex/php-imap#94]
Hi @Webklex 

I'm revisiting upgrading our instance to the new version 2, so far it has been relatively smooth sailing, some namespace changes and adapting to new responses, but I've run into a slight issue while testing a few use cases.

I've noticed that when I send an email (tested on both google and outlook) that has both an inline image attachment, and a "normal" attached file, the email has no body when parsed by the package.

To clarify what I mean with inline image attachment, it's scenarios where people paste an image directly into the email so it forms part of the email content, or for instance clicking attach when composing an email from gmail and selecting inline.

These on their own work fine, however when I send an email that has an inline and normal attachment, for some reason the bodies of the email doesn't get parsed.

For reference: in gmail the email appears as below:

![image](https://user-images.githubusercontent.com/17425015/105688568-70161200-5f02-11eb-853a-3d210782c67c.png)

However when parsed I see the below:

- `->getBodies()` on the email returns an empty array

For some reason I don't get a plain text or html body for these emails which is really strange, I've dumped the result of `$message->getStructure()->raw` into the below file.

[structure.txt](https://github.com/Webklex/php-imap/files/5865690/structure.txt)

Our staging environment is still running version 1.x and the issue didn't happen there for the same email.

Please let me know if there is anything else I can send you that might help with this.

**Comment by Webklex** [comment]
Hi @ricus-zero2one ,
thanks for your report.

Are you using the latest version v2.4.4? If not, please update to it and try again :)

Best regards,

**Comment by ricus-zero2one** [comment]
Hi @Webklex , thanks for the reply.

That was silly of me, I was sill on 2.4.4, all working good now after update thanks :)
