### ISSUE TITLE
Message::getDate() returns Attribute object

### ISSUE THREAD

**Issue by chWagnr** [Webklex/php-imap#95]
Message::getDate() returns Attribute object and not as mentioned in the code a Carbon object. Using version 2.4.4.

**Comment by Webklex** [comment]
Hi @chWagnr ,
thanks for your report. 
This behavior is indeed expected, but I could see why this might be problematic. Therefore I added a new method `Attribute::toDate()` which will allow you to convert any `Attribute::class` instance into a handy `Carbon::class` datetime object.

```php
/** @var \Webklex\PHPIMAP\Message $message */
var_dump($message->getDate()->toDate());
var_dump($message->date->toDate());
```

Best regards,

**Comment by Webklex** [comment]
Hi @chWagnr ,
please update to [v2.5.0](https://github.com/Webklex/php-imap/releases/tag/2.5.0).

Best regards,

**Comment by chWagnr** [comment]
Hi @Webklex ,
thank you very much!
